// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DisputesDispute struct {
	ID                   string
	MerchantID           string
	Livemode             bool
	PaymentIntent        string
	AttemptID            string
	Kind                 string
	Network              string
	NetworkID            string
	NetworkTransactionID string
	Reason               string
	ReasonCode           string
	Amount               int64
	Currency             string
	Stage                string
	Status               string
	Liability            string
	Evidence             []byte
	EvidenceSubmittedAt  pgtype.Timestamptz
	DueBy                pgtype.Timestamptz
	NetworkDueBy         pgtype.Timestamptz
	AuthorizedAt         pgtype.Timestamptz
	NotifiedAt           pgtype.Timestamptz
	ContestedAt          pgtype.Timestamptz
	Blocked              int64
	BlockedAt            pgtype.Timestamptz
	Trace                []byte
	Funds                string
	PendingAction        string
	ActionError          string
	ActionRetryAt        pgtype.Timestamptz
	NetworkVersion       int32
	Outcome              string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	ClosedAt             pgtype.Timestamptz
}

type DisputesFraudReport struct {
	ID            string
	MerchantID    string
	Livemode      bool
	PaymentIntent string
	Network       string
	NetworkID     string
	FraudType     string
	Amount        int64
	Currency      string
	ReportedAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type DisputesHistory struct {
	ID        int64
	DisputeID string
	At        pgtype.Timestamptz
	Kind      string
	Detail    string
}

type DisputesTestCase struct {
	ID                   string
	NetworkTransactionID string
	Network              string
	Amount               int64
	Currency             string
	ReasonCode           string
	Stage                string
	Status               string
	Outcome              string
	RespondBy            pgtype.Timestamptz
	DecideBy             pgtype.Timestamptz
	EscalatedEvidence    string
	AuthorizedAt         pgtype.Timestamptz
	OpenedAt             pgtype.Timestamptz
	Version              int32
}
