// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PaymentsAttempt struct {
	ID                     string
	IntentID               string
	Number                 int32
	PaymentMethod          string
	Amount                 int64
	Status                 string
	Authenticated          bool
	RailReference          string
	DeclineCode            string
	LedgerHold             pgtype.Text
	CaptureAmount          pgtype.Int8
	AmountCaptured         int64
	AuthorizationExpiresAt pgtype.Timestamptz
	UnknownSince           pgtype.Timestamptz
	Resolutions            int32
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	Initiator              string
	StoresCredential       bool
	Installments           pgtype.Int4
	InstallmentsFinancedBy pgtype.Text
	NetworkTransactionID   string
	ClearedOn              pgtype.Date
	AmountCleared          pgtype.Int8
}

type PaymentsIntent struct {
	ID                     string
	MerchantID             string
	Livemode               bool
	Amount                 int64
	Currency               string
	CaptureMethod          string
	Status                 string
	PaymentMethod          string
	Description            string
	AmountCapturable       int64
	AmountReceived         int64
	AmountRefunded         int64
	LatestAttempt          pgtype.Text
	LastErrorCode          string
	LastDeclineCode        string
	LastErrorMessage       string
	NextAction             string
	CancellationReason     string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	Installments           pgtype.Int4
	InstallmentsFinancedBy pgtype.Text
	SetupFutureUsage       string
}

type PaymentsLedgerAccount struct {
	MerchantID string
	Livemode   bool
	Currency   string
	Role       string
	AccountID  string
}

type PaymentsPaymentMethod struct {
	ID                   string
	MerchantID           string
	Livemode             bool
	Type                 string
	VaultToken           string
	Brand                string
	Bin                  string
	Last4                string
	ExpMonth             int32
	ExpYear              int32
	VaultFingerprint     string
	CreatedAt            pgtype.Timestamptz
	NetworkTransactionID string
}

type PaymentsRefund struct {
	ID            string
	IntentID      string
	AttemptID     string
	MerchantID    string
	Livemode      bool
	Amount        int64
	Currency      string
	Reason        string
	Status        string
	RailReference string
	FailureReason string
	LedgerTxn     pgtype.Text
	UnknownSince  pgtype.Timestamptz
	Resolutions   int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	ClearedOn     pgtype.Date
}

type PaymentsTestRail struct {
	Key              string
	Kind             string
	AuthorizationKey string
	Amount           int64
	Status           string
	Reference        string
	Detail           string
	Calls            int32
	Queries          int32
	CreatedAt        pgtype.Timestamptz
}
