// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attemptByServerTransaction = `-- name: AttemptByServerTransaction :one
SELECT id, intent_id, number, payment_method, amount, status, authenticated, rail_reference, decline_code, ledger_hold, capture_amount, amount_captured, authorization_expires_at, unknown_since, resolutions, created_at, updated_at, initiator, stores_credential, installments, installments_financed_by, network_transaction_id, cleared_on, amount_cleared, ip, risk_decision, risk_decision_id, three_ds_server_trans_id, three_ds_version, three_ds_status, ds_trans_id, acs_trans_id, acs_url, eci, authentication_value, liability_shift FROM payments.attempts WHERE three_ds_server_trans_id = $1
`

func (q *Queries) AttemptByServerTransaction(ctx context.Context, threeDsServerTransID string) (PaymentsAttempt, error) {
	row := q.db.QueryRow(ctx, attemptByServerTransaction, threeDsServerTransID)
	var i PaymentsAttempt
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.Number,
		&i.PaymentMethod,
		&i.Amount,
		&i.Status,
		&i.Authenticated,
		&i.RailReference,
		&i.DeclineCode,
		&i.LedgerHold,
		&i.CaptureAmount,
		&i.AmountCaptured,
		&i.AuthorizationExpiresAt,
		&i.UnknownSince,
		&i.Resolutions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Initiator,
		&i.StoresCredential,
		&i.Installments,
		&i.InstallmentsFinancedBy,
		&i.NetworkTransactionID,
		&i.ClearedOn,
		&i.AmountCleared,
		&i.Ip,
		&i.RiskDecision,
		&i.RiskDecisionID,
		&i.ThreeDsServerTransID,
		&i.ThreeDsVersion,
		&i.ThreeDsStatus,
		&i.DsTransID,
		&i.AcsTransID,
		&i.AcsUrl,
		&i.Eci,
		&i.AuthenticationValue,
		&i.LiabilityShift,
	)
	return i, err
}

const attemptsToExpire = `-- name: AttemptsToExpire :many
SELECT id FROM payments.attempts
WHERE status = 'authorized' AND authorization_expires_at <= $1::timestamptz
ORDER BY authorization_expires_at, id
LIMIT $2::integer
`

type AttemptsToExpireParams struct {
	Now      pgtype.Timestamptz
	MaxCount int32
}

func (q *Queries) AttemptsToExpire(ctx context.Context, arg AttemptsToExpireParams) ([]string, error) {
	rows, err := q.db.Query(ctx, attemptsToExpire, arg.Now, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const attemptsToResolve = `-- name: AttemptsToResolve :many
SELECT id FROM payments.attempts
WHERE status IN ('authenticating', 'authorizing', 'authorization_unknown', 'capturing', 'capture_unknown', 'voiding', 'void_unknown')
  AND updated_at <= $1::timestamptz
ORDER BY updated_at, id
LIMIT $2::integer
`

type AttemptsToResolveParams struct {
	Before   pgtype.Timestamptz
	MaxCount int32
}

func (q *Queries) AttemptsToResolve(ctx context.Context, arg AttemptsToResolveParams) ([]string, error) {
	rows, err := q.db.Query(ctx, attemptsToResolve, arg.Before, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimPaymentMethodsToTokenize = `-- name: ClaimPaymentMethodsToTokenize :many
UPDATE payments.payment_methods SET network_token_status = 'provisioning', network_token_since = $1
WHERE id IN (
    SELECT c.id FROM payments.payment_methods c
    WHERE c.livemode AND (c.network_token_status = '' OR (c.network_token_status = 'provisioning' AND c.network_token_since < $2))
    ORDER BY c.id
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
RETURNING id, merchant_id, livemode, vault_token
`

type ClaimPaymentMethodsToTokenizeParams struct {
	Now         pgtype.Timestamptz
	StaleBefore pgtype.Timestamptz
	MaxCount    int32
}

type ClaimPaymentMethodsToTokenizeRow struct {
	ID         string
	MerchantID string
	Livemode   bool
	VaultToken string
}

// Live cards without a network token yet, or whose provisioning stopped half-way.
func (q *Queries) ClaimPaymentMethodsToTokenize(ctx context.Context, arg ClaimPaymentMethodsToTokenizeParams) ([]ClaimPaymentMethodsToTokenizeRow, error) {
	rows, err := q.db.Query(ctx, claimPaymentMethodsToTokenize, arg.Now, arg.StaleBefore, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimPaymentMethodsToTokenizeRow{}
	for rows.Next() {
		var i ClaimPaymentMethodsToTokenizeRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Livemode,
			&i.VaultToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearRefund = `-- name: ClearRefund :execrows
UPDATE payments.refunds SET cleared_on = $1
WHERE id = $2 AND status = 'succeeded' AND amount = $3 AND cleared_on IS NULL
`

type ClearRefundParams struct {
	ClearedOn pgtype.Date
	ID        string
	Amount    int64
}

func (q *Queries) ClearRefund(ctx context.Context, arg ClearRefundParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearRefund, arg.ClearedOn, arg.ID, arg.Amount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAttempt = `-- name: GetAttempt :one
SELECT id, intent_id, number, payment_method, amount, status, authenticated, rail_reference, decline_code, ledger_hold, capture_amount, amount_captured, authorization_expires_at, unknown_since, resolutions, created_at, updated_at, initiator, stores_credential, installments, installments_financed_by, network_transaction_id, cleared_on, amount_cleared, ip, risk_decision, risk_decision_id, three_ds_server_trans_id, three_ds_version, three_ds_status, ds_trans_id, acs_trans_id, acs_url, eci, authentication_value, liability_shift FROM payments.attempts WHERE id = $1
`

func (q *Queries) GetAttempt(ctx context.Context, id string) (PaymentsAttempt, error) {
	row := q.db.QueryRow(ctx, getAttempt, id)
	var i PaymentsAttempt
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.Number,
		&i.PaymentMethod,
		&i.Amount,
		&i.Status,
		&i.Authenticated,
		&i.RailReference,
		&i.DeclineCode,
		&i.LedgerHold,
		&i.CaptureAmount,
		&i.AmountCaptured,
		&i.AuthorizationExpiresAt,
		&i.UnknownSince,
		&i.Resolutions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Initiator,
		&i.StoresCredential,
		&i.Installments,
		&i.InstallmentsFinancedBy,
		&i.NetworkTransactionID,
		&i.ClearedOn,
		&i.AmountCleared,
		&i.Ip,
		&i.RiskDecision,
		&i.RiskDecisionID,
		&i.ThreeDsServerTransID,
		&i.ThreeDsVersion,
		&i.ThreeDsStatus,
		&i.DsTransID,
		&i.AcsTransID,
		&i.AcsUrl,
		&i.Eci,
		&i.AuthenticationValue,
		&i.LiabilityShift,
	)
	return i, err
}

const getIntent = `-- name: GetIntent :one
SELECT id, merchant_id, livemode, amount, currency, capture_method, status, payment_method, description, amount_capturable, amount_received, amount_refunded, latest_attempt, last_error_code, last_decline_code, last_error_message, next_action, cancellation_reason, created_at, updated_at, installments, installments_financed_by, setup_future_usage, request_three_d_secure, next_action_url, risk_decision, risk_decision_id FROM payments.intents WHERE id = $1 AND merchant_id = $2 AND livemode = $3
`

type GetIntentParams struct {
	ID         string
	MerchantID string
	Livemode   bool
}

func (q *Queries) GetIntent(ctx context.Context, arg GetIntentParams) (PaymentsIntent, error) {
	row := q.db.QueryRow(ctx, getIntent, arg.ID, arg.MerchantID, arg.Livemode)
	var i PaymentsIntent
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Amount,
		&i.Currency,
		&i.CaptureMethod,
		&i.Status,
		&i.PaymentMethod,
		&i.Description,
		&i.AmountCapturable,
		&i.AmountReceived,
		&i.AmountRefunded,
		&i.LatestAttempt,
		&i.LastErrorCode,
		&i.LastDeclineCode,
		&i.LastErrorMessage,
		&i.NextAction,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Installments,
		&i.InstallmentsFinancedBy,
		&i.SetupFutureUsage,
		&i.RequestThreeDSecure,
		&i.NextActionUrl,
		&i.RiskDecision,
		&i.RiskDecisionID,
	)
	return i, err
}

const getIntentByID = `-- name: GetIntentByID :one
SELECT id, merchant_id, livemode, amount, currency, capture_method, status, payment_method, description, amount_capturable, amount_received, amount_refunded, latest_attempt, last_error_code, last_decline_code, last_error_message, next_action, cancellation_reason, created_at, updated_at, installments, installments_financed_by, setup_future_usage, request_three_d_secure, next_action_url, risk_decision, risk_decision_id FROM payments.intents WHERE id = $1
`

func (q *Queries) GetIntentByID(ctx context.Context, id string) (PaymentsIntent, error) {
	row := q.db.QueryRow(ctx, getIntentByID, id)
	var i PaymentsIntent
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Amount,
		&i.Currency,
		&i.CaptureMethod,
		&i.Status,
		&i.PaymentMethod,
		&i.Description,
		&i.AmountCapturable,
		&i.AmountReceived,
		&i.AmountRefunded,
		&i.LatestAttempt,
		&i.LastErrorCode,
		&i.LastDeclineCode,
		&i.LastErrorMessage,
		&i.NextAction,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Installments,
		&i.InstallmentsFinancedBy,
		&i.SetupFutureUsage,
		&i.RequestThreeDSecure,
		&i.NextActionUrl,
		&i.RiskDecision,
		&i.RiskDecisionID,
	)
	return i, err
}

const getLedgerAccounts = `-- name: GetLedgerAccounts :many
SELECT role, account_id FROM payments.ledger_accounts
WHERE merchant_id = $1 AND livemode = $2 AND currency = $3
`

type GetLedgerAccountsParams struct {
	MerchantID string
	Livemode   bool
	Currency   string
}

type GetLedgerAccountsRow struct {
	Role      string
	AccountID string
}

func (q *Queries) GetLedgerAccounts(ctx context.Context, arg GetLedgerAccountsParams) ([]GetLedgerAccountsRow, error) {
	rows, err := q.db.Query(ctx, getLedgerAccounts, arg.MerchantID, arg.Livemode, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLedgerAccountsRow{}
	for rows.Next() {
		var i GetLedgerAccountsRow
		if err := rows.Scan(&i.Role, &i.AccountID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentMethod = `-- name: GetPaymentMethod :one
SELECT id, merchant_id, livemode, type, vault_token, brand, bin, last4, exp_month, exp_year, vault_fingerprint, created_at, network_transaction_id, network_token_reference, network_token_status, network_token_since, network_token_event_at FROM payments.payment_methods WHERE id = $1 AND merchant_id = $2 AND livemode = $3
`

type GetPaymentMethodParams struct {
	ID         string
	MerchantID string
	Livemode   bool
}

func (q *Queries) GetPaymentMethod(ctx context.Context, arg GetPaymentMethodParams) (PaymentsPaymentMethod, error) {
	row := q.db.QueryRow(ctx, getPaymentMethod, arg.ID, arg.MerchantID, arg.Livemode)
	var i PaymentsPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Type,
		&i.VaultToken,
		&i.Brand,
		&i.Bin,
		&i.Last4,
		&i.ExpMonth,
		&i.ExpYear,
		&i.VaultFingerprint,
		&i.CreatedAt,
		&i.NetworkTransactionID,
		&i.NetworkTokenReference,
		&i.NetworkTokenStatus,
		&i.NetworkTokenSince,
		&i.NetworkTokenEventAt,
	)
	return i, err
}

const getPaymentMethodByToken = `-- name: GetPaymentMethodByToken :one
SELECT id, merchant_id, livemode, type, vault_token, brand, bin, last4, exp_month, exp_year, vault_fingerprint, created_at, network_transaction_id, network_token_reference, network_token_status, network_token_since, network_token_event_at FROM payments.payment_methods WHERE vault_token = $1
`

func (q *Queries) GetPaymentMethodByToken(ctx context.Context, vaultToken string) (PaymentsPaymentMethod, error) {
	row := q.db.QueryRow(ctx, getPaymentMethodByToken, vaultToken)
	var i PaymentsPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Type,
		&i.VaultToken,
		&i.Brand,
		&i.Bin,
		&i.Last4,
		&i.ExpMonth,
		&i.ExpYear,
		&i.VaultFingerprint,
		&i.CreatedAt,
		&i.NetworkTransactionID,
		&i.NetworkTokenReference,
		&i.NetworkTokenStatus,
		&i.NetworkTokenSince,
		&i.NetworkTokenEventAt,
	)
	return i, err
}

const getRailOperation = `-- name: GetRailOperation :one
SELECT key, kind, authorization_key, amount, status, reference, detail, calls, queries, created_at FROM payments.test_rail WHERE key = $1 FOR UPDATE
`

func (q *Queries) GetRailOperation(ctx context.Context, key string) (PaymentsTestRail, error) {
	row := q.db.QueryRow(ctx, getRailOperation, key)
	var i PaymentsTestRail
	err := row.Scan(
		&i.Key,
		&i.Kind,
		&i.AuthorizationKey,
		&i.Amount,
		&i.Status,
		&i.Reference,
		&i.Detail,
		&i.Calls,
		&i.Queries,
		&i.CreatedAt,
	)
	return i, err
}

const getRefund = `-- name: GetRefund :one
SELECT id, intent_id, attempt_id, merchant_id, livemode, amount, currency, reason, status, rail_reference, failure_reason, ledger_txn, unknown_since, resolutions, created_at, updated_at, cleared_on FROM payments.refunds WHERE id = $1 AND merchant_id = $2 AND livemode = $3
`

type GetRefundParams struct {
	ID         string
	MerchantID string
	Livemode   bool
}

func (q *Queries) GetRefund(ctx context.Context, arg GetRefundParams) (PaymentsRefund, error) {
	row := q.db.QueryRow(ctx, getRefund, arg.ID, arg.MerchantID, arg.Livemode)
	var i PaymentsRefund
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.AttemptID,
		&i.MerchantID,
		&i.Livemode,
		&i.Amount,
		&i.Currency,
		&i.Reason,
		&i.Status,
		&i.RailReference,
		&i.FailureReason,
		&i.LedgerTxn,
		&i.UnknownSince,
		&i.Resolutions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClearedOn,
	)
	return i, err
}

const getRefundByID = `-- name: GetRefundByID :one
SELECT id, intent_id, attempt_id, merchant_id, livemode, amount, currency, reason, status, rail_reference, failure_reason, ledger_txn, unknown_since, resolutions, created_at, updated_at, cleared_on FROM payments.refunds WHERE id = $1
`

func (q *Queries) GetRefundByID(ctx context.Context, id string) (PaymentsRefund, error) {
	row := q.db.QueryRow(ctx, getRefundByID, id)
	var i PaymentsRefund
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.AttemptID,
		&i.MerchantID,
		&i.Livemode,
		&i.Amount,
		&i.Currency,
		&i.Reason,
		&i.Status,
		&i.RailReference,
		&i.FailureReason,
		&i.LedgerTxn,
		&i.UnknownSince,
		&i.Resolutions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClearedOn,
	)
	return i, err
}

const insertAttempt = `-- name: InsertAttempt :exec
INSERT INTO payments.attempts (id, intent_id, number, payment_method, amount, status, initiator, stores_credential,
                              installments, installments_financed_by, ip, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, $12, $12)
`

type InsertAttemptParams struct {
	ID                     string
	IntentID               string
	Number                 int32
	PaymentMethod          string
	Amount                 int64
	Status                 string
	Initiator              string
	StoresCredential       bool
	Installments           pgtype.Int4
	InstallmentsFinancedBy pgtype.Text
	Ip                     string
	CreatedAt              pgtype.Timestamptz
}

func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) error {
	_, err := q.db.Exec(ctx, insertAttempt,
		arg.ID,
		arg.IntentID,
		arg.Number,
		arg.PaymentMethod,
		arg.Amount,
		arg.Status,
		arg.Initiator,
		arg.StoresCredential,
		arg.Installments,
		arg.InstallmentsFinancedBy,
		arg.Ip,
		arg.CreatedAt,
	)
	return err
}

const insertIntent = `-- name: InsertIntent :exec
INSERT INTO payments.intents (id, merchant_id, livemode, amount, currency, capture_method, status, payment_method,
                              description, installments, installments_financed_by, setup_future_usage,
                              request_three_d_secure, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11, $12, $13,
        $14, $14)
`

type InsertIntentParams struct {
	ID                     string
	MerchantID             string
	Livemode               bool
	Amount                 int64
	Currency               string
	CaptureMethod          string
	Status                 string
	PaymentMethod          string
	Description            string
	Installments           pgtype.Int4
	InstallmentsFinancedBy pgtype.Text
	SetupFutureUsage       string
	RequestThreeDSecure    string
	CreatedAt              pgtype.Timestamptz
}

func (q *Queries) InsertIntent(ctx context.Context, arg InsertIntentParams) error {
	_, err := q.db.Exec(ctx, insertIntent,
		arg.ID,
		arg.MerchantID,
		arg.Livemode,
		arg.Amount,
		arg.Currency,
		arg.CaptureMethod,
		arg.Status,
		arg.PaymentMethod,
		arg.Description,
		arg.Installments,
		arg.InstallmentsFinancedBy,
		arg.SetupFutureUsage,
		arg.RequestThreeDSecure,
		arg.CreatedAt,
	)
	return err
}

const insertLedgerAccount = `-- name: InsertLedgerAccount :exec
INSERT INTO payments.ledger_accounts (merchant_id, livemode, currency, role, account_id) VALUES ($1, $2, $3, $4, $5)
`

type InsertLedgerAccountParams struct {
	MerchantID string
	Livemode   bool
	Currency   string
	Role       string
	AccountID  string
}

func (q *Queries) InsertLedgerAccount(ctx context.Context, arg InsertLedgerAccountParams) error {
	_, err := q.db.Exec(ctx, insertLedgerAccount,
		arg.MerchantID,
		arg.Livemode,
		arg.Currency,
		arg.Role,
		arg.AccountID,
	)
	return err
}

const insertPaymentMethod = `-- name: InsertPaymentMethod :one
INSERT INTO payments.payment_methods (id, merchant_id, livemode, type, vault_token, brand, bin, last4, exp_month,
                                      exp_year, vault_fingerprint, created_at)
VALUES ($1, $2, $3, 'card', $4, $5, $6, $7, $8, $9,
        $10, $11)
ON CONFLICT (vault_token) DO NOTHING
RETURNING id, merchant_id, livemode, type, vault_token, brand, bin, last4, exp_month, exp_year, vault_fingerprint, created_at, network_transaction_id, network_token_reference, network_token_status, network_token_since, network_token_event_at
`

type InsertPaymentMethodParams struct {
	ID               string
	MerchantID       string
	Livemode         bool
	VaultToken       string
	Brand            string
	Bin              string
	Last4            string
	ExpMonth         int32
	ExpYear          int32
	VaultFingerprint string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) InsertPaymentMethod(ctx context.Context, arg InsertPaymentMethodParams) (PaymentsPaymentMethod, error) {
	row := q.db.QueryRow(ctx, insertPaymentMethod,
		arg.ID,
		arg.MerchantID,
		arg.Livemode,
		arg.VaultToken,
		arg.Brand,
		arg.Bin,
		arg.Last4,
		arg.ExpMonth,
		arg.ExpYear,
		arg.VaultFingerprint,
		arg.CreatedAt,
	)
	var i PaymentsPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Type,
		&i.VaultToken,
		&i.Brand,
		&i.Bin,
		&i.Last4,
		&i.ExpMonth,
		&i.ExpYear,
		&i.VaultFingerprint,
		&i.CreatedAt,
		&i.NetworkTransactionID,
		&i.NetworkTokenReference,
		&i.NetworkTokenStatus,
		&i.NetworkTokenSince,
		&i.NetworkTokenEventAt,
	)
	return i, err
}

const insertRailOperation = `-- name: InsertRailOperation :exec
INSERT INTO payments.test_rail (key, kind, authorization_key, amount, status, reference, detail, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertRailOperationParams struct {
	Key              string
	Kind             string
	AuthorizationKey string
	Amount           int64
	Status           string
	Reference        string
	Detail           string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) InsertRailOperation(ctx context.Context, arg InsertRailOperationParams) error {
	_, err := q.db.Exec(ctx, insertRailOperation,
		arg.Key,
		arg.Kind,
		arg.AuthorizationKey,
		arg.Amount,
		arg.Status,
		arg.Reference,
		arg.Detail,
		arg.CreatedAt,
	)
	return err
}

const insertRefund = `-- name: InsertRefund :exec
INSERT INTO payments.refunds (id, intent_id, attempt_id, merchant_id, livemode, amount, currency, reason, status,
                              created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'pending', $9, $9)
`

type InsertRefundParams struct {
	ID         string
	IntentID   string
	AttemptID  string
	MerchantID string
	Livemode   bool
	Amount     int64
	Currency   string
	Reason     string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertRefund(ctx context.Context, arg InsertRefundParams) error {
	_, err := q.db.Exec(ctx, insertRefund,
		arg.ID,
		arg.IntentID,
		arg.AttemptID,
		arg.MerchantID,
		arg.Livemode,
		arg.Amount,
		arg.Currency,
		arg.Reason,
		arg.CreatedAt,
	)
	return err
}

const intentInconsistencies = `-- name: IntentInconsistencies :many
SELECT i.id, i.status, coalesce(a.status, '') AS attempt_status
FROM payments.intents i
LEFT JOIN payments.attempts a ON a.id = i.latest_attempt
WHERE NOT CASE i.status
    WHEN 'requires_capture' THEN coalesce(a.status = 'authorized' AND i.amount_capturable = a.amount, false)
    WHEN 'succeeded' THEN coalesce(a.status = 'captured' AND i.amount_received = a.amount_captured, false)
    WHEN 'processing' THEN coalesce(a.status IN ('authenticating', 'authorizing', 'authorization_unknown', 'capturing', 'capture_unknown', 'voiding', 'void_unknown'), false)
    WHEN 'requires_action' THEN coalesce(a.status = 'requires_action', false)
    WHEN 'canceled' THEN a.status IS NULL OR a.status IN ('voided', 'declined', 'failed')
    ELSE a.status IS NULL OR a.status IN ('declined', 'failed')
  END
  OR i.amount_refunded <> (SELECT coalesce(sum(r.amount), 0) FROM payments.refunds r WHERE r.intent_id = i.id AND r.status = 'succeeded')
ORDER BY i.id
`

type IntentInconsistenciesRow struct {
	ID            string
	Status        string
	AttemptStatus string
}

// An intent's status must agree with its latest attempt and its amounts. Statuses that
// need an attempt fail the check when it is missing: coalesce turns NULL into false.
func (q *Queries) IntentInconsistencies(ctx context.Context) ([]IntentInconsistenciesRow, error) {
	rows, err := q.db.Query(ctx, intentInconsistencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntentInconsistenciesRow{}
	for rows.Next() {
		var i IntentInconsistenciesRow
		if err := rows.Scan(&i.ID, &i.Status, &i.AttemptStatus); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntents = `-- name: ListIntents :many
SELECT id, merchant_id, livemode, amount, currency, capture_method, status, payment_method, description, amount_capturable, amount_received, amount_refunded, latest_attempt, last_error_code, last_decline_code, last_error_message, next_action, cancellation_reason, created_at, updated_at, installments, installments_financed_by, setup_future_usage, request_three_d_secure, next_action_url, risk_decision, risk_decision_id FROM payments.intents
WHERE merchant_id = $1 AND livemode = $2
  AND ($3::text = '' OR id < $3)
  AND ($4::text = '' OR id > $4)
ORDER BY CASE WHEN $4 <> '' THEN id END ASC, id DESC
LIMIT $5::integer
`

type ListIntentsParams struct {
	MerchantID    string
	Livemode      bool
	StartingAfter string
	EndingBefore  string
	MaxCount      int32
}

func (q *Queries) ListIntents(ctx context.Context, arg ListIntentsParams) ([]PaymentsIntent, error) {
	rows, err := q.db.Query(ctx, listIntents,
		arg.MerchantID,
		arg.Livemode,
		arg.StartingAfter,
		arg.EndingBefore,
		arg.MaxCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentsIntent{}
	for rows.Next() {
		var i PaymentsIntent
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Livemode,
			&i.Amount,
			&i.Currency,
			&i.CaptureMethod,
			&i.Status,
			&i.PaymentMethod,
			&i.Description,
			&i.AmountCapturable,
			&i.AmountReceived,
			&i.AmountRefunded,
			&i.LatestAttempt,
			&i.LastErrorCode,
			&i.LastDeclineCode,
			&i.LastErrorMessage,
			&i.NextAction,
			&i.CancellationReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Installments,
			&i.InstallmentsFinancedBy,
			&i.SetupFutureUsage,
			&i.RequestThreeDSecure,
			&i.NextActionUrl,
			&i.RiskDecision,
			&i.RiskDecisionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefunds = `-- name: ListRefunds :many
SELECT id, intent_id, attempt_id, merchant_id, livemode, amount, currency, reason, status, rail_reference, failure_reason, ledger_txn, unknown_since, resolutions, created_at, updated_at, cleared_on FROM payments.refunds
WHERE merchant_id = $1 AND livemode = $2
  AND ($3::text = '' OR intent_id = $3)
  AND ($4::text = '' OR id < $4)
  AND ($5::text = '' OR id > $5)
ORDER BY CASE WHEN $5 <> '' THEN id END ASC, id DESC
LIMIT $6::integer
`

type ListRefundsParams struct {
	MerchantID    string
	Livemode      bool
	IntentID      string
	StartingAfter string
	EndingBefore  string
	MaxCount      int32
}

func (q *Queries) ListRefunds(ctx context.Context, arg ListRefundsParams) ([]PaymentsRefund, error) {
	rows, err := q.db.Query(ctx, listRefunds,
		arg.MerchantID,
		arg.Livemode,
		arg.IntentID,
		arg.StartingAfter,
		arg.EndingBefore,
		arg.MaxCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentsRefund{}
	for rows.Next() {
		var i PaymentsRefund
		if err := rows.Scan(
			&i.ID,
			&i.IntentID,
			&i.AttemptID,
			&i.MerchantID,
			&i.Livemode,
			&i.Amount,
			&i.Currency,
			&i.Reason,
			&i.Status,
			&i.RailReference,
			&i.FailureReason,
			&i.LedgerTxn,
			&i.UnknownSince,
			&i.Resolutions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClearedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAttempt = `-- name: LockAttempt :one
SELECT id, intent_id, number, payment_method, amount, status, authenticated, rail_reference, decline_code, ledger_hold, capture_amount, amount_captured, authorization_expires_at, unknown_since, resolutions, created_at, updated_at, initiator, stores_credential, installments, installments_financed_by, network_transaction_id, cleared_on, amount_cleared, ip, risk_decision, risk_decision_id, three_ds_server_trans_id, three_ds_version, three_ds_status, ds_trans_id, acs_trans_id, acs_url, eci, authentication_value, liability_shift FROM payments.attempts WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockAttempt(ctx context.Context, id string) (PaymentsAttempt, error) {
	row := q.db.QueryRow(ctx, lockAttempt, id)
	var i PaymentsAttempt
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.Number,
		&i.PaymentMethod,
		&i.Amount,
		&i.Status,
		&i.Authenticated,
		&i.RailReference,
		&i.DeclineCode,
		&i.LedgerHold,
		&i.CaptureAmount,
		&i.AmountCaptured,
		&i.AuthorizationExpiresAt,
		&i.UnknownSince,
		&i.Resolutions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Initiator,
		&i.StoresCredential,
		&i.Installments,
		&i.InstallmentsFinancedBy,
		&i.NetworkTransactionID,
		&i.ClearedOn,
		&i.AmountCleared,
		&i.Ip,
		&i.RiskDecision,
		&i.RiskDecisionID,
		&i.ThreeDsServerTransID,
		&i.ThreeDsVersion,
		&i.ThreeDsStatus,
		&i.DsTransID,
		&i.AcsTransID,
		&i.AcsUrl,
		&i.Eci,
		&i.AuthenticationValue,
		&i.LiabilityShift,
	)
	return i, err
}

const lockIntent = `-- name: LockIntent :one
SELECT id, merchant_id, livemode, amount, currency, capture_method, status, payment_method, description, amount_capturable, amount_received, amount_refunded, latest_attempt, last_error_code, last_decline_code, last_error_message, next_action, cancellation_reason, created_at, updated_at, installments, installments_financed_by, setup_future_usage, request_three_d_secure, next_action_url, risk_decision, risk_decision_id FROM payments.intents WHERE id = $1 AND merchant_id = $2 AND livemode = $3 FOR UPDATE
`

type LockIntentParams struct {
	ID         string
	MerchantID string
	Livemode   bool
}

func (q *Queries) LockIntent(ctx context.Context, arg LockIntentParams) (PaymentsIntent, error) {
	row := q.db.QueryRow(ctx, lockIntent, arg.ID, arg.MerchantID, arg.Livemode)
	var i PaymentsIntent
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Amount,
		&i.Currency,
		&i.CaptureMethod,
		&i.Status,
		&i.PaymentMethod,
		&i.Description,
		&i.AmountCapturable,
		&i.AmountReceived,
		&i.AmountRefunded,
		&i.LatestAttempt,
		&i.LastErrorCode,
		&i.LastDeclineCode,
		&i.LastErrorMessage,
		&i.NextAction,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Installments,
		&i.InstallmentsFinancedBy,
		&i.SetupFutureUsage,
		&i.RequestThreeDSecure,
		&i.NextActionUrl,
		&i.RiskDecision,
		&i.RiskDecisionID,
	)
	return i, err
}

const lockIntentByID = `-- name: LockIntentByID :one
SELECT id, merchant_id, livemode, amount, currency, capture_method, status, payment_method, description, amount_capturable, amount_received, amount_refunded, latest_attempt, last_error_code, last_decline_code, last_error_message, next_action, cancellation_reason, created_at, updated_at, installments, installments_financed_by, setup_future_usage, request_three_d_secure, next_action_url, risk_decision, risk_decision_id FROM payments.intents WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockIntentByID(ctx context.Context, id string) (PaymentsIntent, error) {
	row := q.db.QueryRow(ctx, lockIntentByID, id)
	var i PaymentsIntent
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Amount,
		&i.Currency,
		&i.CaptureMethod,
		&i.Status,
		&i.PaymentMethod,
		&i.Description,
		&i.AmountCapturable,
		&i.AmountReceived,
		&i.AmountRefunded,
		&i.LatestAttempt,
		&i.LastErrorCode,
		&i.LastDeclineCode,
		&i.LastErrorMessage,
		&i.NextAction,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Installments,
		&i.InstallmentsFinancedBy,
		&i.SetupFutureUsage,
		&i.RequestThreeDSecure,
		&i.NextActionUrl,
		&i.RiskDecision,
		&i.RiskDecisionID,
	)
	return i, err
}

const lockLedgerAccountCreation = `-- name: LockLedgerAccountCreation :exec
SELECT pg_advisory_xact_lock(hashtext('payments.ledger_accounts/' || $1::text))
`

func (q *Queries) LockLedgerAccountCreation(ctx context.Context, scope string) error {
	_, err := q.db.Exec(ctx, lockLedgerAccountCreation, scope)
	return err
}

const lockRailKey = `-- name: LockRailKey :exec
SELECT pg_advisory_xact_lock(hashtext('payments.test_rail/' || $1::text))
`

func (q *Queries) LockRailKey(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, lockRailKey, key)
	return err
}

const lockRefundByID = `-- name: LockRefundByID :one
SELECT id, intent_id, attempt_id, merchant_id, livemode, amount, currency, reason, status, rail_reference, failure_reason, ledger_txn, unknown_since, resolutions, created_at, updated_at, cleared_on FROM payments.refunds WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockRefundByID(ctx context.Context, id string) (PaymentsRefund, error) {
	row := q.db.QueryRow(ctx, lockRefundByID, id)
	var i PaymentsRefund
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.AttemptID,
		&i.MerchantID,
		&i.Livemode,
		&i.Amount,
		&i.Currency,
		&i.Reason,
		&i.Status,
		&i.RailReference,
		&i.FailureReason,
		&i.LedgerTxn,
		&i.UnknownSince,
		&i.Resolutions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClearedOn,
	)
	return i, err
}

const merchantLedgerAccounts = `-- name: MerchantLedgerAccounts :many
SELECT merchant_id, livemode, currency, account_id FROM payments.ledger_accounts
WHERE role = 'merchant_balance' ORDER BY merchant_id, livemode, currency
`

type MerchantLedgerAccountsRow struct {
	MerchantID string
	Livemode   bool
	Currency   string
	AccountID  string
}

func (q *Queries) MerchantLedgerAccounts(ctx context.Context) ([]MerchantLedgerAccountsRow, error) {
	rows, err := q.db.Query(ctx, merchantLedgerAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MerchantLedgerAccountsRow{}
	for rows.Next() {
		var i MerchantLedgerAccountsRow
		if err := rows.Scan(
			&i.MerchantID,
			&i.Livemode,
			&i.Currency,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const merchantTotals = `-- name: MerchantTotals :many
SELECT merchant_id, livemode, currency,
       sum(amount_received - amount_refunded)::bigint AS posted,
       (SELECT coalesce(sum(a.amount), 0) FROM payments.attempts a
          JOIN payments.intents i2 ON i2.id = a.intent_id
         WHERE i2.merchant_id = i.merchant_id AND i2.livemode = i.livemode AND i2.currency = i.currency
           AND a.status IN ('authorized', 'capturing', 'capture_unknown', 'voiding', 'void_unknown'))::bigint AS held
FROM payments.intents i
GROUP BY merchant_id, livemode, currency
`

type MerchantTotalsRow struct {
	MerchantID string
	Livemode   bool
	Currency   string
	Posted     int64
	Held       int64
}

func (q *Queries) MerchantTotals(ctx context.Context) ([]MerchantTotalsRow, error) {
	rows, err := q.db.Query(ctx, merchantTotals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MerchantTotalsRow{}
	for rows.Next() {
		var i MerchantTotalsRow
		if err := rows.Scan(
			&i.MerchantID,
			&i.Livemode,
			&i.Currency,
			&i.Posted,
			&i.Held,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextAttemptNumber = `-- name: NextAttemptNumber :one
SELECT (coalesce(max(number), 0) + 1)::integer FROM payments.attempts WHERE intent_id = $1
`

func (q *Queries) NextAttemptNumber(ctx context.Context, intentID string) (int32, error) {
	row := q.db.QueryRow(ctx, nextAttemptNumber, intentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const outstandingRefunds = `-- name: OutstandingRefunds :one
SELECT coalesce(sum(amount), 0)::bigint FROM payments.refunds
WHERE intent_id = $1 AND status IN ('pending', 'refund_unknown')
`

func (q *Queries) OutstandingRefunds(ctx context.Context, intentID string) (int64, error) {
	row := q.db.QueryRow(ctx, outstandingRefunds, intentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const railApprovedTotal = `-- name: RailApprovedTotal :one
SELECT coalesce(sum(amount), 0)::bigint FROM payments.test_rail
WHERE authorization_key = $1 AND kind = $2 AND status = 'approved'
`

type RailApprovedTotalParams struct {
	AuthorizationKey string
	Kind             string
}

func (q *Queries) RailApprovedTotal(ctx context.Context, arg RailApprovedTotalParams) (int64, error) {
	row := q.db.QueryRow(ctx, railApprovedTotal, arg.AuthorizationKey, arg.Kind)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const refundsToResolve = `-- name: RefundsToResolve :many
SELECT id FROM payments.refunds
WHERE status IN ('pending', 'refund_unknown') AND updated_at <= $1::timestamptz
ORDER BY updated_at, id
LIMIT $2::integer
`

type RefundsToResolveParams struct {
	Before   pgtype.Timestamptz
	MaxCount int32
}

func (q *Queries) RefundsToResolve(ctx context.Context, arg RefundsToResolveParams) ([]string, error) {
	rows, err := q.db.Query(ctx, refundsToResolve, arg.Before, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveAttempt = `-- name: SaveAttempt :exec
UPDATE payments.attempts
SET status = $1, authenticated = $2, rail_reference = $3,
    decline_code = $4, ledger_hold = $5, capture_amount = $6,
    amount_captured = $7, authorization_expires_at = $8,
    unknown_since = $9, resolutions = $10, network_transaction_id = $11,
    cleared_on = $12, amount_cleared = $13, risk_decision = $14,
    risk_decision_id = $15, three_ds_server_trans_id = $16,
    three_ds_version = $17, three_ds_status = $18, ds_trans_id = $19,
    acs_trans_id = $20, acs_url = $21, eci = $22, authentication_value = $23,
    liability_shift = $24, updated_at = $25
WHERE id = $26
`

type SaveAttemptParams struct {
	Status                 string
	Authenticated          bool
	RailReference          string
	DeclineCode            string
	LedgerHold             pgtype.Text
	CaptureAmount          pgtype.Int8
	AmountCaptured         int64
	AuthorizationExpiresAt pgtype.Timestamptz
	UnknownSince           pgtype.Timestamptz
	Resolutions            int32
	NetworkTransactionID   string
	ClearedOn              pgtype.Date
	AmountCleared          pgtype.Int8
	RiskDecision           string
	RiskDecisionID         string
	ThreeDsServerTransID   string
	ThreeDsVersion         string
	ThreeDsStatus          string
	DsTransID              string
	AcsTransID             string
	AcsUrl                 string
	Eci                    string
	AuthenticationValue    string
	LiabilityShift         bool
	UpdatedAt              pgtype.Timestamptz
	ID                     string
}

func (q *Queries) SaveAttempt(ctx context.Context, arg SaveAttemptParams) error {
	_, err := q.db.Exec(ctx, saveAttempt,
		arg.Status,
		arg.Authenticated,
		arg.RailReference,
		arg.DeclineCode,
		arg.LedgerHold,
		arg.CaptureAmount,
		arg.AmountCaptured,
		arg.AuthorizationExpiresAt,
		arg.UnknownSince,
		arg.Resolutions,
		arg.NetworkTransactionID,
		arg.ClearedOn,
		arg.AmountCleared,
		arg.RiskDecision,
		arg.RiskDecisionID,
		arg.ThreeDsServerTransID,
		arg.ThreeDsVersion,
		arg.ThreeDsStatus,
		arg.DsTransID,
		arg.AcsTransID,
		arg.AcsUrl,
		arg.Eci,
		arg.AuthenticationValue,
		arg.LiabilityShift,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const saveIntent = `-- name: SaveIntent :exec
UPDATE payments.intents
SET amount = $1, status = $2, payment_method = $3, description = $4,
    amount_capturable = $5, amount_received = $6, amount_refunded = $7,
    latest_attempt = $8, last_error_code = $9, last_decline_code = $10,
    last_error_message = $11, next_action = $12,
    cancellation_reason = $13, installments = $14,
    installments_financed_by = $15, setup_future_usage = $16,
    request_three_d_secure = $17, next_action_url = $18,
    risk_decision = $19, risk_decision_id = $20, updated_at = $21
WHERE id = $22
`

type SaveIntentParams struct {
	Amount                 int64
	Status                 string
	PaymentMethod          string
	Description            string
	AmountCapturable       int64
	AmountReceived         int64
	AmountRefunded         int64
	LatestAttempt          pgtype.Text
	LastErrorCode          string
	LastDeclineCode        string
	LastErrorMessage       string
	NextAction             string
	CancellationReason     string
	Installments           pgtype.Int4
	InstallmentsFinancedBy pgtype.Text
	SetupFutureUsage       string
	RequestThreeDSecure    string
	NextActionUrl          string
	RiskDecision           string
	RiskDecisionID         string
	UpdatedAt              pgtype.Timestamptz
	ID                     string
}

func (q *Queries) SaveIntent(ctx context.Context, arg SaveIntentParams) error {
	_, err := q.db.Exec(ctx, saveIntent,
		arg.Amount,
		arg.Status,
		arg.PaymentMethod,
		arg.Description,
		arg.AmountCapturable,
		arg.AmountReceived,
		arg.AmountRefunded,
		arg.LatestAttempt,
		arg.LastErrorCode,
		arg.LastDeclineCode,
		arg.LastErrorMessage,
		arg.NextAction,
		arg.CancellationReason,
		arg.Installments,
		arg.InstallmentsFinancedBy,
		arg.SetupFutureUsage,
		arg.RequestThreeDSecure,
		arg.NextActionUrl,
		arg.RiskDecision,
		arg.RiskDecisionID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const saveRailOperation = `-- name: SaveRailOperation :exec
UPDATE payments.test_rail SET status = $2, detail = $3, calls = $4, queries = $5 WHERE key = $1
`

type SaveRailOperationParams struct {
	Key     string
	Status  string
	Detail  string
	Calls   int32
	Queries int32
}

func (q *Queries) SaveRailOperation(ctx context.Context, arg SaveRailOperationParams) error {
	_, err := q.db.Exec(ctx, saveRailOperation,
		arg.Key,
		arg.Status,
		arg.Detail,
		arg.Calls,
		arg.Queries,
	)
	return err
}

const saveRefund = `-- name: SaveRefund :exec
UPDATE payments.refunds
SET status = $1, rail_reference = $2, failure_reason = $3, ledger_txn = $4,
    unknown_since = $5, resolutions = $6, updated_at = $7
WHERE id = $8
`

type SaveRefundParams struct {
	Status        string
	RailReference string
	FailureReason string
	LedgerTxn     pgtype.Text
	UnknownSince  pgtype.Timestamptz
	Resolutions   int32
	UpdatedAt     pgtype.Timestamptz
	ID            string
}

func (q *Queries) SaveRefund(ctx context.Context, arg SaveRefundParams) error {
	_, err := q.db.Exec(ctx, saveRefund,
		arg.Status,
		arg.RailReference,
		arg.FailureReason,
		arg.LedgerTxn,
		arg.UnknownSince,
		arg.Resolutions,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setNetworkToken = `-- name: SetNetworkToken :exec
UPDATE payments.payment_methods
SET network_token_reference = $1, network_token_status = $2, network_token_since = $3
WHERE id = $4 AND network_token_status = 'provisioning' AND network_token_since = $5
`

type SetNetworkTokenParams struct {
	NetworkTokenReference string
	NetworkTokenStatus    string
	Now                   pgtype.Timestamptz
	ID                    string
	ClaimedAt             pgtype.Timestamptz
}

func (q *Queries) SetNetworkToken(ctx context.Context, arg SetNetworkTokenParams) error {
	_, err := q.db.Exec(ctx, setNetworkToken,
		arg.NetworkTokenReference,
		arg.NetworkTokenStatus,
		arg.Now,
		arg.ID,
		arg.ClaimedAt,
	)
	return err
}

const setPaymentMethodNetworkTransaction = `-- name: SetPaymentMethodNetworkTransaction :exec
UPDATE payments.payment_methods SET network_transaction_id = $1
WHERE id = $2 AND network_transaction_id = ''
`

type SetPaymentMethodNetworkTransactionParams struct {
	NetworkTransactionID string
	ID                   string
}

func (q *Queries) SetPaymentMethodNetworkTransaction(ctx context.Context, arg SetPaymentMethodNetworkTransactionParams) error {
	_, err := q.db.Exec(ctx, setPaymentMethodNetworkTransaction, arg.NetworkTransactionID, arg.ID)
	return err
}

const touchRefund = `-- name: TouchRefund :exec
UPDATE payments.refunds SET resolutions = resolutions + 1, updated_at = $1 WHERE id = $2
`

type TouchRefundParams struct {
	UpdatedAt pgtype.Timestamptz
	ID        string
}

func (q *Queries) TouchRefund(ctx context.Context, arg TouchRefundParams) error {
	_, err := q.db.Exec(ctx, touchRefund, arg.UpdatedAt, arg.ID)
	return err
}

const updateCardFromNetworkToken = `-- name: UpdateCardFromNetworkToken :execrows
UPDATE payments.payment_methods
SET last4 = $1, exp_month = $2, exp_year = $3, network_token_status = $4,
    network_token_since = $5, network_token_event_at = $6
WHERE network_token_reference = $7
  AND network_token_status IN ('active', 'suspended')
  AND (network_token_event_at IS NULL OR network_token_event_at <= $6)
`

type UpdateCardFromNetworkTokenParams struct {
	Last4                 string
	ExpMonth              int32
	ExpYear               int32
	NetworkTokenStatus    string
	Now                   pgtype.Timestamptz
	OccurredAt            pgtype.Timestamptz
	NetworkTokenReference string
}

func (q *Queries) UpdateCardFromNetworkToken(ctx context.Context, arg UpdateCardFromNetworkTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCardFromNetworkToken,
		arg.Last4,
		arg.ExpMonth,
		arg.ExpYear,
		arg.NetworkTokenStatus,
		arg.Now,
		arg.OccurredAt,
		arg.NetworkTokenReference,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
