// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allDisputeFunds = `-- name: AllDisputeFunds :many
SELECT reference, status, amount FROM payments.dispute_funds ORDER BY reference
`

type AllDisputeFundsRow struct {
	Reference string
	Status    string
	Amount    int64
}

func (q *Queries) AllDisputeFunds(ctx context.Context) ([]AllDisputeFundsRow, error) {
	rows, err := q.db.Query(ctx, allDisputeFunds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllDisputeFundsRow{}
	for rows.Next() {
		var i AllDisputeFundsRow
		if err := rows.Scan(&i.Reference, &i.Status, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const attemptByServerTransaction = `-- name: AttemptByServerTransaction :one
SELECT id, intent_id, number, payment_method, amount, status, authenticated, rail_reference, decline_code, ledger_hold, capture_amount, amount_captured, authorization_expires_at, unknown_since, resolutions, created_at, updated_at, initiator, stores_credential, installments, installments_financed_by, network_transaction_id, cleared_on, amount_cleared, ip, risk_decision, risk_decision_id, three_ds_server_trans_id, three_ds_version, three_ds_status, ds_trans_id, acs_trans_id, acs_url, eci, authentication_value, liability_shift, fee, split_out FROM payments.attempts WHERE three_ds_server_trans_id = $1
`

func (q *Queries) AttemptByServerTransaction(ctx context.Context, threeDsServerTransID string) (PaymentsAttempt, error) {
	row := q.db.QueryRow(ctx, attemptByServerTransaction, threeDsServerTransID)
	var i PaymentsAttempt
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.Number,
		&i.PaymentMethod,
		&i.Amount,
		&i.Status,
		&i.Authenticated,
		&i.RailReference,
		&i.DeclineCode,
		&i.LedgerHold,
		&i.CaptureAmount,
		&i.AmountCaptured,
		&i.AuthorizationExpiresAt,
		&i.UnknownSince,
		&i.Resolutions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Initiator,
		&i.StoresCredential,
		&i.Installments,
		&i.InstallmentsFinancedBy,
		&i.NetworkTransactionID,
		&i.ClearedOn,
		&i.AmountCleared,
		&i.Ip,
		&i.RiskDecision,
		&i.RiskDecisionID,
		&i.ThreeDsServerTransID,
		&i.ThreeDsVersion,
		&i.ThreeDsStatus,
		&i.DsTransID,
		&i.AcsTransID,
		&i.AcsUrl,
		&i.Eci,
		&i.AuthenticationValue,
		&i.LiabilityShift,
		&i.Fee,
		&i.SplitOut,
	)
	return i, err
}

const attemptsToExpire = `-- name: AttemptsToExpire :many
SELECT id FROM payments.attempts
WHERE status = 'authorized' AND authorization_expires_at <= $1::timestamptz
ORDER BY authorization_expires_at, id
LIMIT $2::integer
`

type AttemptsToExpireParams struct {
	Now      pgtype.Timestamptz
	MaxCount int32
}

func (q *Queries) AttemptsToExpire(ctx context.Context, arg AttemptsToExpireParams) ([]string, error) {
	rows, err := q.db.Query(ctx, attemptsToExpire, arg.Now, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const attemptsToResolve = `-- name: AttemptsToResolve :many
SELECT id FROM payments.attempts
WHERE status IN ('authenticating', 'authorizing', 'authorization_unknown', 'capturing', 'capture_unknown', 'voiding', 'void_unknown')
  AND updated_at <= $1::timestamptz
ORDER BY updated_at, id
LIMIT $2::integer
`

type AttemptsToResolveParams struct {
	Before   pgtype.Timestamptz
	MaxCount int32
}

func (q *Queries) AttemptsToResolve(ctx context.Context, arg AttemptsToResolveParams) ([]string, error) {
	rows, err := q.db.Query(ctx, attemptsToResolve, arg.Before, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const capturedAttemptByNetworkID = `-- name: CapturedAttemptByNetworkID :one
SELECT a.id, a.intent_id, a.number, a.payment_method, a.amount, a.status, a.authenticated, a.rail_reference, a.decline_code, a.ledger_hold, a.capture_amount, a.amount_captured, a.authorization_expires_at, a.unknown_since, a.resolutions, a.created_at, a.updated_at, a.initiator, a.stores_credential, a.installments, a.installments_financed_by, a.network_transaction_id, a.cleared_on, a.amount_cleared, a.ip, a.risk_decision, a.risk_decision_id, a.three_ds_server_trans_id, a.three_ds_version, a.three_ds_status, a.ds_trans_id, a.acs_trans_id, a.acs_url, a.eci, a.authentication_value, a.liability_shift, a.fee, a.split_out FROM payments.attempts a JOIN payments.intents i ON i.id = a.intent_id
WHERE a.network_transaction_id = $1 AND i.livemode = $2 AND a.status = 'captured'
ORDER BY a.created_at DESC
LIMIT 1
`

type CapturedAttemptByNetworkIDParams struct {
	NetworkID string
	Livemode  bool
}

// The captured attempt a card network or the Pix bank names a payment by: its network
// transaction id, or its end-to-end id.
func (q *Queries) CapturedAttemptByNetworkID(ctx context.Context, arg CapturedAttemptByNetworkIDParams) (PaymentsAttempt, error) {
	row := q.db.QueryRow(ctx, capturedAttemptByNetworkID, arg.NetworkID, arg.Livemode)
	var i PaymentsAttempt
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.Number,
		&i.PaymentMethod,
		&i.Amount,
		&i.Status,
		&i.Authenticated,
		&i.RailReference,
		&i.DeclineCode,
		&i.LedgerHold,
		&i.CaptureAmount,
		&i.AmountCaptured,
		&i.AuthorizationExpiresAt,
		&i.UnknownSince,
		&i.Resolutions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Initiator,
		&i.StoresCredential,
		&i.Installments,
		&i.InstallmentsFinancedBy,
		&i.NetworkTransactionID,
		&i.ClearedOn,
		&i.AmountCleared,
		&i.Ip,
		&i.RiskDecision,
		&i.RiskDecisionID,
		&i.ThreeDsServerTransID,
		&i.ThreeDsVersion,
		&i.ThreeDsStatus,
		&i.DsTransID,
		&i.AcsTransID,
		&i.AcsUrl,
		&i.Eci,
		&i.AuthenticationValue,
		&i.LiabilityShift,
		&i.Fee,
		&i.SplitOut,
	)
	return i, err
}

const capturedAttempts = `-- name: CapturedAttempts :many
SELECT id FROM payments.attempts WHERE id = ANY($1::text[]) AND status = 'captured'
`

// Which of some attempts were captured: their money booked.
func (q *Queries) CapturedAttempts(ctx context.Context, ids []string) ([]string, error) {
	rows, err := q.db.Query(ctx, capturedAttempts, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cardAttemptsBetween = `-- name: CardAttemptsBetween :one
SELECT count(*)::bigint FROM payments.attempts a JOIN payments.intents i ON i.id = a.intent_id
WHERE i.merchant_id = $1 AND i.livemode = $2 AND a.status = 'captured'
  AND a.payment_method NOT IN ('pix', 'boleto') AND a.created_at >= $3 AND a.created_at < $4
`

type CardAttemptsBetweenParams struct {
	MerchantID string
	Livemode   bool
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
}

// A merchant's card payments captured in a period, by when they were authorized.
func (q *Queries) CardAttemptsBetween(ctx context.Context, arg CardAttemptsBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, cardAttemptsBetween,
		arg.MerchantID,
		arg.Livemode,
		arg.FromTime,
		arg.ToTime,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const claimPaymentMethodsToTokenize = `-- name: ClaimPaymentMethodsToTokenize :many
UPDATE payments.payment_methods SET network_token_status = 'provisioning', network_token_since = $1
WHERE id IN (
    SELECT c.id FROM payments.payment_methods c
    WHERE c.livemode AND (c.network_token_status = '' OR (c.network_token_status = 'provisioning' AND c.network_token_since < $2))
    ORDER BY c.id
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
RETURNING id, merchant_id, livemode, vault_token
`

type ClaimPaymentMethodsToTokenizeParams struct {
	Now         pgtype.Timestamptz
	StaleBefore pgtype.Timestamptz
	MaxCount    int32
}

type ClaimPaymentMethodsToTokenizeRow struct {
	ID         string
	MerchantID string
	Livemode   bool
	VaultToken string
}

// Live cards without a network token yet, or whose provisioning stopped half-way.
func (q *Queries) ClaimPaymentMethodsToTokenize(ctx context.Context, arg ClaimPaymentMethodsToTokenizeParams) ([]ClaimPaymentMethodsToTokenizeRow, error) {
	rows, err := q.db.Query(ctx, claimPaymentMethodsToTokenize, arg.Now, arg.StaleBefore, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimPaymentMethodsToTokenizeRow{}
	for rows.Next() {
		var i ClaimPaymentMethodsToTokenizeRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Livemode,
			&i.VaultToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearRefund = `-- name: ClearRefund :execrows
UPDATE payments.refunds SET cleared_on = $1
WHERE id = $2 AND status = 'succeeded' AND amount = $3 AND cleared_on IS NULL
`

type ClearRefundParams struct {
	ClearedOn pgtype.Date
	ID        string
	Amount    int64
}

func (q *Queries) ClearRefund(ctx context.Context, arg ClearRefundParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearRefund, arg.ClearedOn, arg.ID, arg.Amount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disputedAmount = `-- name: DisputedAmount :one
SELECT coalesce(sum(amount), 0)::bigint FROM payments.dispute_funds
WHERE intent_id = $1 AND status IN ('held', 'withdrawn')
`

// What disputes hold or took of a payment: not refundable.
func (q *Queries) DisputedAmount(ctx context.Context, intentID string) (int64, error) {
	row := q.db.QueryRow(ctx, disputedAmount, intentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const feeLedgerAccounts = `-- name: FeeLedgerAccounts :many
SELECT livemode, currency, account_id FROM payments.ledger_accounts WHERE merchant_id = '' AND role = 'card_fees'
`

type FeeLedgerAccountsRow struct {
	Livemode  bool
	Currency  string
	AccountID string
}

func (q *Queries) FeeLedgerAccounts(ctx context.Context) ([]FeeLedgerAccountsRow, error) {
	rows, err := q.db.Query(ctx, feeLedgerAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeeLedgerAccountsRow{}
	for rows.Next() {
		var i FeeLedgerAccountsRow
		if err := rows.Scan(&i.Livemode, &i.Currency, &i.AccountID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const feeTotals = `-- name: FeeTotals :many
SELECT i.livemode, i.currency,
       (coalesce(sum(a.fee), 0) - coalesce((SELECT sum(r.fee_returned) FROM payments.refunds r
            JOIN payments.intents ri ON ri.id = r.intent_id
            WHERE r.status = 'succeeded' AND ri.livemode = i.livemode AND ri.currency = i.currency), 0))::bigint AS held
FROM payments.attempts a JOIN payments.intents i ON i.id = a.intent_id
GROUP BY i.livemode, i.currency
`

type FeeTotalsRow struct {
	Livemode bool
	Currency string
	Held     int64
}

// What each mode's fee account should hold: the fees charged less what refunds gave back.
func (q *Queries) FeeTotals(ctx context.Context) ([]FeeTotalsRow, error) {
	rows, err := q.db.Query(ctx, feeTotals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeeTotalsRow{}
	for rows.Next() {
		var i FeeTotalsRow
		if err := rows.Scan(&i.Livemode, &i.Currency, &i.Held); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const feesReturned = `-- name: FeesReturned :one
SELECT coalesce(sum(fee_returned), 0)::bigint FROM payments.refunds WHERE intent_id = $1 AND status = 'succeeded'
`

func (q *Queries) FeesReturned(ctx context.Context, intentID string) (int64, error) {
	row := q.db.QueryRow(ctx, feesReturned, intentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getAttempt = `-- name: GetAttempt :one
SELECT id, intent_id, number, payment_method, amount, status, authenticated, rail_reference, decline_code, ledger_hold, capture_amount, amount_captured, authorization_expires_at, unknown_since, resolutions, created_at, updated_at, initiator, stores_credential, installments, installments_financed_by, network_transaction_id, cleared_on, amount_cleared, ip, risk_decision, risk_decision_id, three_ds_server_trans_id, three_ds_version, three_ds_status, ds_trans_id, acs_trans_id, acs_url, eci, authentication_value, liability_shift, fee, split_out FROM payments.attempts WHERE id = $1
`

func (q *Queries) GetAttempt(ctx context.Context, id string) (PaymentsAttempt, error) {
	row := q.db.QueryRow(ctx, getAttempt, id)
	var i PaymentsAttempt
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.Number,
		&i.PaymentMethod,
		&i.Amount,
		&i.Status,
		&i.Authenticated,
		&i.RailReference,
		&i.DeclineCode,
		&i.LedgerHold,
		&i.CaptureAmount,
		&i.AmountCaptured,
		&i.AuthorizationExpiresAt,
		&i.UnknownSince,
		&i.Resolutions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Initiator,
		&i.StoresCredential,
		&i.Installments,
		&i.InstallmentsFinancedBy,
		&i.NetworkTransactionID,
		&i.ClearedOn,
		&i.AmountCleared,
		&i.Ip,
		&i.RiskDecision,
		&i.RiskDecisionID,
		&i.ThreeDsServerTransID,
		&i.ThreeDsVersion,
		&i.ThreeDsStatus,
		&i.DsTransID,
		&i.AcsTransID,
		&i.AcsUrl,
		&i.Eci,
		&i.AuthenticationValue,
		&i.LiabilityShift,
		&i.Fee,
		&i.SplitOut,
	)
	return i, err
}

const getCardLedgerAccounts = `-- name: GetCardLedgerAccounts :many
SELECT merchant_id, role, account_id FROM payments.ledger_accounts
WHERE merchant_id IN ($1::text, '') AND livemode = $2 AND currency = $3
`

type GetCardLedgerAccountsParams struct {
	MerchantID string
	Livemode   bool
	Currency   string
}

type GetCardLedgerAccountsRow struct {
	MerchantID string
	Role       string
	AccountID  string
}

// A merchant's accounts and the platform's, in one read.
func (q *Queries) GetCardLedgerAccounts(ctx context.Context, arg GetCardLedgerAccountsParams) ([]GetCardLedgerAccountsRow, error) {
	rows, err := q.db.Query(ctx, getCardLedgerAccounts, arg.MerchantID, arg.Livemode, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCardLedgerAccountsRow{}
	for rows.Next() {
		var i GetCardLedgerAccountsRow
		if err := rows.Scan(&i.MerchantID, &i.Role, &i.AccountID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIntent = `-- name: GetIntent :one
SELECT id, merchant_id, livemode, amount, currency, capture_method, status, payment_method, description, amount_capturable, amount_received, amount_refunded, latest_attempt, last_error_code, last_decline_code, last_error_message, next_action, cancellation_reason, created_at, updated_at, installments, installments_financed_by, setup_future_usage, request_three_d_secure, next_action_url, risk_decision, risk_decision_id, pix_options, next_action_data, next_action_expires_at, split, boleto_options FROM payments.intents WHERE id = $1 AND merchant_id = $2 AND livemode = $3
`

type GetIntentParams struct {
	ID         string
	MerchantID string
	Livemode   bool
}

func (q *Queries) GetIntent(ctx context.Context, arg GetIntentParams) (PaymentsIntent, error) {
	row := q.db.QueryRow(ctx, getIntent, arg.ID, arg.MerchantID, arg.Livemode)
	var i PaymentsIntent
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Amount,
		&i.Currency,
		&i.CaptureMethod,
		&i.Status,
		&i.PaymentMethod,
		&i.Description,
		&i.AmountCapturable,
		&i.AmountReceived,
		&i.AmountRefunded,
		&i.LatestAttempt,
		&i.LastErrorCode,
		&i.LastDeclineCode,
		&i.LastErrorMessage,
		&i.NextAction,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Installments,
		&i.InstallmentsFinancedBy,
		&i.SetupFutureUsage,
		&i.RequestThreeDSecure,
		&i.NextActionUrl,
		&i.RiskDecision,
		&i.RiskDecisionID,
		&i.PixOptions,
		&i.NextActionData,
		&i.NextActionExpiresAt,
		&i.Split,
		&i.BoletoOptions,
	)
	return i, err
}

const getIntentByID = `-- name: GetIntentByID :one
SELECT id, merchant_id, livemode, amount, currency, capture_method, status, payment_method, description, amount_capturable, amount_received, amount_refunded, latest_attempt, last_error_code, last_decline_code, last_error_message, next_action, cancellation_reason, created_at, updated_at, installments, installments_financed_by, setup_future_usage, request_three_d_secure, next_action_url, risk_decision, risk_decision_id, pix_options, next_action_data, next_action_expires_at, split, boleto_options FROM payments.intents WHERE id = $1
`

func (q *Queries) GetIntentByID(ctx context.Context, id string) (PaymentsIntent, error) {
	row := q.db.QueryRow(ctx, getIntentByID, id)
	var i PaymentsIntent
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Amount,
		&i.Currency,
		&i.CaptureMethod,
		&i.Status,
		&i.PaymentMethod,
		&i.Description,
		&i.AmountCapturable,
		&i.AmountReceived,
		&i.AmountRefunded,
		&i.LatestAttempt,
		&i.LastErrorCode,
		&i.LastDeclineCode,
		&i.LastErrorMessage,
		&i.NextAction,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Installments,
		&i.InstallmentsFinancedBy,
		&i.SetupFutureUsage,
		&i.RequestThreeDSecure,
		&i.NextActionUrl,
		&i.RiskDecision,
		&i.RiskDecisionID,
		&i.PixOptions,
		&i.NextActionData,
		&i.NextActionExpiresAt,
		&i.Split,
		&i.BoletoOptions,
	)
	return i, err
}

const getLedgerAccounts = `-- name: GetLedgerAccounts :many
SELECT role, account_id FROM payments.ledger_accounts
WHERE merchant_id = $1 AND livemode = $2 AND currency = $3
`

type GetLedgerAccountsParams struct {
	MerchantID string
	Livemode   bool
	Currency   string
}

type GetLedgerAccountsRow struct {
	Role      string
	AccountID string
}

func (q *Queries) GetLedgerAccounts(ctx context.Context, arg GetLedgerAccountsParams) ([]GetLedgerAccountsRow, error) {
	rows, err := q.db.Query(ctx, getLedgerAccounts, arg.MerchantID, arg.Livemode, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLedgerAccountsRow{}
	for rows.Next() {
		var i GetLedgerAccountsRow
		if err := rows.Scan(&i.Role, &i.AccountID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentMethod = `-- name: GetPaymentMethod :one
SELECT id, merchant_id, livemode, type, vault_token, brand, bin, last4, exp_month, exp_year, vault_fingerprint, created_at, network_transaction_id, network_token_reference, network_token_status, network_token_since, network_token_event_at FROM payments.payment_methods WHERE id = $1 AND merchant_id = $2 AND livemode = $3
`

type GetPaymentMethodParams struct {
	ID         string
	MerchantID string
	Livemode   bool
}

func (q *Queries) GetPaymentMethod(ctx context.Context, arg GetPaymentMethodParams) (PaymentsPaymentMethod, error) {
	row := q.db.QueryRow(ctx, getPaymentMethod, arg.ID, arg.MerchantID, arg.Livemode)
	var i PaymentsPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Type,
		&i.VaultToken,
		&i.Brand,
		&i.Bin,
		&i.Last4,
		&i.ExpMonth,
		&i.ExpYear,
		&i.VaultFingerprint,
		&i.CreatedAt,
		&i.NetworkTransactionID,
		&i.NetworkTokenReference,
		&i.NetworkTokenStatus,
		&i.NetworkTokenSince,
		&i.NetworkTokenEventAt,
	)
	return i, err
}

const getPaymentMethodByToken = `-- name: GetPaymentMethodByToken :one
SELECT id, merchant_id, livemode, type, vault_token, brand, bin, last4, exp_month, exp_year, vault_fingerprint, created_at, network_transaction_id, network_token_reference, network_token_status, network_token_since, network_token_event_at FROM payments.payment_methods WHERE vault_token = $1
`

func (q *Queries) GetPaymentMethodByToken(ctx context.Context, vaultToken string) (PaymentsPaymentMethod, error) {
	row := q.db.QueryRow(ctx, getPaymentMethodByToken, vaultToken)
	var i PaymentsPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Type,
		&i.VaultToken,
		&i.Brand,
		&i.Bin,
		&i.Last4,
		&i.ExpMonth,
		&i.ExpYear,
		&i.VaultFingerprint,
		&i.CreatedAt,
		&i.NetworkTransactionID,
		&i.NetworkTokenReference,
		&i.NetworkTokenStatus,
		&i.NetworkTokenSince,
		&i.NetworkTokenEventAt,
	)
	return i, err
}

const getPayout = `-- name: GetPayout :one
SELECT id, merchant_id, livemode, amount, currency, pix_key, description, status, failure_code, failure_message, e2e_id, recipient_name, ledger_hold, unknown_since, resolutions, arrived_at, created_at, updated_at, recipient_id, method, bank_ispb, bank_branch, bank_account, holder_name, holder_tax_id, returned_at, scheduled_on, source_account FROM payments.payouts WHERE id = $1 AND merchant_id = $2 AND livemode = $3
`

type GetPayoutParams struct {
	ID         string
	MerchantID string
	Livemode   bool
}

func (q *Queries) GetPayout(ctx context.Context, arg GetPayoutParams) (PaymentsPayout, error) {
	row := q.db.QueryRow(ctx, getPayout, arg.ID, arg.MerchantID, arg.Livemode)
	var i PaymentsPayout
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Amount,
		&i.Currency,
		&i.PixKey,
		&i.Description,
		&i.Status,
		&i.FailureCode,
		&i.FailureMessage,
		&i.E2eID,
		&i.RecipientName,
		&i.LedgerHold,
		&i.UnknownSince,
		&i.Resolutions,
		&i.ArrivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecipientID,
		&i.Method,
		&i.BankIspb,
		&i.BankBranch,
		&i.BankAccount,
		&i.HolderName,
		&i.HolderTaxID,
		&i.ReturnedAt,
		&i.ScheduledOn,
		&i.SourceAccount,
	)
	return i, err
}

const getPayoutByID = `-- name: GetPayoutByID :one
SELECT id, merchant_id, livemode, amount, currency, pix_key, description, status, failure_code, failure_message, e2e_id, recipient_name, ledger_hold, unknown_since, resolutions, arrived_at, created_at, updated_at, recipient_id, method, bank_ispb, bank_branch, bank_account, holder_name, holder_tax_id, returned_at, scheduled_on, source_account FROM payments.payouts WHERE id = $1
`

func (q *Queries) GetPayoutByID(ctx context.Context, id string) (PaymentsPayout, error) {
	row := q.db.QueryRow(ctx, getPayoutByID, id)
	var i PaymentsPayout
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Amount,
		&i.Currency,
		&i.PixKey,
		&i.Description,
		&i.Status,
		&i.FailureCode,
		&i.FailureMessage,
		&i.E2eID,
		&i.RecipientName,
		&i.LedgerHold,
		&i.UnknownSince,
		&i.Resolutions,
		&i.ArrivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecipientID,
		&i.Method,
		&i.BankIspb,
		&i.BankBranch,
		&i.BankAccount,
		&i.HolderName,
		&i.HolderTaxID,
		&i.ReturnedAt,
		&i.ScheduledOn,
		&i.SourceAccount,
	)
	return i, err
}

const getRailOperation = `-- name: GetRailOperation :one
SELECT key, kind, authorization_key, amount, status, reference, detail, calls, queries, created_at FROM payments.test_rail WHERE key = $1 FOR UPDATE
`

func (q *Queries) GetRailOperation(ctx context.Context, key string) (PaymentsTestRail, error) {
	row := q.db.QueryRow(ctx, getRailOperation, key)
	var i PaymentsTestRail
	err := row.Scan(
		&i.Key,
		&i.Kind,
		&i.AuthorizationKey,
		&i.Amount,
		&i.Status,
		&i.Reference,
		&i.Detail,
		&i.Calls,
		&i.Queries,
		&i.CreatedAt,
	)
	return i, err
}

const getRefund = `-- name: GetRefund :one
SELECT id, intent_id, attempt_id, merchant_id, livemode, amount, currency, reason, status, rail_reference, failure_reason, ledger_txn, unknown_since, resolutions, created_at, updated_at, cleared_on, fee_returned, split_back FROM payments.refunds WHERE id = $1 AND merchant_id = $2 AND livemode = $3
`

type GetRefundParams struct {
	ID         string
	MerchantID string
	Livemode   bool
}

func (q *Queries) GetRefund(ctx context.Context, arg GetRefundParams) (PaymentsRefund, error) {
	row := q.db.QueryRow(ctx, getRefund, arg.ID, arg.MerchantID, arg.Livemode)
	var i PaymentsRefund
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.AttemptID,
		&i.MerchantID,
		&i.Livemode,
		&i.Amount,
		&i.Currency,
		&i.Reason,
		&i.Status,
		&i.RailReference,
		&i.FailureReason,
		&i.LedgerTxn,
		&i.UnknownSince,
		&i.Resolutions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClearedOn,
		&i.FeeReturned,
		&i.SplitBack,
	)
	return i, err
}

const getRefundByID = `-- name: GetRefundByID :one
SELECT id, intent_id, attempt_id, merchant_id, livemode, amount, currency, reason, status, rail_reference, failure_reason, ledger_txn, unknown_since, resolutions, created_at, updated_at, cleared_on, fee_returned, split_back FROM payments.refunds WHERE id = $1
`

func (q *Queries) GetRefundByID(ctx context.Context, id string) (PaymentsRefund, error) {
	row := q.db.QueryRow(ctx, getRefundByID, id)
	var i PaymentsRefund
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.AttemptID,
		&i.MerchantID,
		&i.Livemode,
		&i.Amount,
		&i.Currency,
		&i.Reason,
		&i.Status,
		&i.RailReference,
		&i.FailureReason,
		&i.LedgerTxn,
		&i.UnknownSince,
		&i.Resolutions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClearedOn,
		&i.FeeReturned,
		&i.SplitBack,
	)
	return i, err
}

const health = `-- name: Health :one
SELECT
    (SELECT count(*) FROM payments.attempts
     WHERE status IN ('authenticating', 'authorizing', 'authorization_unknown', 'capturing', 'capture_unknown', 'voiding', 'void_unknown')
       AND updated_at < $1::timestamptz)::bigint AS attempts_unresolved,
    (SELECT count(*) FROM payments.refunds WHERE status IN ('pending', 'refund_unknown') AND updated_at < $1::timestamptz)::bigint AS refunds_unresolved,
    (SELECT count(*) FROM payments.payouts WHERE status IN ('sending', 'unknown') AND updated_at < $2::timestamptz)::bigint AS payouts_unresolved,
    (SELECT count(*) FROM payments.pix_received WHERE status IN ('unmatched', 'returning') AND updated_at < $2::timestamptz)::bigint AS pix_unreturned,
    (SELECT count(*) FROM payments.payouts WHERE status = 'held')::bigint AS payouts_held,
    (SELECT count(*) FROM (
        SELECT 1 FROM payments.payouts p
        WHERE p.created_at >= $3::timestamptz AND p.scheduled_on IS NULL AND p.status NOT IN ('failed', 'returned')
        GROUP BY p.merchant_id, p.livemode, p.recipient_id, p.currency
        HAVING sum(p.amount) >= $4::bigint
    ) near)::bigint AS balances_near_daily_limit
`

type HealthParams struct {
	AttemptsBefore pgtype.Timestamptz
	PayoutsBefore  pgtype.Timestamptz
	DayBegan       pgtype.Timestamptz
	NearDailyLimit int64
}

type HealthRow struct {
	AttemptsUnresolved     int64
	RefundsUnresolved      int64
	PayoutsUnresolved      int64
	PixUnreturned          int64
	PayoutsHeld            int64
	BalancesNearDailyLimit int64
}

// What has waited too long for the resolver: attempts, refunds and payouts whose outcome
// is not final, and Pix received that paid nothing and are not returned. Payouts held for
// an operator, and balances whose payouts today reached 80% of the daily limit.
func (q *Queries) Health(ctx context.Context, arg HealthParams) (HealthRow, error) {
	row := q.db.QueryRow(ctx, health,
		arg.AttemptsBefore,
		arg.PayoutsBefore,
		arg.DayBegan,
		arg.NearDailyLimit,
	)
	var i HealthRow
	err := row.Scan(
		&i.AttemptsUnresolved,
		&i.RefundsUnresolved,
		&i.PayoutsUnresolved,
		&i.PixUnreturned,
		&i.PayoutsHeld,
		&i.BalancesNearDailyLimit,
	)
	return i, err
}

const heldPayouts = `-- name: HeldPayouts :many
SELECT id, merchant_id, livemode, amount, currency, pix_key, description, status, failure_code, failure_message, e2e_id, recipient_name, ledger_hold, unknown_since, resolutions, arrived_at, created_at, updated_at, recipient_id, method, bank_ispb, bank_branch, bank_account, holder_name, holder_tax_id, returned_at, scheduled_on, source_account FROM payments.payouts
WHERE status = 'held' AND (recipient_id = $1
    OR ($2::boolean AND recipient_id = '' AND merchant_id = $3 AND livemode = $4))
ORDER BY id
FOR UPDATE
`

type HeldPayoutsParams struct {
	RecipientID string
	Own         bool
	MerchantID  string
	Livemode    bool
}

func (q *Queries) HeldPayouts(ctx context.Context, arg HeldPayoutsParams) ([]PaymentsPayout, error) {
	rows, err := q.db.Query(ctx, heldPayouts,
		arg.RecipientID,
		arg.Own,
		arg.MerchantID,
		arg.Livemode,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentsPayout{}
	for rows.Next() {
		var i PaymentsPayout
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Livemode,
			&i.Amount,
			&i.Currency,
			&i.PixKey,
			&i.Description,
			&i.Status,
			&i.FailureCode,
			&i.FailureMessage,
			&i.E2eID,
			&i.RecipientName,
			&i.LedgerHold,
			&i.UnknownSince,
			&i.Resolutions,
			&i.ArrivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecipientID,
			&i.Method,
			&i.BankIspb,
			&i.BankBranch,
			&i.BankAccount,
			&i.HolderName,
			&i.HolderTaxID,
			&i.ReturnedAt,
			&i.ScheduledOn,
			&i.SourceAccount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAttempt = `-- name: InsertAttempt :exec
INSERT INTO payments.attempts (id, intent_id, number, payment_method, amount, status, initiator, stores_credential,
                              installments, installments_financed_by, ip, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, $12, $12)
`

type InsertAttemptParams struct {
	ID                     string
	IntentID               string
	Number                 int32
	PaymentMethod          string
	Amount                 int64
	Status                 string
	Initiator              string
	StoresCredential       bool
	Installments           pgtype.Int4
	InstallmentsFinancedBy pgtype.Text
	Ip                     string
	CreatedAt              pgtype.Timestamptz
}

func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) error {
	_, err := q.db.Exec(ctx, insertAttempt,
		arg.ID,
		arg.IntentID,
		arg.Number,
		arg.PaymentMethod,
		arg.Amount,
		arg.Status,
		arg.Initiator,
		arg.StoresCredential,
		arg.Installments,
		arg.InstallmentsFinancedBy,
		arg.Ip,
		arg.CreatedAt,
	)
	return err
}

const insertDisputeFunds = `-- name: InsertDisputeFunds :execrows
INSERT INTO payments.dispute_funds (reference, intent_id, attempt_id, merchant_id, livemode, currency, amount, status, ledger_hold, ledger_txn, created_at, updated_at, withdrawn_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $11,
        CASE WHEN $8 = 'withdrawn' THEN $11::timestamptz END)
ON CONFLICT (reference) DO NOTHING
`

type InsertDisputeFundsParams struct {
	Reference  string
	IntentID   string
	AttemptID  string
	MerchantID string
	Livemode   bool
	Currency   string
	Amount     int64
	Status     string
	LedgerHold pgtype.Text
	LedgerTxn  pgtype.Text
	Now        pgtype.Timestamptz
}

func (q *Queries) InsertDisputeFunds(ctx context.Context, arg InsertDisputeFundsParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDisputeFunds,
		arg.Reference,
		arg.IntentID,
		arg.AttemptID,
		arg.MerchantID,
		arg.Livemode,
		arg.Currency,
		arg.Amount,
		arg.Status,
		arg.LedgerHold,
		arg.LedgerTxn,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertIntent = `-- name: InsertIntent :exec
INSERT INTO payments.intents (id, merchant_id, livemode, amount, currency, capture_method, status, payment_method,
                              description, installments, installments_financed_by, setup_future_usage,
                              request_three_d_secure, pix_options, split, boleto_options, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11, $12, $13,
        $14, $15, $16, $17, $17)
`

type InsertIntentParams struct {
	ID                     string
	MerchantID             string
	Livemode               bool
	Amount                 int64
	Currency               string
	CaptureMethod          string
	Status                 string
	PaymentMethod          string
	Description            string
	Installments           pgtype.Int4
	InstallmentsFinancedBy pgtype.Text
	SetupFutureUsage       string
	RequestThreeDSecure    string
	PixOptions             []byte
	Split                  []byte
	BoletoOptions          []byte
	CreatedAt              pgtype.Timestamptz
}

func (q *Queries) InsertIntent(ctx context.Context, arg InsertIntentParams) error {
	_, err := q.db.Exec(ctx, insertIntent,
		arg.ID,
		arg.MerchantID,
		arg.Livemode,
		arg.Amount,
		arg.Currency,
		arg.CaptureMethod,
		arg.Status,
		arg.PaymentMethod,
		arg.Description,
		arg.Installments,
		arg.InstallmentsFinancedBy,
		arg.SetupFutureUsage,
		arg.RequestThreeDSecure,
		arg.PixOptions,
		arg.Split,
		arg.BoletoOptions,
		arg.CreatedAt,
	)
	return err
}

const insertLedgerAccount = `-- name: InsertLedgerAccount :exec
INSERT INTO payments.ledger_accounts (merchant_id, livemode, currency, role, account_id) VALUES ($1, $2, $3, $4, $5)
`

type InsertLedgerAccountParams struct {
	MerchantID string
	Livemode   bool
	Currency   string
	Role       string
	AccountID  string
}

func (q *Queries) InsertLedgerAccount(ctx context.Context, arg InsertLedgerAccountParams) error {
	_, err := q.db.Exec(ctx, insertLedgerAccount,
		arg.MerchantID,
		arg.Livemode,
		arg.Currency,
		arg.Role,
		arg.AccountID,
	)
	return err
}

const insertPaymentMethod = `-- name: InsertPaymentMethod :one
INSERT INTO payments.payment_methods (id, merchant_id, livemode, type, vault_token, brand, bin, last4, exp_month,
                                      exp_year, vault_fingerprint, created_at)
VALUES ($1, $2, $3, 'card', $4, $5, $6, $7, $8, $9,
        $10, $11)
ON CONFLICT (vault_token) DO NOTHING
RETURNING id, merchant_id, livemode, type, vault_token, brand, bin, last4, exp_month, exp_year, vault_fingerprint, created_at, network_transaction_id, network_token_reference, network_token_status, network_token_since, network_token_event_at
`

type InsertPaymentMethodParams struct {
	ID               string
	MerchantID       string
	Livemode         bool
	VaultToken       string
	Brand            string
	Bin              string
	Last4            string
	ExpMonth         int32
	ExpYear          int32
	VaultFingerprint string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) InsertPaymentMethod(ctx context.Context, arg InsertPaymentMethodParams) (PaymentsPaymentMethod, error) {
	row := q.db.QueryRow(ctx, insertPaymentMethod,
		arg.ID,
		arg.MerchantID,
		arg.Livemode,
		arg.VaultToken,
		arg.Brand,
		arg.Bin,
		arg.Last4,
		arg.ExpMonth,
		arg.ExpYear,
		arg.VaultFingerprint,
		arg.CreatedAt,
	)
	var i PaymentsPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Type,
		&i.VaultToken,
		&i.Brand,
		&i.Bin,
		&i.Last4,
		&i.ExpMonth,
		&i.ExpYear,
		&i.VaultFingerprint,
		&i.CreatedAt,
		&i.NetworkTransactionID,
		&i.NetworkTokenReference,
		&i.NetworkTokenStatus,
		&i.NetworkTokenSince,
		&i.NetworkTokenEventAt,
	)
	return i, err
}

const insertPayout = `-- name: InsertPayout :exec
INSERT INTO payments.payouts (id, merchant_id, livemode, amount, currency, pix_key, description, status, ledger_hold,
                              recipient_id, method, bank_ispb, bank_branch, bank_account, holder_name, holder_tax_id,
                              scheduled_on, source_account, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11, $12, $13, $14, $15, $16,
        $17, $18, $19, $19)
`

type InsertPayoutParams struct {
	ID            string
	MerchantID    string
	Livemode      bool
	Amount        int64
	Currency      string
	PixKey        string
	Description   string
	Status        string
	LedgerHold    string
	RecipientID   string
	Method        string
	BankIspb      string
	BankBranch    string
	BankAccount   string
	HolderName    string
	HolderTaxID   string
	ScheduledOn   pgtype.Date
	SourceAccount string
	Now           pgtype.Timestamptz
}

func (q *Queries) InsertPayout(ctx context.Context, arg InsertPayoutParams) error {
	_, err := q.db.Exec(ctx, insertPayout,
		arg.ID,
		arg.MerchantID,
		arg.Livemode,
		arg.Amount,
		arg.Currency,
		arg.PixKey,
		arg.Description,
		arg.Status,
		arg.LedgerHold,
		arg.RecipientID,
		arg.Method,
		arg.BankIspb,
		arg.BankBranch,
		arg.BankAccount,
		arg.HolderName,
		arg.HolderTaxID,
		arg.ScheduledOn,
		arg.SourceAccount,
		arg.Now,
	)
	return err
}

const insertPixCharge = `-- name: InsertPixCharge :exec
INSERT INTO payments.pix_charges (txid, attempt_id, livemode, due, copy_paste, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (txid) DO NOTHING
`

type InsertPixChargeParams struct {
	Txid      string
	AttemptID string
	Livemode  bool
	Due       bool
	CopyPaste string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertPixCharge(ctx context.Context, arg InsertPixChargeParams) error {
	_, err := q.db.Exec(ctx, insertPixCharge,
		arg.Txid,
		arg.AttemptID,
		arg.Livemode,
		arg.Due,
		arg.CopyPaste,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const insertPixReceived = `-- name: InsertPixReceived :one
INSERT INTO payments.pix_received (livemode, e2e_id, txid, amount, currency, received_at, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, 'unmatched', $7, $7)
ON CONFLICT (livemode, e2e_id) DO NOTHING
RETURNING livemode, e2e_id, txid, amount, currency, received_at, attempt_id, status, ledger_txn, return_txn, reason, created_at, updated_at
`

type InsertPixReceivedParams struct {
	Livemode   bool
	E2eID      string
	Txid       string
	Amount     int64
	Currency   string
	ReceivedAt pgtype.Timestamptz
	Now        pgtype.Timestamptz
}

func (q *Queries) InsertPixReceived(ctx context.Context, arg InsertPixReceivedParams) (PaymentsPixReceived, error) {
	row := q.db.QueryRow(ctx, insertPixReceived,
		arg.Livemode,
		arg.E2eID,
		arg.Txid,
		arg.Amount,
		arg.Currency,
		arg.ReceivedAt,
		arg.Now,
	)
	var i PaymentsPixReceived
	err := row.Scan(
		&i.Livemode,
		&i.E2eID,
		&i.Txid,
		&i.Amount,
		&i.Currency,
		&i.ReceivedAt,
		&i.AttemptID,
		&i.Status,
		&i.LedgerTxn,
		&i.ReturnTxn,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRailOperation = `-- name: InsertRailOperation :exec
INSERT INTO payments.test_rail (key, kind, authorization_key, amount, status, reference, detail, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertRailOperationParams struct {
	Key              string
	Kind             string
	AuthorizationKey string
	Amount           int64
	Status           string
	Reference        string
	Detail           string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) InsertRailOperation(ctx context.Context, arg InsertRailOperationParams) error {
	_, err := q.db.Exec(ctx, insertRailOperation,
		arg.Key,
		arg.Kind,
		arg.AuthorizationKey,
		arg.Amount,
		arg.Status,
		arg.Reference,
		arg.Detail,
		arg.CreatedAt,
	)
	return err
}

const insertRefund = `-- name: InsertRefund :exec
INSERT INTO payments.refunds (id, intent_id, attempt_id, merchant_id, livemode, amount, currency, reason, status,
                              created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'pending', $9, $9)
`

type InsertRefundParams struct {
	ID         string
	IntentID   string
	AttemptID  string
	MerchantID string
	Livemode   bool
	Amount     int64
	Currency   string
	Reason     string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertRefund(ctx context.Context, arg InsertRefundParams) error {
	_, err := q.db.Exec(ctx, insertRefund,
		arg.ID,
		arg.IntentID,
		arg.AttemptID,
		arg.MerchantID,
		arg.Livemode,
		arg.Amount,
		arg.Currency,
		arg.Reason,
		arg.CreatedAt,
	)
	return err
}

const intentInconsistencies = `-- name: IntentInconsistencies :many
SELECT i.id, i.status, coalesce(a.status, '') AS attempt_status
FROM payments.intents i
LEFT JOIN payments.attempts a ON a.id = i.latest_attempt
WHERE NOT CASE i.status
    WHEN 'requires_capture' THEN coalesce(a.status = 'authorized' AND i.amount_capturable = a.amount, false)
    WHEN 'succeeded' THEN coalesce(a.status = 'captured' AND i.amount_received = a.amount_captured, false)
    WHEN 'processing' THEN coalesce(a.status IN ('authenticating', 'authorizing', 'authorization_unknown', 'scheduled', 'capturing', 'capture_unknown', 'voiding', 'void_unknown'), false)
    WHEN 'requires_action' THEN coalesce(a.status = 'requires_action', false)
    WHEN 'canceled' THEN a.status IS NULL OR a.status IN ('voided', 'declined', 'failed')
    ELSE a.status IS NULL OR a.status IN ('declined', 'failed')
  END
  OR i.amount_refunded <> (SELECT coalesce(sum(r.amount), 0) FROM payments.refunds r WHERE r.intent_id = i.id AND r.status = 'succeeded')
ORDER BY i.id
`

type IntentInconsistenciesRow struct {
	ID            string
	Status        string
	AttemptStatus string
}

// An intent's status must agree with its latest attempt and its amounts. Statuses that
// need an attempt fail the check when it is missing: coalesce turns NULL into false.
func (q *Queries) IntentInconsistencies(ctx context.Context) ([]IntentInconsistenciesRow, error) {
	rows, err := q.db.Query(ctx, intentInconsistencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntentInconsistenciesRow{}
	for rows.Next() {
		var i IntentInconsistenciesRow
		if err := rows.Scan(&i.ID, &i.Status, &i.AttemptStatus); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntents = `-- name: ListIntents :many
SELECT id, merchant_id, livemode, amount, currency, capture_method, status, payment_method, description, amount_capturable, amount_received, amount_refunded, latest_attempt, last_error_code, last_decline_code, last_error_message, next_action, cancellation_reason, created_at, updated_at, installments, installments_financed_by, setup_future_usage, request_three_d_secure, next_action_url, risk_decision, risk_decision_id, pix_options, next_action_data, next_action_expires_at, split, boleto_options FROM payments.intents
WHERE merchant_id = $1 AND livemode = $2
  AND ($3::text = '' OR id < $3)
  AND ($4::text = '' OR id > $4)
ORDER BY CASE WHEN $4 <> '' THEN id END ASC, id DESC
LIMIT $5::integer
`

type ListIntentsParams struct {
	MerchantID    string
	Livemode      bool
	StartingAfter string
	EndingBefore  string
	MaxCount      int32
}

func (q *Queries) ListIntents(ctx context.Context, arg ListIntentsParams) ([]PaymentsIntent, error) {
	rows, err := q.db.Query(ctx, listIntents,
		arg.MerchantID,
		arg.Livemode,
		arg.StartingAfter,
		arg.EndingBefore,
		arg.MaxCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentsIntent{}
	for rows.Next() {
		var i PaymentsIntent
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Livemode,
			&i.Amount,
			&i.Currency,
			&i.CaptureMethod,
			&i.Status,
			&i.PaymentMethod,
			&i.Description,
			&i.AmountCapturable,
			&i.AmountReceived,
			&i.AmountRefunded,
			&i.LatestAttempt,
			&i.LastErrorCode,
			&i.LastDeclineCode,
			&i.LastErrorMessage,
			&i.NextAction,
			&i.CancellationReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Installments,
			&i.InstallmentsFinancedBy,
			&i.SetupFutureUsage,
			&i.RequestThreeDSecure,
			&i.NextActionUrl,
			&i.RiskDecision,
			&i.RiskDecisionID,
			&i.PixOptions,
			&i.NextActionData,
			&i.NextActionExpiresAt,
			&i.Split,
			&i.BoletoOptions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayouts = `-- name: ListPayouts :many
SELECT id, merchant_id, livemode, amount, currency, pix_key, description, status, failure_code, failure_message, e2e_id, recipient_name, ledger_hold, unknown_since, resolutions, arrived_at, created_at, updated_at, recipient_id, method, bank_ispb, bank_branch, bank_account, holder_name, holder_tax_id, returned_at, scheduled_on, source_account FROM payments.payouts
WHERE merchant_id = $1 AND livemode = $2
  AND ($3::text = '' OR id < $3)
  AND ($4::text = '' OR id > $4)
ORDER BY CASE WHEN $4 <> '' THEN id END ASC, id DESC
LIMIT $5::integer
`

type ListPayoutsParams struct {
	MerchantID    string
	Livemode      bool
	StartingAfter string
	EndingBefore  string
	MaxCount      int32
}

func (q *Queries) ListPayouts(ctx context.Context, arg ListPayoutsParams) ([]PaymentsPayout, error) {
	rows, err := q.db.Query(ctx, listPayouts,
		arg.MerchantID,
		arg.Livemode,
		arg.StartingAfter,
		arg.EndingBefore,
		arg.MaxCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentsPayout{}
	for rows.Next() {
		var i PaymentsPayout
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Livemode,
			&i.Amount,
			&i.Currency,
			&i.PixKey,
			&i.Description,
			&i.Status,
			&i.FailureCode,
			&i.FailureMessage,
			&i.E2eID,
			&i.RecipientName,
			&i.LedgerHold,
			&i.UnknownSince,
			&i.Resolutions,
			&i.ArrivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecipientID,
			&i.Method,
			&i.BankIspb,
			&i.BankBranch,
			&i.BankAccount,
			&i.HolderName,
			&i.HolderTaxID,
			&i.ReturnedAt,
			&i.ScheduledOn,
			&i.SourceAccount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefunds = `-- name: ListRefunds :many
SELECT id, intent_id, attempt_id, merchant_id, livemode, amount, currency, reason, status, rail_reference, failure_reason, ledger_txn, unknown_since, resolutions, created_at, updated_at, cleared_on, fee_returned, split_back FROM payments.refunds
WHERE merchant_id = $1 AND livemode = $2
  AND ($3::text = '' OR intent_id = $3)
  AND ($4::text = '' OR id < $4)
  AND ($5::text = '' OR id > $5)
ORDER BY CASE WHEN $5 <> '' THEN id END ASC, id DESC
LIMIT $6::integer
`

type ListRefundsParams struct {
	MerchantID    string
	Livemode      bool
	IntentID      string
	StartingAfter string
	EndingBefore  string
	MaxCount      int32
}

func (q *Queries) ListRefunds(ctx context.Context, arg ListRefundsParams) ([]PaymentsRefund, error) {
	rows, err := q.db.Query(ctx, listRefunds,
		arg.MerchantID,
		arg.Livemode,
		arg.IntentID,
		arg.StartingAfter,
		arg.EndingBefore,
		arg.MaxCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentsRefund{}
	for rows.Next() {
		var i PaymentsRefund
		if err := rows.Scan(
			&i.ID,
			&i.IntentID,
			&i.AttemptID,
			&i.MerchantID,
			&i.Livemode,
			&i.Amount,
			&i.Currency,
			&i.Reason,
			&i.Status,
			&i.RailReference,
			&i.FailureReason,
			&i.LedgerTxn,
			&i.UnknownSince,
			&i.Resolutions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClearedOn,
			&i.FeeReturned,
			&i.SplitBack,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAttempt = `-- name: LockAttempt :one
SELECT id, intent_id, number, payment_method, amount, status, authenticated, rail_reference, decline_code, ledger_hold, capture_amount, amount_captured, authorization_expires_at, unknown_since, resolutions, created_at, updated_at, initiator, stores_credential, installments, installments_financed_by, network_transaction_id, cleared_on, amount_cleared, ip, risk_decision, risk_decision_id, three_ds_server_trans_id, three_ds_version, three_ds_status, ds_trans_id, acs_trans_id, acs_url, eci, authentication_value, liability_shift, fee, split_out FROM payments.attempts WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockAttempt(ctx context.Context, id string) (PaymentsAttempt, error) {
	row := q.db.QueryRow(ctx, lockAttempt, id)
	var i PaymentsAttempt
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.Number,
		&i.PaymentMethod,
		&i.Amount,
		&i.Status,
		&i.Authenticated,
		&i.RailReference,
		&i.DeclineCode,
		&i.LedgerHold,
		&i.CaptureAmount,
		&i.AmountCaptured,
		&i.AuthorizationExpiresAt,
		&i.UnknownSince,
		&i.Resolutions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Initiator,
		&i.StoresCredential,
		&i.Installments,
		&i.InstallmentsFinancedBy,
		&i.NetworkTransactionID,
		&i.ClearedOn,
		&i.AmountCleared,
		&i.Ip,
		&i.RiskDecision,
		&i.RiskDecisionID,
		&i.ThreeDsServerTransID,
		&i.ThreeDsVersion,
		&i.ThreeDsStatus,
		&i.DsTransID,
		&i.AcsTransID,
		&i.AcsUrl,
		&i.Eci,
		&i.AuthenticationValue,
		&i.LiabilityShift,
		&i.Fee,
		&i.SplitOut,
	)
	return i, err
}

const lockDisputeFunds = `-- name: LockDisputeFunds :one
SELECT reference, intent_id, attempt_id, merchant_id, livemode, currency, amount, split_back, status, ledger_hold, ledger_txn, created_at, updated_at, withdrawn_at FROM payments.dispute_funds WHERE reference = $1 FOR UPDATE
`

func (q *Queries) LockDisputeFunds(ctx context.Context, reference string) (PaymentsDisputeFund, error) {
	row := q.db.QueryRow(ctx, lockDisputeFunds, reference)
	var i PaymentsDisputeFund
	err := row.Scan(
		&i.Reference,
		&i.IntentID,
		&i.AttemptID,
		&i.MerchantID,
		&i.Livemode,
		&i.Currency,
		&i.Amount,
		&i.SplitBack,
		&i.Status,
		&i.LedgerHold,
		&i.LedgerTxn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WithdrawnAt,
	)
	return i, err
}

const lockIntent = `-- name: LockIntent :one
SELECT id, merchant_id, livemode, amount, currency, capture_method, status, payment_method, description, amount_capturable, amount_received, amount_refunded, latest_attempt, last_error_code, last_decline_code, last_error_message, next_action, cancellation_reason, created_at, updated_at, installments, installments_financed_by, setup_future_usage, request_three_d_secure, next_action_url, risk_decision, risk_decision_id, pix_options, next_action_data, next_action_expires_at, split, boleto_options FROM payments.intents WHERE id = $1 AND merchant_id = $2 AND livemode = $3 FOR UPDATE
`

type LockIntentParams struct {
	ID         string
	MerchantID string
	Livemode   bool
}

func (q *Queries) LockIntent(ctx context.Context, arg LockIntentParams) (PaymentsIntent, error) {
	row := q.db.QueryRow(ctx, lockIntent, arg.ID, arg.MerchantID, arg.Livemode)
	var i PaymentsIntent
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Amount,
		&i.Currency,
		&i.CaptureMethod,
		&i.Status,
		&i.PaymentMethod,
		&i.Description,
		&i.AmountCapturable,
		&i.AmountReceived,
		&i.AmountRefunded,
		&i.LatestAttempt,
		&i.LastErrorCode,
		&i.LastDeclineCode,
		&i.LastErrorMessage,
		&i.NextAction,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Installments,
		&i.InstallmentsFinancedBy,
		&i.SetupFutureUsage,
		&i.RequestThreeDSecure,
		&i.NextActionUrl,
		&i.RiskDecision,
		&i.RiskDecisionID,
		&i.PixOptions,
		&i.NextActionData,
		&i.NextActionExpiresAt,
		&i.Split,
		&i.BoletoOptions,
	)
	return i, err
}

const lockIntentByID = `-- name: LockIntentByID :one
SELECT id, merchant_id, livemode, amount, currency, capture_method, status, payment_method, description, amount_capturable, amount_received, amount_refunded, latest_attempt, last_error_code, last_decline_code, last_error_message, next_action, cancellation_reason, created_at, updated_at, installments, installments_financed_by, setup_future_usage, request_three_d_secure, next_action_url, risk_decision, risk_decision_id, pix_options, next_action_data, next_action_expires_at, split, boleto_options FROM payments.intents WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockIntentByID(ctx context.Context, id string) (PaymentsIntent, error) {
	row := q.db.QueryRow(ctx, lockIntentByID, id)
	var i PaymentsIntent
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Amount,
		&i.Currency,
		&i.CaptureMethod,
		&i.Status,
		&i.PaymentMethod,
		&i.Description,
		&i.AmountCapturable,
		&i.AmountReceived,
		&i.AmountRefunded,
		&i.LatestAttempt,
		&i.LastErrorCode,
		&i.LastDeclineCode,
		&i.LastErrorMessage,
		&i.NextAction,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Installments,
		&i.InstallmentsFinancedBy,
		&i.SetupFutureUsage,
		&i.RequestThreeDSecure,
		&i.NextActionUrl,
		&i.RiskDecision,
		&i.RiskDecisionID,
		&i.PixOptions,
		&i.NextActionData,
		&i.NextActionExpiresAt,
		&i.Split,
		&i.BoletoOptions,
	)
	return i, err
}

const lockLedgerAccountCreation = `-- name: LockLedgerAccountCreation :exec
SELECT pg_advisory_xact_lock(hashtext('payments.ledger_accounts/' || $1::text))
`

func (q *Queries) LockLedgerAccountCreation(ctx context.Context, scope string) error {
	_, err := q.db.Exec(ctx, lockLedgerAccountCreation, scope)
	return err
}

const lockPayoutByID = `-- name: LockPayoutByID :one
SELECT id, merchant_id, livemode, amount, currency, pix_key, description, status, failure_code, failure_message, e2e_id, recipient_name, ledger_hold, unknown_since, resolutions, arrived_at, created_at, updated_at, recipient_id, method, bank_ispb, bank_branch, bank_account, holder_name, holder_tax_id, returned_at, scheduled_on, source_account FROM payments.payouts WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockPayoutByID(ctx context.Context, id string) (PaymentsPayout, error) {
	row := q.db.QueryRow(ctx, lockPayoutByID, id)
	var i PaymentsPayout
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Amount,
		&i.Currency,
		&i.PixKey,
		&i.Description,
		&i.Status,
		&i.FailureCode,
		&i.FailureMessage,
		&i.E2eID,
		&i.RecipientName,
		&i.LedgerHold,
		&i.UnknownSince,
		&i.Resolutions,
		&i.ArrivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecipientID,
		&i.Method,
		&i.BankIspb,
		&i.BankBranch,
		&i.BankAccount,
		&i.HolderName,
		&i.HolderTaxID,
		&i.ReturnedAt,
		&i.ScheduledOn,
		&i.SourceAccount,
	)
	return i, err
}

const lockPayouts = `-- name: LockPayouts :exec
SELECT pg_advisory_xact_lock(hashtext('payments.payouts/' || $1::text))
`

// Serializes payouts from one balance, so two cannot both spend what is available once.
func (q *Queries) LockPayouts(ctx context.Context, scope string) error {
	_, err := q.db.Exec(ctx, lockPayouts, scope)
	return err
}

const lockPixReceived = `-- name: LockPixReceived :one
SELECT livemode, e2e_id, txid, amount, currency, received_at, attempt_id, status, ledger_txn, return_txn, reason, created_at, updated_at FROM payments.pix_received WHERE livemode = $1 AND e2e_id = $2 FOR UPDATE
`

type LockPixReceivedParams struct {
	Livemode bool
	E2eID    string
}

func (q *Queries) LockPixReceived(ctx context.Context, arg LockPixReceivedParams) (PaymentsPixReceived, error) {
	row := q.db.QueryRow(ctx, lockPixReceived, arg.Livemode, arg.E2eID)
	var i PaymentsPixReceived
	err := row.Scan(
		&i.Livemode,
		&i.E2eID,
		&i.Txid,
		&i.Amount,
		&i.Currency,
		&i.ReceivedAt,
		&i.AttemptID,
		&i.Status,
		&i.LedgerTxn,
		&i.ReturnTxn,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockRailKey = `-- name: LockRailKey :exec
SELECT pg_advisory_xact_lock(hashtext('payments.test_rail/' || $1::text))
`

func (q *Queries) LockRailKey(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, lockRailKey, key)
	return err
}

const lockRefundByID = `-- name: LockRefundByID :one
SELECT id, intent_id, attempt_id, merchant_id, livemode, amount, currency, reason, status, rail_reference, failure_reason, ledger_txn, unknown_since, resolutions, created_at, updated_at, cleared_on, fee_returned, split_back FROM payments.refunds WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockRefundByID(ctx context.Context, id string) (PaymentsRefund, error) {
	row := q.db.QueryRow(ctx, lockRefundByID, id)
	var i PaymentsRefund
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.AttemptID,
		&i.MerchantID,
		&i.Livemode,
		&i.Amount,
		&i.Currency,
		&i.Reason,
		&i.Status,
		&i.RailReference,
		&i.FailureReason,
		&i.LedgerTxn,
		&i.UnknownSince,
		&i.Resolutions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClearedOn,
		&i.FeeReturned,
		&i.SplitBack,
	)
	return i, err
}

const merchantLedgerAccounts = `-- name: MerchantLedgerAccounts :many
SELECT merchant_id, livemode, currency, account_id FROM payments.ledger_accounts
WHERE role = 'merchant_balance' ORDER BY merchant_id, livemode, currency
`

type MerchantLedgerAccountsRow struct {
	MerchantID string
	Livemode   bool
	Currency   string
	AccountID  string
}

func (q *Queries) MerchantLedgerAccounts(ctx context.Context) ([]MerchantLedgerAccountsRow, error) {
	rows, err := q.db.Query(ctx, merchantLedgerAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MerchantLedgerAccountsRow{}
	for rows.Next() {
		var i MerchantLedgerAccountsRow
		if err := rows.Scan(
			&i.MerchantID,
			&i.Livemode,
			&i.Currency,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const merchantTotals = `-- name: MerchantTotals :many
WITH received AS (
    SELECT i.merchant_id, i.livemode, i.currency,
           sum(i.amount_received - i.amount_refunded
               - coalesce((SELECT sum(a.fee + a.split_out) FROM payments.attempts a WHERE a.intent_id = i.id), 0)
               + coalesce((SELECT sum(r.fee_returned + r.split_back) FROM payments.refunds r WHERE r.intent_id = i.id AND r.status = 'succeeded'), 0)) AS posted
    FROM payments.intents i GROUP BY i.merchant_id, i.livemode, i.currency
), held AS (
    SELECT i.merchant_id, i.livemode, i.currency, sum(a.amount) AS held
    FROM payments.attempts a JOIN payments.intents i ON i.id = a.intent_id
    WHERE a.ledger_hold IS NOT NULL AND a.status IN ('authorized', 'capturing', 'capture_unknown', 'voiding', 'void_unknown')
    GROUP BY i.merchant_id, i.livemode, i.currency
), paid_out AS (
    SELECT merchant_id, livemode, currency,
           coalesce(sum(amount) FILTER (WHERE status = 'paid'), 0) AS paid,
           coalesce(sum(amount) FILTER (WHERE status IN ('held', 'sending', 'unknown')), 0) AS in_flight
    FROM payments.payouts WHERE recipient_id = '' GROUP BY merchant_id, livemode, currency
), disputed AS (
    SELECT merchant_id, livemode, currency,
           coalesce(sum(amount - split_back) FILTER (WHERE status = 'withdrawn'), 0) AS withdrawn,
           coalesce(sum(amount) FILTER (WHERE status = 'held'), 0) AS held
    FROM payments.dispute_funds GROUP BY merchant_id, livemode, currency
)
SELECT r.merchant_id, r.livemode, r.currency,
       (r.posted - coalesce(p.paid, 0) - coalesce(d.withdrawn, 0))::bigint AS posted,
       coalesce(h.held, 0)::bigint AS held,
       (coalesce(p.in_flight, 0) + coalesce(d.held, 0))::bigint AS paying_out,
       coalesce(d.withdrawn, 0)::bigint AS disputed
FROM received r
LEFT JOIN held h ON h.merchant_id = r.merchant_id AND h.livemode = r.livemode AND h.currency = r.currency
LEFT JOIN paid_out p ON p.merchant_id = r.merchant_id AND p.livemode = r.livemode AND p.currency = r.currency
LEFT JOIN disputed d ON d.merchant_id = r.merchant_id AND d.livemode = r.livemode AND d.currency = r.currency
`

type MerchantTotalsRow struct {
	MerchantID string
	Livemode   bool
	Currency   string
	Posted     int64
	Held       int64
	PayingOut  int64
	Disputed   int64
}

// What each merchant's balance should hold: posted, what payments received less what
// was refunded, Jupiter's fees net of what refunds gave back, what was paid out, and what
// disputes took net of what recipients gave back for them; held for the merchant, what
// open card authorizations hold; held against the merchant, what payouts in flight and
// MED claims under analysis hold. Disputed is what disputes took, the most a chargeback
// can leave the balance below zero.
func (q *Queries) MerchantTotals(ctx context.Context) ([]MerchantTotalsRow, error) {
	rows, err := q.db.Query(ctx, merchantTotals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MerchantTotalsRow{}
	for rows.Next() {
		var i MerchantTotalsRow
		if err := rows.Scan(
			&i.MerchantID,
			&i.Livemode,
			&i.Currency,
			&i.Posted,
			&i.Held,
			&i.PayingOut,
			&i.Disputed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const merchantsOfObjects = `-- name: MerchantsOfObjects :many
SELECT a.id::text AS object, i.merchant_id::text AS merchant_id FROM payments.attempts a JOIN payments.intents i ON i.id = a.intent_id
WHERE a.id = ANY($1::text[])
UNION ALL
SELECT r.id::text, r.merchant_id::text FROM payments.refunds r WHERE r.id = ANY($1::text[])
`

type MerchantsOfObjectsRow struct {
	Object     string
	MerchantID string
}

// The merchants attempts and refunds belong to.
func (q *Queries) MerchantsOfObjects(ctx context.Context, ids []string) ([]MerchantsOfObjectsRow, error) {
	rows, err := q.db.Query(ctx, merchantsOfObjects, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MerchantsOfObjectsRow{}
	for rows.Next() {
		var i MerchantsOfObjectsRow
		if err := rows.Scan(&i.Object, &i.MerchantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextAttemptNumber = `-- name: NextAttemptNumber :one
SELECT (coalesce(max(number), 0) + 1)::integer FROM payments.attempts WHERE intent_id = $1
`

func (q *Queries) NextAttemptNumber(ctx context.Context, intentID string) (int32, error) {
	row := q.db.QueryRow(ctx, nextAttemptNumber, intentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const outstandingRefunds = `-- name: OutstandingRefunds :one
SELECT coalesce(sum(amount), 0)::bigint FROM payments.refunds
WHERE intent_id = $1 AND status IN ('pending', 'refund_unknown')
`

func (q *Queries) OutstandingRefunds(ctx context.Context, intentID string) (int64, error) {
	row := q.db.QueryRow(ctx, outstandingRefunds, intentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const paidOutSince = `-- name: PaidOutSince :many
SELECT id, amount, e2e_id, method, created_at FROM payments.payouts
WHERE merchant_id = $1 AND livemode = $2 AND currency = $3 AND recipient_id = ''
  AND status = 'paid' AND created_at >= $4
ORDER BY created_at, id
LIMIT 100
`

type PaidOutSinceParams struct {
	MerchantID string
	Livemode   bool
	Currency   string
	Since      pgtype.Timestamptz
}

type PaidOutSinceRow struct {
	ID        string
	Amount    int64
	E2eID     string
	Method    string
	CreatedAt pgtype.Timestamptz
}

// The merchant's own payouts paid since a moment, oldest first: where its balance went.
func (q *Queries) PaidOutSince(ctx context.Context, arg PaidOutSinceParams) ([]PaidOutSinceRow, error) {
	rows, err := q.db.Query(ctx, paidOutSince,
		arg.MerchantID,
		arg.Livemode,
		arg.Currency,
		arg.Since,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaidOutSinceRow{}
	for rows.Next() {
		var i PaidOutSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.E2eID,
			&i.Method,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const payoutsOfTheDay = `-- name: PayoutsOfTheDay :one
SELECT coalesce(sum(amount), 0)::bigint FROM payments.payouts
WHERE merchant_id = $1 AND livemode = $2 AND recipient_id = $3 AND currency = $4
  AND created_at >= $5 AND scheduled_on IS NULL AND status NOT IN ('failed', 'returned')
`

type PayoutsOfTheDayParams struct {
	MerchantID  string
	Livemode    bool
	RecipientID string
	Currency    string
	Since       pgtype.Timestamptz
}

// What a balance's payouts asked for since the day began took, but those that failed or
// came back; scheduled payouts are not counted.
func (q *Queries) PayoutsOfTheDay(ctx context.Context, arg PayoutsOfTheDayParams) (int64, error) {
	row := q.db.QueryRow(ctx, payoutsOfTheDay,
		arg.MerchantID,
		arg.Livemode,
		arg.RecipientID,
		arg.Currency,
		arg.Since,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const payoutsSince = `-- name: PayoutsSince :many
SELECT id, merchant_id, amount, status, arrived_at, returned_at FROM payments.payouts
WHERE livemode = $1 AND method = $2 AND status IN ('paid', 'returned') AND (arrived_at >= $3 OR returned_at >= $3)
ORDER BY arrived_at, id
`

type PayoutsSinceParams struct {
	Livemode bool
	Method   string
	Since    pgtype.Timestamptz
}

type PayoutsSinceRow struct {
	ID         string
	MerchantID string
	Amount     int64
	Status     string
	ArrivedAt  pgtype.Timestamptz
	ReturnedAt pgtype.Timestamptz
}

// Payouts paid, or paid and returned, by a method, since a moment.
func (q *Queries) PayoutsSince(ctx context.Context, arg PayoutsSinceParams) ([]PayoutsSinceRow, error) {
	rows, err := q.db.Query(ctx, payoutsSince, arg.Livemode, arg.Method, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PayoutsSinceRow{}
	for rows.Next() {
		var i PayoutsSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Amount,
			&i.Status,
			&i.ArrivedAt,
			&i.ReturnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const payoutsToResolve = `-- name: PayoutsToResolve :many
SELECT id FROM payments.payouts
WHERE (status IN ('sending', 'unknown') AND updated_at <= $1::timestamptz)
   OR (status = 'paid' AND method = 'bank_transfer' AND arrived_at >= $2::timestamptz AND updated_at <= $1::timestamptz)
ORDER BY updated_at, id
LIMIT $3::integer
`

type PayoutsToResolveParams struct {
	Before     pgtype.Timestamptz
	WatchSince pgtype.Timestamptz
	MaxCount   int32
}

// Payouts whose transfer has no answer yet, and bank transfers paid in the last week,
// which the receiving bank may still send back.
func (q *Queries) PayoutsToResolve(ctx context.Context, arg PayoutsToResolveParams) ([]string, error) {
	rows, err := q.db.Query(ctx, payoutsToResolve, arg.Before, arg.WatchSince, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pixAttemptsDue = `-- name: PixAttemptsDue :many
SELECT a.id FROM payments.attempts a JOIN payments.pix_charges c ON c.attempt_id = a.id
WHERE a.status = 'requires_action' AND c.expires_at <= $1::timestamptz
ORDER BY c.expires_at, a.id
LIMIT $2::integer
`

type PixAttemptsDueParams struct {
	Before   pgtype.Timestamptz
	MaxCount int32
}

// Attempts waiting for a Pix whose charge expired more than a grace period ago.
func (q *Queries) PixAttemptsDue(ctx context.Context, arg PixAttemptsDueParams) ([]string, error) {
	rows, err := q.db.Query(ctx, pixAttemptsDue, arg.Before, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pixChargeByAttempt = `-- name: PixChargeByAttempt :one
SELECT txid, attempt_id, livemode, due, copy_paste, expires_at, created_at FROM payments.pix_charges WHERE attempt_id = $1
`

func (q *Queries) PixChargeByAttempt(ctx context.Context, attemptID string) (PaymentsPixCharge, error) {
	row := q.db.QueryRow(ctx, pixChargeByAttempt, attemptID)
	var i PaymentsPixCharge
	err := row.Scan(
		&i.Txid,
		&i.AttemptID,
		&i.Livemode,
		&i.Due,
		&i.CopyPaste,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const pixChargeByTxid = `-- name: PixChargeByTxid :one
SELECT txid, attempt_id, livemode, due, copy_paste, expires_at, created_at FROM payments.pix_charges WHERE txid = $1 AND livemode = $2
`

type PixChargeByTxidParams struct {
	Txid     string
	Livemode bool
}

func (q *Queries) PixChargeByTxid(ctx context.Context, arg PixChargeByTxidParams) (PaymentsPixCharge, error) {
	row := q.db.QueryRow(ctx, pixChargeByTxid, arg.Txid, arg.Livemode)
	var i PaymentsPixCharge
	err := row.Scan(
		&i.Txid,
		&i.AttemptID,
		&i.Livemode,
		&i.Due,
		&i.CopyPaste,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const pixDisputeFundsSince = `-- name: PixDisputeFundsSince :many
SELECT f.reference, f.merchant_id, f.amount, f.status, f.withdrawn_at, f.updated_at FROM payments.dispute_funds f
JOIN payments.attempts a ON a.id = f.attempt_id
WHERE f.livemode = $1 AND a.payment_method = 'pix' AND f.status IN ('withdrawn', 'reinstated') AND f.withdrawn_at >= $2
ORDER BY f.withdrawn_at, f.reference
`

type PixDisputeFundsSinceParams struct {
	Livemode bool
	Since    pgtype.Timestamptz
}

type PixDisputeFundsSinceRow struct {
	Reference   string
	MerchantID  string
	Amount      int64
	Status      string
	WithdrawnAt pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

// What MED claims took from Pix payments, and gave back.
func (q *Queries) PixDisputeFundsSince(ctx context.Context, arg PixDisputeFundsSinceParams) ([]PixDisputeFundsSinceRow, error) {
	rows, err := q.db.Query(ctx, pixDisputeFundsSince, arg.Livemode, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PixDisputeFundsSinceRow{}
	for rows.Next() {
		var i PixDisputeFundsSinceRow
		if err := rows.Scan(
			&i.Reference,
			&i.MerchantID,
			&i.Amount,
			&i.Status,
			&i.WithdrawnAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pixLedgerAccounts = `-- name: PixLedgerAccounts :many
SELECT livemode, currency, account_id FROM payments.ledger_accounts WHERE role = 'pix_unmatched'
`

type PixLedgerAccountsRow struct {
	Livemode  bool
	Currency  string
	AccountID string
}

func (q *Queries) PixLedgerAccounts(ctx context.Context) ([]PixLedgerAccountsRow, error) {
	rows, err := q.db.Query(ctx, pixLedgerAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PixLedgerAccountsRow{}
	for rows.Next() {
		var i PixLedgerAccountsRow
		if err := rows.Scan(&i.Livemode, &i.Currency, &i.AccountID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pixReceivedOf = `-- name: PixReceivedOf :one
SELECT livemode, e2e_id, txid, amount, currency, received_at, attempt_id, status, ledger_txn, return_txn, reason, created_at, updated_at FROM payments.pix_received WHERE livemode = $1 AND e2e_id = $2
`

type PixReceivedOfParams struct {
	Livemode bool
	E2eID    string
}

func (q *Queries) PixReceivedOf(ctx context.Context, arg PixReceivedOfParams) (PaymentsPixReceived, error) {
	row := q.db.QueryRow(ctx, pixReceivedOf, arg.Livemode, arg.E2eID)
	var i PaymentsPixReceived
	err := row.Scan(
		&i.Livemode,
		&i.E2eID,
		&i.Txid,
		&i.Amount,
		&i.Currency,
		&i.ReceivedAt,
		&i.AttemptID,
		&i.Status,
		&i.LedgerTxn,
		&i.ReturnTxn,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pixReceivedSince = `-- name: PixReceivedSince :many
SELECT r.e2e_id, r.amount, r.received_at, r.status, r.updated_at, coalesce(i.merchant_id, '')::text AS merchant_id
FROM payments.pix_received r
LEFT JOIN payments.attempts a ON a.id = r.attempt_id
LEFT JOIN payments.intents i ON i.id = a.intent_id
WHERE r.livemode = $1 AND (r.received_at >= $2 OR r.updated_at >= $2)
ORDER BY r.received_at, r.e2e_id
`

type PixReceivedSinceParams struct {
	Livemode bool
	Since    pgtype.Timestamptz
}

type PixReceivedSinceRow struct {
	E2eID      string
	Amount     int64
	ReceivedAt pgtype.Timestamptz
	Status     string
	UpdatedAt  pgtype.Timestamptz
	MerchantID string
}

func (q *Queries) PixReceivedSince(ctx context.Context, arg PixReceivedSinceParams) ([]PixReceivedSinceRow, error) {
	rows, err := q.db.Query(ctx, pixReceivedSince, arg.Livemode, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PixReceivedSinceRow{}
	for rows.Next() {
		var i PixReceivedSinceRow
		if err := rows.Scan(
			&i.E2eID,
			&i.Amount,
			&i.ReceivedAt,
			&i.Status,
			&i.UpdatedAt,
			&i.MerchantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pixReceivedToReturn = `-- name: PixReceivedToReturn :many
SELECT livemode, e2e_id FROM payments.pix_received
WHERE status IN ('unmatched', 'returning') AND updated_at <= $1::timestamptz
ORDER BY updated_at, e2e_id
LIMIT $2::integer
`

type PixReceivedToReturnParams struct {
	Before   pgtype.Timestamptz
	MaxCount int32
}

type PixReceivedToReturnRow struct {
	Livemode bool
	E2eID    string
}

func (q *Queries) PixReceivedToReturn(ctx context.Context, arg PixReceivedToReturnParams) ([]PixReceivedToReturnRow, error) {
	rows, err := q.db.Query(ctx, pixReceivedToReturn, arg.Before, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PixReceivedToReturnRow{}
	for rows.Next() {
		var i PixReceivedToReturnRow
		if err := rows.Scan(&i.Livemode, &i.E2eID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pixRefundsSince = `-- name: PixRefundsSince :many
SELECT r.id, r.merchant_id, r.amount, r.updated_at FROM payments.refunds r JOIN payments.attempts a ON a.id = r.attempt_id
WHERE r.livemode = $1 AND r.status = 'succeeded' AND a.payment_method = 'pix' AND r.updated_at >= $2
ORDER BY r.updated_at, r.id
`

type PixRefundsSinceParams struct {
	Livemode bool
	Since    pgtype.Timestamptz
}

type PixRefundsSinceRow struct {
	ID         string
	MerchantID string
	Amount     int64
	UpdatedAt  pgtype.Timestamptz
}

// Refunds of Pix payments the bank returned.
func (q *Queries) PixRefundsSince(ctx context.Context, arg PixRefundsSinceParams) ([]PixRefundsSinceRow, error) {
	rows, err := q.db.Query(ctx, pixRefundsSince, arg.Livemode, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PixRefundsSinceRow{}
	for rows.Next() {
		var i PixRefundsSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Amount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const railApprovedTotal = `-- name: RailApprovedTotal :one
SELECT coalesce(sum(amount), 0)::bigint FROM payments.test_rail
WHERE authorization_key = $1 AND kind = $2 AND status = 'approved'
`

type RailApprovedTotalParams struct {
	AuthorizationKey string
	Kind             string
}

func (q *Queries) RailApprovedTotal(ctx context.Context, arg RailApprovedTotalParams) (int64, error) {
	row := q.db.QueryRow(ctx, railApprovedTotal, arg.AuthorizationKey, arg.Kind)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const refundsInFlight = `-- name: RefundsInFlight :one
SELECT coalesce(sum(amount), 0)::bigint FROM payments.refunds
WHERE merchant_id = $1 AND livemode = $2 AND currency = $3 AND status IN ('pending', 'refund_unknown')
`

type RefundsInFlightParams struct {
	MerchantID string
	Livemode   bool
	Currency   string
}

// What refunds not yet confirmed will take from a merchant's balance.
func (q *Queries) RefundsInFlight(ctx context.Context, arg RefundsInFlightParams) (int64, error) {
	row := q.db.QueryRow(ctx, refundsInFlight, arg.MerchantID, arg.Livemode, arg.Currency)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const refundsToResolve = `-- name: RefundsToResolve :many
SELECT id FROM payments.refunds
WHERE status IN ('pending', 'refund_unknown') AND updated_at <= $1::timestamptz
ORDER BY updated_at, id
LIMIT $2::integer
`

type RefundsToResolveParams struct {
	Before   pgtype.Timestamptz
	MaxCount int32
}

func (q *Queries) RefundsToResolve(ctx context.Context, arg RefundsToResolveParams) ([]string, error) {
	rows, err := q.db.Query(ctx, refundsToResolve, arg.Before, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveAttempt = `-- name: SaveAttempt :exec
UPDATE payments.attempts
SET status = $1, authenticated = $2, rail_reference = $3,
    decline_code = $4, ledger_hold = $5, capture_amount = $6,
    amount_captured = $7, authorization_expires_at = $8,
    unknown_since = $9, resolutions = $10, network_transaction_id = $11,
    cleared_on = $12, amount_cleared = $13, risk_decision = $14,
    risk_decision_id = $15, three_ds_server_trans_id = $16,
    three_ds_version = $17, three_ds_status = $18, ds_trans_id = $19,
    acs_trans_id = $20, acs_url = $21, eci = $22, authentication_value = $23,
    liability_shift = $24, updated_at = $25
WHERE id = $26
`

type SaveAttemptParams struct {
	Status                 string
	Authenticated          bool
	RailReference          string
	DeclineCode            string
	LedgerHold             pgtype.Text
	CaptureAmount          pgtype.Int8
	AmountCaptured         int64
	AuthorizationExpiresAt pgtype.Timestamptz
	UnknownSince           pgtype.Timestamptz
	Resolutions            int32
	NetworkTransactionID   string
	ClearedOn              pgtype.Date
	AmountCleared          pgtype.Int8
	RiskDecision           string
	RiskDecisionID         string
	ThreeDsServerTransID   string
	ThreeDsVersion         string
	ThreeDsStatus          string
	DsTransID              string
	AcsTransID             string
	AcsUrl                 string
	Eci                    string
	AuthenticationValue    string
	LiabilityShift         bool
	UpdatedAt              pgtype.Timestamptz
	ID                     string
}

func (q *Queries) SaveAttempt(ctx context.Context, arg SaveAttemptParams) error {
	_, err := q.db.Exec(ctx, saveAttempt,
		arg.Status,
		arg.Authenticated,
		arg.RailReference,
		arg.DeclineCode,
		arg.LedgerHold,
		arg.CaptureAmount,
		arg.AmountCaptured,
		arg.AuthorizationExpiresAt,
		arg.UnknownSince,
		arg.Resolutions,
		arg.NetworkTransactionID,
		arg.ClearedOn,
		arg.AmountCleared,
		arg.RiskDecision,
		arg.RiskDecisionID,
		arg.ThreeDsServerTransID,
		arg.ThreeDsVersion,
		arg.ThreeDsStatus,
		arg.DsTransID,
		arg.AcsTransID,
		arg.AcsUrl,
		arg.Eci,
		arg.AuthenticationValue,
		arg.LiabilityShift,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const saveDisputeFunds = `-- name: SaveDisputeFunds :exec
UPDATE payments.dispute_funds
SET status = $1, split_back = $2, ledger_txn = $3, updated_at = $4,
    withdrawn_at = CASE WHEN $1 = 'withdrawn' AND withdrawn_at IS NULL THEN $4 ELSE withdrawn_at END
WHERE reference = $5
`

type SaveDisputeFundsParams struct {
	Status    string
	SplitBack int64
	LedgerTxn pgtype.Text
	Now       pgtype.Timestamptz
	Reference string
}

func (q *Queries) SaveDisputeFunds(ctx context.Context, arg SaveDisputeFundsParams) error {
	_, err := q.db.Exec(ctx, saveDisputeFunds,
		arg.Status,
		arg.SplitBack,
		arg.LedgerTxn,
		arg.Now,
		arg.Reference,
	)
	return err
}

const saveIntent = `-- name: SaveIntent :exec
UPDATE payments.intents
SET amount = $1, status = $2, payment_method = $3, description = $4,
    amount_capturable = $5, amount_received = $6, amount_refunded = $7,
    latest_attempt = $8, last_error_code = $9, last_decline_code = $10,
    last_error_message = $11, next_action = $12,
    cancellation_reason = $13, installments = $14,
    installments_financed_by = $15, setup_future_usage = $16,
    request_three_d_secure = $17, next_action_url = $18,
    risk_decision = $19, risk_decision_id = $20, pix_options = $21, split = $22, boleto_options = $23,
    next_action_data = $24, next_action_expires_at = $25, updated_at = $26
WHERE id = $27
`

type SaveIntentParams struct {
	Amount                 int64
	Status                 string
	PaymentMethod          string
	Description            string
	AmountCapturable       int64
	AmountReceived         int64
	AmountRefunded         int64
	LatestAttempt          pgtype.Text
	LastErrorCode          string
	LastDeclineCode        string
	LastErrorMessage       string
	NextAction             string
	CancellationReason     string
	Installments           pgtype.Int4
	InstallmentsFinancedBy pgtype.Text
	SetupFutureUsage       string
	RequestThreeDSecure    string
	NextActionUrl          string
	RiskDecision           string
	RiskDecisionID         string
	PixOptions             []byte
	Split                  []byte
	BoletoOptions          []byte
	NextActionData         string
	NextActionExpiresAt    pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	ID                     string
}

func (q *Queries) SaveIntent(ctx context.Context, arg SaveIntentParams) error {
	_, err := q.db.Exec(ctx, saveIntent,
		arg.Amount,
		arg.Status,
		arg.PaymentMethod,
		arg.Description,
		arg.AmountCapturable,
		arg.AmountReceived,
		arg.AmountRefunded,
		arg.LatestAttempt,
		arg.LastErrorCode,
		arg.LastDeclineCode,
		arg.LastErrorMessage,
		arg.NextAction,
		arg.CancellationReason,
		arg.Installments,
		arg.InstallmentsFinancedBy,
		arg.SetupFutureUsage,
		arg.RequestThreeDSecure,
		arg.NextActionUrl,
		arg.RiskDecision,
		arg.RiskDecisionID,
		arg.PixOptions,
		arg.Split,
		arg.BoletoOptions,
		arg.NextActionData,
		arg.NextActionExpiresAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const savePayout = `-- name: SavePayout :exec
UPDATE payments.payouts
SET status = $1, failure_code = $2, failure_message = $3, e2e_id = $4,
    recipient_name = $5, unknown_since = $6, resolutions = $7,
    arrived_at = $8, returned_at = $9, updated_at = $10
WHERE id = $11
`

type SavePayoutParams struct {
	Status         string
	FailureCode    string
	FailureMessage string
	E2eID          string
	RecipientName  string
	UnknownSince   pgtype.Timestamptz
	Resolutions    int32
	ArrivedAt      pgtype.Timestamptz
	ReturnedAt     pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ID             string
}

func (q *Queries) SavePayout(ctx context.Context, arg SavePayoutParams) error {
	_, err := q.db.Exec(ctx, savePayout,
		arg.Status,
		arg.FailureCode,
		arg.FailureMessage,
		arg.E2eID,
		arg.RecipientName,
		arg.UnknownSince,
		arg.Resolutions,
		arg.ArrivedAt,
		arg.ReturnedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const savePixReceived = `-- name: SavePixReceived :exec
UPDATE payments.pix_received
SET status = $1, attempt_id = $2, ledger_txn = $3,
    return_txn = $4, reason = $5, updated_at = $6
WHERE livemode = $7 AND e2e_id = $8
`

type SavePixReceivedParams struct {
	Status    string
	AttemptID pgtype.Text
	LedgerTxn pgtype.Text
	ReturnTxn pgtype.Text
	Reason    string
	UpdatedAt pgtype.Timestamptz
	Livemode  bool
	E2eID     string
}

func (q *Queries) SavePixReceived(ctx context.Context, arg SavePixReceivedParams) error {
	_, err := q.db.Exec(ctx, savePixReceived,
		arg.Status,
		arg.AttemptID,
		arg.LedgerTxn,
		arg.ReturnTxn,
		arg.Reason,
		arg.UpdatedAt,
		arg.Livemode,
		arg.E2eID,
	)
	return err
}

const saveRailOperation = `-- name: SaveRailOperation :exec
UPDATE payments.test_rail SET status = $2, detail = $3, calls = $4, queries = $5 WHERE key = $1
`

type SaveRailOperationParams struct {
	Key     string
	Status  string
	Detail  string
	Calls   int32
	Queries int32
}

func (q *Queries) SaveRailOperation(ctx context.Context, arg SaveRailOperationParams) error {
	_, err := q.db.Exec(ctx, saveRailOperation,
		arg.Key,
		arg.Status,
		arg.Detail,
		arg.Calls,
		arg.Queries,
	)
	return err
}

const saveRefund = `-- name: SaveRefund :exec
UPDATE payments.refunds
SET status = $1, rail_reference = $2, failure_reason = $3, ledger_txn = $4,
    unknown_since = $5, resolutions = $6, updated_at = $7
WHERE id = $8
`

type SaveRefundParams struct {
	Status        string
	RailReference string
	FailureReason string
	LedgerTxn     pgtype.Text
	UnknownSince  pgtype.Timestamptz
	Resolutions   int32
	UpdatedAt     pgtype.Timestamptz
	ID            string
}

func (q *Queries) SaveRefund(ctx context.Context, arg SaveRefundParams) error {
	_, err := q.db.Exec(ctx, saveRefund,
		arg.Status,
		arg.RailReference,
		arg.FailureReason,
		arg.LedgerTxn,
		arg.UnknownSince,
		arg.Resolutions,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const scheduledPayoutMade = `-- name: ScheduledPayoutMade :one
SELECT EXISTS (SELECT 1 FROM payments.payouts WHERE merchant_id = $1 AND livemode = $2
                                               AND recipient_id = $3 AND scheduled_on = $4)::boolean
`

type ScheduledPayoutMadeParams struct {
	MerchantID  string
	Livemode    bool
	RecipientID string
	ScheduledOn pgtype.Date
}

func (q *Queries) ScheduledPayoutMade(ctx context.Context, arg ScheduledPayoutMadeParams) (bool, error) {
	row := q.db.QueryRow(ctx, scheduledPayoutMade,
		arg.MerchantID,
		arg.Livemode,
		arg.RecipientID,
		arg.ScheduledOn,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const setAttemptFee = `-- name: SetAttemptFee :exec
UPDATE payments.attempts SET fee = $1 WHERE id = $2
`

type SetAttemptFeeParams struct {
	Fee int64
	ID  string
}

func (q *Queries) SetAttemptFee(ctx context.Context, arg SetAttemptFeeParams) error {
	_, err := q.db.Exec(ctx, setAttemptFee, arg.Fee, arg.ID)
	return err
}

const setNetworkToken = `-- name: SetNetworkToken :exec
UPDATE payments.payment_methods
SET network_token_reference = $1, network_token_status = $2, network_token_since = $3
WHERE id = $4 AND network_token_status = 'provisioning' AND network_token_since = $5
`

type SetNetworkTokenParams struct {
	NetworkTokenReference string
	NetworkTokenStatus    string
	Now                   pgtype.Timestamptz
	ID                    string
	ClaimedAt             pgtype.Timestamptz
}

func (q *Queries) SetNetworkToken(ctx context.Context, arg SetNetworkTokenParams) error {
	_, err := q.db.Exec(ctx, setNetworkToken,
		arg.NetworkTokenReference,
		arg.NetworkTokenStatus,
		arg.Now,
		arg.ID,
		arg.ClaimedAt,
	)
	return err
}

const setPaymentMethodNetworkTransaction = `-- name: SetPaymentMethodNetworkTransaction :exec
UPDATE payments.payment_methods SET network_transaction_id = $1
WHERE id = $2 AND network_transaction_id = ''
`

type SetPaymentMethodNetworkTransactionParams struct {
	NetworkTransactionID string
	ID                   string
}

func (q *Queries) SetPaymentMethodNetworkTransaction(ctx context.Context, arg SetPaymentMethodNetworkTransactionParams) error {
	_, err := q.db.Exec(ctx, setPaymentMethodNetworkTransaction, arg.NetworkTransactionID, arg.ID)
	return err
}

const setRefundFee = `-- name: SetRefundFee :exec
UPDATE payments.refunds SET fee_returned = $1 WHERE id = $2
`

type SetRefundFeeParams struct {
	FeeReturned int64
	ID          string
}

func (q *Queries) SetRefundFee(ctx context.Context, arg SetRefundFeeParams) error {
	_, err := q.db.Exec(ctx, setRefundFee, arg.FeeReturned, arg.ID)
	return err
}

const setSplitBack = `-- name: SetSplitBack :exec
UPDATE payments.refunds SET split_back = $1 WHERE id = $2
`

type SetSplitBackParams struct {
	SplitBack int64
	ID        string
}

func (q *Queries) SetSplitBack(ctx context.Context, arg SetSplitBackParams) error {
	_, err := q.db.Exec(ctx, setSplitBack, arg.SplitBack, arg.ID)
	return err
}

const setSplitOut = `-- name: SetSplitOut :exec
UPDATE payments.attempts SET split_out = $1 WHERE id = $2
`

type SetSplitOutParams struct {
	SplitOut int64
	ID       string
}

func (q *Queries) SetSplitOut(ctx context.Context, arg SetSplitOutParams) error {
	_, err := q.db.Exec(ctx, setSplitOut, arg.SplitOut, arg.ID)
	return err
}

const touchPayout = `-- name: TouchPayout :exec
UPDATE payments.payouts SET updated_at = $1 WHERE id = $2
`

type TouchPayoutParams struct {
	UpdatedAt pgtype.Timestamptz
	ID        string
}

func (q *Queries) TouchPayout(ctx context.Context, arg TouchPayoutParams) error {
	_, err := q.db.Exec(ctx, touchPayout, arg.UpdatedAt, arg.ID)
	return err
}

const touchRefund = `-- name: TouchRefund :exec
UPDATE payments.refunds SET resolutions = resolutions + 1, updated_at = $1 WHERE id = $2
`

type TouchRefundParams struct {
	UpdatedAt pgtype.Timestamptz
	ID        string
}

func (q *Queries) TouchRefund(ctx context.Context, arg TouchRefundParams) error {
	_, err := q.db.Exec(ctx, touchRefund, arg.UpdatedAt, arg.ID)
	return err
}

const unmatchedPixTotals = `-- name: UnmatchedPixTotals :many
SELECT livemode, currency, coalesce(sum(amount), 0)::bigint AS held
FROM payments.pix_received WHERE status IN ('unmatched', 'returning', 'return_failed')
GROUP BY livemode, currency
`

type UnmatchedPixTotalsRow struct {
	Livemode bool
	Currency string
	Held     int64
}

func (q *Queries) UnmatchedPixTotals(ctx context.Context) ([]UnmatchedPixTotalsRow, error) {
	rows, err := q.db.Query(ctx, unmatchedPixTotals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnmatchedPixTotalsRow{}
	for rows.Next() {
		var i UnmatchedPixTotalsRow
		if err := rows.Scan(&i.Livemode, &i.Currency, &i.Held); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCardFromNetworkToken = `-- name: UpdateCardFromNetworkToken :execrows
UPDATE payments.payment_methods
SET last4 = $1, exp_month = $2, exp_year = $3, network_token_status = $4,
    network_token_since = $5, network_token_event_at = $6
WHERE network_token_reference = $7
  AND network_token_status IN ('active', 'suspended')
  AND (network_token_event_at IS NULL OR network_token_event_at <= $6)
`

type UpdateCardFromNetworkTokenParams struct {
	Last4                 string
	ExpMonth              int32
	ExpYear               int32
	NetworkTokenStatus    string
	Now                   pgtype.Timestamptz
	OccurredAt            pgtype.Timestamptz
	NetworkTokenReference string
}

func (q *Queries) UpdateCardFromNetworkToken(ctx context.Context, arg UpdateCardFromNetworkTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCardFromNetworkToken,
		arg.Last4,
		arg.ExpMonth,
		arg.ExpYear,
		arg.NetworkTokenStatus,
		arg.Now,
		arg.OccurredAt,
		arg.NetworkTokenReference,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
