// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type VaultCard struct {
	Token                 string
	Owner                 pgtype.Text
	RequestKey            pgtype.Text
	PublishableKey        pgtype.Text
	ClaimExpiresAt        pgtype.Timestamptz
	Fingerprint           []byte
	Brand                 string
	Bin                   string
	Last4                 string
	ExpMonth              int32
	ExpYear               int32
	EncryptedNumber       []byte
	WrappedKey            []byte
	KeyID                 string
	CreatedAt             pgtype.Timestamptz
	NetworkToken          []byte
	NetworkTokenMonth     pgtype.Int4
	NetworkTokenYear      pgtype.Int4
	NetworkTokenReference string
	ClientIp              string
}
