// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cardByRequestKey = `-- name: CardByRequestKey :one
SELECT token, owner, request_key, publishable_key, claim_expires_at, fingerprint, brand, bin, last4, exp_month, exp_year, encrypted_number, wrapped_key, key_id, created_at, network_token, network_token_month, network_token_year, network_token_reference, client_ip FROM vault.cards WHERE owner = $1 AND request_key = $2
`

type CardByRequestKeyParams struct {
	Owner      pgtype.Text
	RequestKey pgtype.Text
}

func (q *Queries) CardByRequestKey(ctx context.Context, arg CardByRequestKeyParams) (VaultCard, error) {
	row := q.db.QueryRow(ctx, cardByRequestKey, arg.Owner, arg.RequestKey)
	var i VaultCard
	err := row.Scan(
		&i.Token,
		&i.Owner,
		&i.RequestKey,
		&i.PublishableKey,
		&i.ClaimExpiresAt,
		&i.Fingerprint,
		&i.Brand,
		&i.Bin,
		&i.Last4,
		&i.ExpMonth,
		&i.ExpYear,
		&i.EncryptedNumber,
		&i.WrappedKey,
		&i.KeyID,
		&i.CreatedAt,
		&i.NetworkToken,
		&i.NetworkTokenMonth,
		&i.NetworkTokenYear,
		&i.NetworkTokenReference,
		&i.ClientIp,
	)
	return i, err
}

const cardsToRewrap = `-- name: CardsToRewrap :many
SELECT token, wrapped_key, key_id FROM vault.cards
WHERE key_id <> $1
ORDER BY token
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type CardsToRewrapParams struct {
	ActiveKey string
	MaxCount  int32
}

type CardsToRewrapRow struct {
	Token      string
	WrappedKey []byte
	KeyID      string
}

func (q *Queries) CardsToRewrap(ctx context.Context, arg CardsToRewrapParams) ([]CardsToRewrapRow, error) {
	rows, err := q.db.Query(ctx, cardsToRewrap, arg.ActiveKey, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardsToRewrapRow{}
	for rows.Next() {
		var i CardsToRewrapRow
		if err := rows.Scan(&i.Token, &i.WrappedKey, &i.KeyID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimCard = `-- name: ClaimCard :one
UPDATE vault.cards SET owner = $1, claim_expires_at = NULL
WHERE token = $2 AND owner IS NULL AND claim_expires_at > $3
RETURNING token, owner, request_key, publishable_key, claim_expires_at, fingerprint, brand, bin, last4, exp_month, exp_year, encrypted_number, wrapped_key, key_id, created_at, network_token, network_token_month, network_token_year, network_token_reference, client_ip
`

type ClaimCardParams struct {
	Owner pgtype.Text
	Token string
	Now   pgtype.Timestamptz
}

func (q *Queries) ClaimCard(ctx context.Context, arg ClaimCardParams) (VaultCard, error) {
	row := q.db.QueryRow(ctx, claimCard, arg.Owner, arg.Token, arg.Now)
	var i VaultCard
	err := row.Scan(
		&i.Token,
		&i.Owner,
		&i.RequestKey,
		&i.PublishableKey,
		&i.ClaimExpiresAt,
		&i.Fingerprint,
		&i.Brand,
		&i.Bin,
		&i.Last4,
		&i.ExpMonth,
		&i.ExpYear,
		&i.EncryptedNumber,
		&i.WrappedKey,
		&i.KeyID,
		&i.CreatedAt,
		&i.NetworkToken,
		&i.NetworkTokenMonth,
		&i.NetworkTokenYear,
		&i.NetworkTokenReference,
		&i.ClientIp,
	)
	return i, err
}

const countCardsUnderKey = `-- name: CountCardsUnderKey :one
SELECT count(*)::bigint FROM vault.cards WHERE key_id = $1
`

func (q *Queries) CountCardsUnderKey(ctx context.Context, keyID string) (int64, error) {
	row := q.db.QueryRow(ctx, countCardsUnderKey, keyID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getCard = `-- name: GetCard :one
SELECT token, owner, request_key, publishable_key, claim_expires_at, fingerprint, brand, bin, last4, exp_month, exp_year, encrypted_number, wrapped_key, key_id, created_at, network_token, network_token_month, network_token_year, network_token_reference, client_ip FROM vault.cards WHERE token = $1
`

func (q *Queries) GetCard(ctx context.Context, token string) (VaultCard, error) {
	row := q.db.QueryRow(ctx, getCard, token)
	var i VaultCard
	err := row.Scan(
		&i.Token,
		&i.Owner,
		&i.RequestKey,
		&i.PublishableKey,
		&i.ClaimExpiresAt,
		&i.Fingerprint,
		&i.Brand,
		&i.Bin,
		&i.Last4,
		&i.ExpMonth,
		&i.ExpYear,
		&i.EncryptedNumber,
		&i.WrappedKey,
		&i.KeyID,
		&i.CreatedAt,
		&i.NetworkToken,
		&i.NetworkTokenMonth,
		&i.NetworkTokenYear,
		&i.NetworkTokenReference,
		&i.ClientIp,
	)
	return i, err
}

const insertCard = `-- name: InsertCard :one
INSERT INTO vault.cards (
    token, owner, request_key, publishable_key, claim_expires_at, fingerprint, brand, bin, last4,
    exp_month, exp_year, encrypted_number, wrapped_key, key_id, client_ip, created_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
ON CONFLICT (owner, request_key) DO NOTHING
RETURNING token, owner, request_key, publishable_key, claim_expires_at, fingerprint, brand, bin, last4, exp_month, exp_year, encrypted_number, wrapped_key, key_id, created_at, network_token, network_token_month, network_token_year, network_token_reference, client_ip
`

type InsertCardParams struct {
	Token           string
	Owner           pgtype.Text
	RequestKey      pgtype.Text
	PublishableKey  pgtype.Text
	ClaimExpiresAt  pgtype.Timestamptz
	Fingerprint     []byte
	Brand           string
	Bin             string
	Last4           string
	ExpMonth        int32
	ExpYear         int32
	EncryptedNumber []byte
	WrappedKey      []byte
	KeyID           string
	ClientIp        string
	CreatedAt       pgtype.Timestamptz
}

// A repeated request key inserts nothing and returns no row; the caller then reads the
// card the first request stored.
func (q *Queries) InsertCard(ctx context.Context, arg InsertCardParams) (VaultCard, error) {
	row := q.db.QueryRow(ctx, insertCard,
		arg.Token,
		arg.Owner,
		arg.RequestKey,
		arg.PublishableKey,
		arg.ClaimExpiresAt,
		arg.Fingerprint,
		arg.Brand,
		arg.Bin,
		arg.Last4,
		arg.ExpMonth,
		arg.ExpYear,
		arg.EncryptedNumber,
		arg.WrappedKey,
		arg.KeyID,
		arg.ClientIp,
		arg.CreatedAt,
	)
	var i VaultCard
	err := row.Scan(
		&i.Token,
		&i.Owner,
		&i.RequestKey,
		&i.PublishableKey,
		&i.ClaimExpiresAt,
		&i.Fingerprint,
		&i.Brand,
		&i.Bin,
		&i.Last4,
		&i.ExpMonth,
		&i.ExpYear,
		&i.EncryptedNumber,
		&i.WrappedKey,
		&i.KeyID,
		&i.CreatedAt,
		&i.NetworkToken,
		&i.NetworkTokenMonth,
		&i.NetworkTokenYear,
		&i.NetworkTokenReference,
		&i.ClientIp,
	)
	return i, err
}

const keyUsage = `-- name: KeyUsage :many
SELECT key_id, count(*)::bigint AS cards FROM vault.cards GROUP BY key_id ORDER BY key_id
`

type KeyUsageRow struct {
	KeyID string
	Cards int64
}

func (q *Queries) KeyUsage(ctx context.Context) ([]KeyUsageRow, error) {
	rows, err := q.db.Query(ctx, keyUsage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KeyUsageRow{}
	for rows.Next() {
		var i KeyUsageRow
		if err := rows.Scan(&i.KeyID, &i.Cards); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeUnclaimed = `-- name: PurgeUnclaimed :execrows
DELETE FROM vault.cards WHERE token IN (
    SELECT c.token FROM vault.cards c WHERE c.owner IS NULL AND c.claim_expires_at <= $1::timestamptz LIMIT $2::integer
)
`

type PurgeUnclaimedParams struct {
	Now      pgtype.Timestamptz
	MaxCount int32
}

// A batch at a time, so that a backlog cannot outlast the statement timeout.
func (q *Queries) PurgeUnclaimed(ctx context.Context, arg PurgeUnclaimedParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeUnclaimed, arg.Now, arg.MaxCount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rewrapCard = `-- name: RewrapCard :exec
UPDATE vault.cards SET wrapped_key = $1, key_id = $2 WHERE token = $3
`

type RewrapCardParams struct {
	WrappedKey []byte
	KeyID      string
	Token      string
}

func (q *Queries) RewrapCard(ctx context.Context, arg RewrapCardParams) error {
	_, err := q.db.Exec(ctx, rewrapCard, arg.WrappedKey, arg.KeyID, arg.Token)
	return err
}

const storeNetworkToken = `-- name: StoreNetworkToken :execrows
UPDATE vault.cards
SET network_token = $1, network_token_month = $2, network_token_year = $3,
    network_token_reference = $4
WHERE token = $5 AND owner = $6
`

type StoreNetworkTokenParams struct {
	NetworkToken          []byte
	NetworkTokenMonth     pgtype.Int4
	NetworkTokenYear      pgtype.Int4
	NetworkTokenReference string
	Token                 string
	Owner                 pgtype.Text
}

func (q *Queries) StoreNetworkToken(ctx context.Context, arg StoreNetworkTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, storeNetworkToken,
		arg.NetworkToken,
		arg.NetworkTokenMonth,
		arg.NetworkTokenYear,
		arg.NetworkTokenReference,
		arg.Token,
		arg.Owner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
