// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ReceivablesAnticipation struct {
	ID          string
	MerchantID  string
	Livemode    bool
	RecipientID string
	Currency    string
	Amount      int64
	Price       int64
	MonthlyRate string
	Automatic   bool
	LedgerTxn   string
	CreatedAt   pgtype.Timestamptz
}

type ReceivablesAnticipationQuote struct {
	ID           string
	MerchantID   string
	Livemode     bool
	RecipientID  string
	MonthlyRate  string
	Units        []byte
	Amount       int64
	Price        int64
	ExpiresAt    pgtype.Timestamptz
	Anticipation pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type ReceivablesAnticipationUnit struct {
	AnticipationID string
	UnitID         string
	Amount         int64
	Price          int64
	Days           int32
	Contract       string
}

type ReceivablesDivergence struct {
	ID         int64
	Livemode   bool
	Kind       string
	Subject    string
	Detail     string
	FoundAt    pgtype.Timestamptz
	ResolvedAt pgtype.Timestamptz
}

type ReceivablesEffectSnapshot struct {
	ID          int64
	UnitID      string
	ObservedAt  pgtype.Timestamptz
	Commitments []byte
}

type ReceivablesInstallment struct {
	AttemptID     string
	Number        int32
	PaymentIntent string
	UnitID        string
	Gross         int64
	Fee           int64
	Net           int64
	Reduced       int64
	RecipientID   string
}

type ReceivablesLedgerAccount struct {
	RecipientID string
	Livemode    bool
	Currency    string
	Role        string
	AccountID   string
}

type ReceivablesMovement struct {
	ID          int64
	RecipientID string
	Livemode    bool
	Currency    string
	Bucket      string
	Kind        string
	Amount      int64
	Reference   string
	At          pgtype.Timestamptz
}

type ReceivablesOptIn struct {
	MerchantID string
	Livemode   bool
	Financier  string
	Active     bool
	Synced     bool
	SyncError  string
	RetryAt    pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ReceivablesReconciliation struct {
	Livemode    bool
	Kind        string
	RanOn       pgtype.Date
	RanAt       pgtype.Timestamptz
	Divergences int32
}

type ReceivablesSplitLine struct {
	AttemptID     string
	PaymentIntent string
	RecipientID   string
	Type          string
	Amount        int64
	Liable        bool
	LedgerTxn     string
}

type ReceivablesUnit struct {
	ID                string
	MerchantID        string
	Livemode          bool
	Arrangement       string
	SettlementDate    pgtype.Date
	Value             int64
	Blocked           int64
	Currency          string
	ConstitutedOn     pgtype.Date
	Version           int32
	RegisteredVersion int32
	RegisteredAt      pgtype.Timestamptz
	RegisterError     string
	RegisterRetryAt   pgtype.Timestamptz
	SettledOn         pgtype.Date
	SettledAmount     pgtype.Int8
	Payments          []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	RecipientID       string
	Anticipated       int64
}

type ReceivablesUnitEvent struct {
	ID        int64
	UnitID    string
	At        pgtype.Timestamptz
	Kind      string
	Amount    int64
	Reference string
}
