// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ReceivablesDivergence struct {
	ID         int64
	Livemode   bool
	Kind       string
	Subject    string
	Detail     string
	FoundAt    pgtype.Timestamptz
	ResolvedAt pgtype.Timestamptz
}

type ReceivablesEffectSnapshot struct {
	ID          int64
	UnitID      string
	ObservedAt  pgtype.Timestamptz
	Commitments []byte
}

type ReceivablesInstallment struct {
	AttemptID     string
	Number        int32
	PaymentIntent string
	UnitID        string
	Gross         int64
	Fee           int64
	Net           int64
	Reduced       int64
}

type ReceivablesOptIn struct {
	MerchantID string
	Livemode   bool
	Financier  string
	Active     bool
	Synced     bool
	SyncError  string
	RetryAt    pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ReceivablesReconciliation struct {
	Livemode    bool
	Kind        string
	RanOn       pgtype.Date
	RanAt       pgtype.Timestamptz
	Divergences int32
}

type ReceivablesUnit struct {
	ID                string
	MerchantID        string
	Livemode          bool
	Arrangement       string
	SettlementDate    pgtype.Date
	Value             int64
	Blocked           int64
	Currency          string
	ConstitutedOn     pgtype.Date
	Version           int32
	RegisteredVersion int32
	RegisteredAt      pgtype.Timestamptz
	RegisterError     string
	RegisterRetryAt   pgtype.Timestamptz
	SettledOn         pgtype.Date
	SettledAmount     pgtype.Int8
	Payments          []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type ReceivablesUnitEvent struct {
	ID        int64
	UnitID    string
	At        pgtype.Timestamptz
	Kind      string
	Amount    int64
	Reference string
}
