// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const agendaAsOf = `-- name: AgendaAsOf :many
SELECT u.id, u.arrangement, u.settlement_date, u.currency, u.blocked, u.registered_version, u.settled_on,
       coalesce(ev.value, 0)::bigint AS value, coalesce(ev.settled, 0)::bigint AS settled,
       coalesce(ev.is_settled, false)::boolean AS is_settled,
       snap.commitments
FROM receivables.units u
LEFT JOIN LATERAL (
    SELECT sum(e.amount) FILTER (WHERE e.kind IN ('constituted', 'reduced')) AS value,
           sum(e.amount) FILTER (WHERE e.kind = 'settled') AS settled,
           bool_or(e.kind = 'settled') AS is_settled
    FROM receivables.unit_events e WHERE e.unit_id = u.id AND e.at <= $1
) ev ON true
LEFT JOIN LATERAL (
    SELECT es.commitments FROM receivables.effect_snapshots es
    WHERE es.unit_id = u.id AND es.observed_at <= $1
    ORDER BY es.observed_at DESC, es.id DESC LIMIT 1
) snap ON true
WHERE u.merchant_id = $2 AND u.livemode = $3
  AND u.settlement_date BETWEEN $4 AND $5 AND u.created_at <= $1
ORDER BY u.settlement_date, u.arrangement
`

type AgendaAsOfParams struct {
	At         pgtype.Timestamptz
	MerchantID string
	Livemode   bool
	FromDate   pgtype.Date
	ToDate     pgtype.Date
}

type AgendaAsOfRow struct {
	ID                string
	Arrangement       string
	SettlementDate    pgtype.Date
	Currency          string
	Blocked           int64
	RegisteredVersion int32
	SettledOn         pgtype.Date
	Value             int64
	Settled           int64
	IsSettled         bool
	Commitments       []byte
}

// A merchant's units as they stood at a moment: their value from the events until then,
// their commitments from the last snapshot before it.
func (q *Queries) AgendaAsOf(ctx context.Context, arg AgendaAsOfParams) ([]AgendaAsOfRow, error) {
	rows, err := q.db.Query(ctx, agendaAsOf,
		arg.At,
		arg.MerchantID,
		arg.Livemode,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgendaAsOfRow{}
	for rows.Next() {
		var i AgendaAsOfRow
		if err := rows.Scan(
			&i.ID,
			&i.Arrangement,
			&i.SettlementDate,
			&i.Currency,
			&i.Blocked,
			&i.RegisteredVersion,
			&i.SettledOn,
			&i.Value,
			&i.Settled,
			&i.IsSettled,
			&i.Commitments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const changeUnitValue = `-- name: ChangeUnitValue :exec
UPDATE receivables.units
SET value = value + $1, constituted_on = greatest(constituted_on, $2), version = version + 1,
    register_retry_at = NULL, updated_at = $3
WHERE id = $4
`

type ChangeUnitValueParams struct {
	Delta         int64
	ConstitutedOn pgtype.Date
	Now           pgtype.Timestamptz
	ID            string
}

// Any change is a new version the registry must take.
func (q *Queries) ChangeUnitValue(ctx context.Context, arg ChangeUnitValueParams) error {
	_, err := q.db.Exec(ctx, changeUnitValue,
		arg.Delta,
		arg.ConstitutedOn,
		arg.Now,
		arg.ID,
	)
	return err
}

const countOptIns = `-- name: CountOptIns :one
SELECT count(*) FROM receivables.opt_ins WHERE merchant_id = $1 AND livemode = $2 AND financier <> $3
`

type CountOptInsParams struct {
	MerchantID string
	Livemode   bool
	Financier  string
}

// Others than financier: changing an existing one never counts against the cap.
func (q *Queries) CountOptIns(ctx context.Context, arg CountOptInsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOptIns, arg.MerchantID, arg.Livemode, arg.Financier)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUnit = `-- name: GetUnit :one
SELECT id, merchant_id, livemode, arrangement, settlement_date, value, blocked, currency, constituted_on, version, registered_version, registered_at, register_error, register_retry_at, settled_on, settled_amount, payments, created_at, updated_at FROM receivables.units WHERE id = $1
`

func (q *Queries) GetUnit(ctx context.Context, id string) (ReceivablesUnit, error) {
	row := q.db.QueryRow(ctx, getUnit, id)
	var i ReceivablesUnit
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Arrangement,
		&i.SettlementDate,
		&i.Value,
		&i.Blocked,
		&i.Currency,
		&i.ConstitutedOn,
		&i.Version,
		&i.RegisteredVersion,
		&i.RegisteredAt,
		&i.RegisterError,
		&i.RegisterRetryAt,
		&i.SettledOn,
		&i.SettledAmount,
		&i.Payments,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertInstallment = `-- name: InsertInstallment :exec
INSERT INTO receivables.installments (attempt_id, number, payment_intent, unit_id, gross, fee, net)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertInstallmentParams struct {
	AttemptID     string
	Number        int32
	PaymentIntent string
	UnitID        string
	Gross         int64
	Fee           int64
	Net           int64
}

func (q *Queries) InsertInstallment(ctx context.Context, arg InsertInstallmentParams) error {
	_, err := q.db.Exec(ctx, insertInstallment,
		arg.AttemptID,
		arg.Number,
		arg.PaymentIntent,
		arg.UnitID,
		arg.Gross,
		arg.Fee,
		arg.Net,
	)
	return err
}

const insertReconciliation = `-- name: InsertReconciliation :exec
INSERT INTO receivables.reconciliations (livemode, kind, ran_on, ran_at, divergences)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (livemode, kind, ran_on) DO UPDATE SET ran_at = excluded.ran_at, divergences = excluded.divergences
`

type InsertReconciliationParams struct {
	Livemode    bool
	Kind        string
	RanOn       pgtype.Date
	RanAt       pgtype.Timestamptz
	Divergences int32
}

func (q *Queries) InsertReconciliation(ctx context.Context, arg InsertReconciliationParams) error {
	_, err := q.db.Exec(ctx, insertReconciliation,
		arg.Livemode,
		arg.Kind,
		arg.RanOn,
		arg.RanAt,
		arg.Divergences,
	)
	return err
}

const insertSnapshot = `-- name: InsertSnapshot :exec
INSERT INTO receivables.effect_snapshots (unit_id, observed_at, commitments) VALUES ($1, $2, $3)
`

type InsertSnapshotParams struct {
	UnitID      string
	ObservedAt  pgtype.Timestamptz
	Commitments []byte
}

func (q *Queries) InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertSnapshot, arg.UnitID, arg.ObservedAt, arg.Commitments)
	return err
}

const insertUnit = `-- name: InsertUnit :exec
INSERT INTO receivables.units (id, merchant_id, livemode, arrangement, settlement_date, value, currency, constituted_on, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, 0, $6, $7, $8, $8)
ON CONFLICT (merchant_id, livemode, arrangement, settlement_date) DO NOTHING
`

type InsertUnitParams struct {
	ID             string
	MerchantID     string
	Livemode       bool
	Arrangement    string
	SettlementDate pgtype.Date
	Currency       string
	ConstitutedOn  pgtype.Date
	Now            pgtype.Timestamptz
}

func (q *Queries) InsertUnit(ctx context.Context, arg InsertUnitParams) error {
	_, err := q.db.Exec(ctx, insertUnit,
		arg.ID,
		arg.MerchantID,
		arg.Livemode,
		arg.Arrangement,
		arg.SettlementDate,
		arg.Currency,
		arg.ConstitutedOn,
		arg.Now,
	)
	return err
}

const insertUnitEvent = `-- name: InsertUnitEvent :exec
INSERT INTO receivables.unit_events (unit_id, at, kind, amount, reference) VALUES ($1, $2, $3, $4, $5)
`

type InsertUnitEventParams struct {
	UnitID    string
	At        pgtype.Timestamptz
	Kind      string
	Amount    int64
	Reference string
}

func (q *Queries) InsertUnitEvent(ctx context.Context, arg InsertUnitEventParams) error {
	_, err := q.db.Exec(ctx, insertUnitEvent,
		arg.UnitID,
		arg.At,
		arg.Kind,
		arg.Amount,
		arg.Reference,
	)
	return err
}

const installmentTotals = `-- name: InstallmentTotals :many
SELECT u.id, u.value, coalesce(sum(i.net - i.reduced), 0)::bigint AS from_installments
FROM receivables.units u LEFT JOIN receivables.installments i ON i.unit_id = u.id
GROUP BY u.id, u.value
`

type InstallmentTotalsRow struct {
	ID               string
	Value            int64
	FromInstallments int64
}

// For the check: each unit's value is what its installments constituted, less reductions.
func (q *Queries) InstallmentTotals(ctx context.Context) ([]InstallmentTotalsRow, error) {
	rows, err := q.db.Query(ctx, installmentTotals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstallmentTotalsRow{}
	for rows.Next() {
		var i InstallmentTotalsRow
		if err := rows.Scan(&i.ID, &i.Value, &i.FromInstallments); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const installmentsOfIntent = `-- name: InstallmentsOfIntent :many
SELECT i.attempt_id, i.number, i.payment_intent, i.unit_id, i.gross, i.fee, i.net, i.reduced, (u.settled_on IS NOT NULL)::boolean AS unit_settled
FROM receivables.installments i JOIN receivables.units u ON u.id = i.unit_id
WHERE i.payment_intent = $1
ORDER BY i.number
FOR UPDATE OF i, u
`

type InstallmentsOfIntentRow struct {
	AttemptID     string
	Number        int32
	PaymentIntent string
	UnitID        string
	Gross         int64
	Fee           int64
	Net           int64
	Reduced       int64
	UnitSettled   bool
}

func (q *Queries) InstallmentsOfIntent(ctx context.Context, paymentIntent string) ([]InstallmentsOfIntentRow, error) {
	rows, err := q.db.Query(ctx, installmentsOfIntent, paymentIntent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstallmentsOfIntentRow{}
	for rows.Next() {
		var i InstallmentsOfIntentRow
		if err := rows.Scan(
			&i.AttemptID,
			&i.Number,
			&i.PaymentIntent,
			&i.UnitID,
			&i.Gross,
			&i.Fee,
			&i.Net,
			&i.Reduced,
			&i.UnitSettled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lastReconciliation = `-- name: LastReconciliation :one
SELECT coalesce(max(ran_on), '0001-01-01'::date)::date FROM receivables.reconciliations WHERE livemode = $1 AND kind = $2
`

type LastReconciliationParams struct {
	Livemode bool
	Kind     string
}

func (q *Queries) LastReconciliation(ctx context.Context, arg LastReconciliationParams) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, lastReconciliation, arg.Livemode, arg.Kind)
	var column_1 pgtype.Date
	err := row.Scan(&column_1)
	return column_1, err
}

const latestSnapshot = `-- name: LatestSnapshot :one
SELECT commitments FROM receivables.effect_snapshots
WHERE unit_id = $1 AND observed_at <= $2
ORDER BY observed_at DESC, id DESC LIMIT 1
`

type LatestSnapshotParams struct {
	UnitID string
	At     pgtype.Timestamptz
}

func (q *Queries) LatestSnapshot(ctx context.Context, arg LatestSnapshotParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, latestSnapshot, arg.UnitID, arg.At)
	var commitments []byte
	err := row.Scan(&commitments)
	return commitments, err
}

const latestSnapshots = `-- name: LatestSnapshots :many
SELECT DISTINCT ON (es.unit_id) es.unit_id, es.commitments
FROM receivables.effect_snapshots es JOIN receivables.units u ON u.id = es.unit_id
WHERE u.livemode = $1 AND u.settled_on IS NULL
ORDER BY es.unit_id, es.observed_at DESC, es.id DESC
`

type LatestSnapshotsRow struct {
	UnitID      string
	Commitments []byte
}

// What was last seen committed on each unsettled unit of a mode.
func (q *Queries) LatestSnapshots(ctx context.Context, livemode bool) ([]LatestSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, latestSnapshots, livemode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestSnapshotsRow{}
	for rows.Next() {
		var i LatestSnapshotsRow
		if err := rows.Scan(&i.UnitID, &i.Commitments); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUnit = `-- name: LockUnit :one
SELECT id, merchant_id, livemode, arrangement, settlement_date, value, blocked, currency, constituted_on, version, registered_version, registered_at, register_error, register_retry_at, settled_on, settled_amount, payments, created_at, updated_at FROM receivables.units
WHERE merchant_id = $1 AND livemode = $2 AND arrangement = $3 AND settlement_date = $4
FOR UPDATE
`

type LockUnitParams struct {
	MerchantID     string
	Livemode       bool
	Arrangement    string
	SettlementDate pgtype.Date
}

func (q *Queries) LockUnit(ctx context.Context, arg LockUnitParams) (ReceivablesUnit, error) {
	row := q.db.QueryRow(ctx, lockUnit,
		arg.MerchantID,
		arg.Livemode,
		arg.Arrangement,
		arg.SettlementDate,
	)
	var i ReceivablesUnit
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Arrangement,
		&i.SettlementDate,
		&i.Value,
		&i.Blocked,
		&i.Currency,
		&i.ConstitutedOn,
		&i.Version,
		&i.RegisteredVersion,
		&i.RegisteredAt,
		&i.RegisterError,
		&i.RegisterRetryAt,
		&i.SettledOn,
		&i.SettledAmount,
		&i.Payments,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockUnitByID = `-- name: LockUnitByID :one
SELECT id, merchant_id, livemode, arrangement, settlement_date, value, blocked, currency, constituted_on, version, registered_version, registered_at, register_error, register_retry_at, settled_on, settled_amount, payments, created_at, updated_at FROM receivables.units WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockUnitByID(ctx context.Context, id string) (ReceivablesUnit, error) {
	row := q.db.QueryRow(ctx, lockUnitByID, id)
	var i ReceivablesUnit
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Arrangement,
		&i.SettlementDate,
		&i.Value,
		&i.Blocked,
		&i.Currency,
		&i.ConstitutedOn,
		&i.Version,
		&i.RegisteredVersion,
		&i.RegisteredAt,
		&i.RegisterError,
		&i.RegisterRetryAt,
		&i.SettledOn,
		&i.SettledAmount,
		&i.Payments,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOptInError = `-- name: MarkOptInError :exec
UPDATE receivables.opt_ins SET sync_error = $1, retry_at = $2
WHERE merchant_id = $3 AND livemode = $4 AND financier = $5
`

type MarkOptInErrorParams struct {
	Error      string
	RetryAt    pgtype.Timestamptz
	MerchantID string
	Livemode   bool
	Financier  string
}

func (q *Queries) MarkOptInError(ctx context.Context, arg MarkOptInErrorParams) error {
	_, err := q.db.Exec(ctx, markOptInError,
		arg.Error,
		arg.RetryAt,
		arg.MerchantID,
		arg.Livemode,
		arg.Financier,
	)
	return err
}

const markOptInSynced = `-- name: MarkOptInSynced :exec
UPDATE receivables.opt_ins SET synced = true, sync_error = '', retry_at = NULL
WHERE merchant_id = $1 AND livemode = $2 AND financier = $3 AND updated_at = $4
`

type MarkOptInSyncedParams struct {
	MerchantID string
	Livemode   bool
	Financier  string
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) MarkOptInSynced(ctx context.Context, arg MarkOptInSyncedParams) error {
	_, err := q.db.Exec(ctx, markOptInSynced,
		arg.MerchantID,
		arg.Livemode,
		arg.Financier,
		arg.UpdatedAt,
	)
	return err
}

const markRegisterError = `-- name: MarkRegisterError :exec
UPDATE receivables.units SET register_error = $1, register_retry_at = $2 WHERE id = $3
`

type MarkRegisterErrorParams struct {
	Error   string
	RetryAt pgtype.Timestamptz
	ID      string
}

func (q *Queries) MarkRegisterError(ctx context.Context, arg MarkRegisterErrorParams) error {
	_, err := q.db.Exec(ctx, markRegisterError, arg.Error, arg.RetryAt, arg.ID)
	return err
}

const markRegistered = `-- name: MarkRegistered :exec
UPDATE receivables.units
SET registered_version = greatest(registered_version, $1), registered_at = $2, register_error = ''
WHERE id = $3
`

type MarkRegisteredParams struct {
	Version int32
	Now     pgtype.Timestamptz
	ID      string
}

func (q *Queries) MarkRegistered(ctx context.Context, arg MarkRegisteredParams) error {
	_, err := q.db.Exec(ctx, markRegistered, arg.Version, arg.Now, arg.ID)
	return err
}

const markSettled = `-- name: MarkSettled :exec
UPDATE receivables.units
SET settled_on = $1, settled_amount = $2, payments = $3, updated_at = $4
WHERE id = $5 AND settled_on IS NULL
`

type MarkSettledParams struct {
	SettledOn pgtype.Date
	Amount    pgtype.Int8
	Payments  []byte
	Now       pgtype.Timestamptz
	ID        string
}

func (q *Queries) MarkSettled(ctx context.Context, arg MarkSettledParams) error {
	_, err := q.db.Exec(ctx, markSettled,
		arg.SettledOn,
		arg.Amount,
		arg.Payments,
		arg.Now,
		arg.ID,
	)
	return err
}

const openDivergence = `-- name: OpenDivergence :exec
INSERT INTO receivables.divergences (livemode, kind, subject, detail, found_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (livemode, kind, subject) WHERE resolved_at IS NULL DO UPDATE SET detail = excluded.detail
`

type OpenDivergenceParams struct {
	Livemode bool
	Kind     string
	Subject  string
	Detail   string
	FoundAt  pgtype.Timestamptz
}

func (q *Queries) OpenDivergence(ctx context.Context, arg OpenDivergenceParams) error {
	_, err := q.db.Exec(ctx, openDivergence,
		arg.Livemode,
		arg.Kind,
		arg.Subject,
		arg.Detail,
		arg.FoundAt,
	)
	return err
}

const openDivergences = `-- name: OpenDivergences :many
SELECT id, livemode, kind, subject, detail, found_at, resolved_at FROM receivables.divergences WHERE resolved_at IS NULL ORDER BY found_at, id
`

func (q *Queries) OpenDivergences(ctx context.Context) ([]ReceivablesDivergence, error) {
	rows, err := q.db.Query(ctx, openDivergences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceivablesDivergence{}
	for rows.Next() {
		var i ReceivablesDivergence
		if err := rows.Scan(
			&i.ID,
			&i.Livemode,
			&i.Kind,
			&i.Subject,
			&i.Detail,
			&i.FoundAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const optInsOf = `-- name: OptInsOf :many
SELECT merchant_id, livemode, financier, active, synced, sync_error, retry_at, updated_at FROM receivables.opt_ins WHERE merchant_id = $1 AND livemode = $2 ORDER BY financier
`

type OptInsOfParams struct {
	MerchantID string
	Livemode   bool
}

func (q *Queries) OptInsOf(ctx context.Context, arg OptInsOfParams) ([]ReceivablesOptIn, error) {
	rows, err := q.db.Query(ctx, optInsOf, arg.MerchantID, arg.Livemode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceivablesOptIn{}
	for rows.Next() {
		var i ReceivablesOptIn
		if err := rows.Scan(
			&i.MerchantID,
			&i.Livemode,
			&i.Financier,
			&i.Active,
			&i.Synced,
			&i.SyncError,
			&i.RetryAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const optInsToSync = `-- name: OptInsToSync :many
SELECT merchant_id, livemode, financier, active, synced, sync_error, retry_at, updated_at FROM receivables.opt_ins
WHERE livemode = $1 AND NOT synced AND (retry_at IS NULL OR retry_at <= $2)
ORDER BY updated_at LIMIT 100
`

type OptInsToSyncParams struct {
	Livemode bool
	Now      pgtype.Timestamptz
}

func (q *Queries) OptInsToSync(ctx context.Context, arg OptInsToSyncParams) ([]ReceivablesOptIn, error) {
	rows, err := q.db.Query(ctx, optInsToSync, arg.Livemode, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceivablesOptIn{}
	for rows.Next() {
		var i ReceivablesOptIn
		if err := rows.Scan(
			&i.MerchantID,
			&i.Livemode,
			&i.Financier,
			&i.Active,
			&i.Synced,
			&i.SyncError,
			&i.RetryAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reduceInstallment = `-- name: ReduceInstallment :exec
UPDATE receivables.installments SET reduced = reduced + $1 WHERE attempt_id = $2 AND number = $3
`

type ReduceInstallmentParams struct {
	Amount    int64
	AttemptID string
	Number    int32
}

func (q *Queries) ReduceInstallment(ctx context.Context, arg ReduceInstallmentParams) error {
	_, err := q.db.Exec(ctx, reduceInstallment, arg.Amount, arg.AttemptID, arg.Number)
	return err
}

const reregister = `-- name: Reregister :exec
UPDATE receivables.units
SET registered_version = 0, register_retry_at = NULL, constituted_on = greatest(constituted_on, $1)
WHERE id = $2
`

type ReregisterParams struct {
	Today pgtype.Date
	ID    string
}

// The registry disagrees with what it was sent: send it again.
// The correction is due from the day it is found.
func (q *Queries) Reregister(ctx context.Context, arg ReregisterParams) error {
	_, err := q.db.Exec(ctx, reregister, arg.Today, arg.ID)
	return err
}

const resolveDivergences = `-- name: ResolveDivergences :exec
UPDATE receivables.divergences SET resolved_at = $1
WHERE livemode = $2 AND kind = $3 AND resolved_at IS NULL AND NOT (subject = ANY($4::text[]))
`

type ResolveDivergencesParams struct {
	Now      pgtype.Timestamptz
	Livemode bool
	Kind     string
	Still    []string
}

// Those of a kind a reconciliation no longer found.
func (q *Queries) ResolveDivergences(ctx context.Context, arg ResolveDivergencesParams) error {
	_, err := q.db.Exec(ctx, resolveDivergences,
		arg.Now,
		arg.Livemode,
		arg.Kind,
		arg.Still,
	)
	return err
}

const setOptIn = `-- name: SetOptIn :exec
INSERT INTO receivables.opt_ins (merchant_id, livemode, financier, active, synced, updated_at)
VALUES ($1, $2, $3, $4, false, $5)
ON CONFLICT (merchant_id, livemode, financier) DO UPDATE
SET active = excluded.active, synced = false, sync_error = '', retry_at = NULL, updated_at = excluded.updated_at
`

type SetOptInParams struct {
	MerchantID string
	Livemode   bool
	Financier  string
	Active     bool
	Now        pgtype.Timestamptz
}

func (q *Queries) SetOptIn(ctx context.Context, arg SetOptInParams) error {
	_, err := q.db.Exec(ctx, setOptIn,
		arg.MerchantID,
		arg.Livemode,
		arg.Financier,
		arg.Active,
		arg.Now,
	)
	return err
}

const unitsToReconcile = `-- name: UnitsToReconcile :many
SELECT id, merchant_id, livemode, arrangement, settlement_date, value, blocked, currency, constituted_on, version, registered_version, registered_at, register_error, register_retry_at, settled_on, settled_amount, payments, created_at, updated_at FROM receivables.units
WHERE livemode = $1 AND (settled_on IS NULL OR settlement_date >= $2)
ORDER BY settlement_date, id
`

type UnitsToReconcileParams struct {
	Livemode bool
	Since    pgtype.Date
}

// A mode's units still unsettled, or settled on or after since.
func (q *Queries) UnitsToReconcile(ctx context.Context, arg UnitsToReconcileParams) ([]ReceivablesUnit, error) {
	rows, err := q.db.Query(ctx, unitsToReconcile, arg.Livemode, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceivablesUnit{}
	for rows.Next() {
		var i ReceivablesUnit
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Livemode,
			&i.Arrangement,
			&i.SettlementDate,
			&i.Value,
			&i.Blocked,
			&i.Currency,
			&i.ConstitutedOn,
			&i.Version,
			&i.RegisteredVersion,
			&i.RegisteredAt,
			&i.RegisterError,
			&i.RegisterRetryAt,
			&i.SettledOn,
			&i.SettledAmount,
			&i.Payments,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unitsToRegister = `-- name: UnitsToRegister :many
SELECT id, merchant_id, livemode, arrangement, settlement_date, value, blocked, currency, constituted_on, version, registered_version, registered_at, register_error, register_retry_at, settled_on, settled_amount, payments, created_at, updated_at FROM receivables.units
WHERE livemode = $1 AND version > registered_version AND (register_retry_at IS NULL OR register_retry_at <= $2)
ORDER BY updated_at, id
LIMIT $3::integer
`

type UnitsToRegisterParams struct {
	Livemode bool
	Now      pgtype.Timestamptz
	MaxCount int32
}

func (q *Queries) UnitsToRegister(ctx context.Context, arg UnitsToRegisterParams) ([]ReceivablesUnit, error) {
	rows, err := q.db.Query(ctx, unitsToRegister, arg.Livemode, arg.Now, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceivablesUnit{}
	for rows.Next() {
		var i ReceivablesUnit
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Livemode,
			&i.Arrangement,
			&i.SettlementDate,
			&i.Value,
			&i.Blocked,
			&i.Currency,
			&i.ConstitutedOn,
			&i.Version,
			&i.RegisteredVersion,
			&i.RegisteredAt,
			&i.RegisterError,
			&i.RegisterRetryAt,
			&i.SettledOn,
			&i.SettledAmount,
			&i.Payments,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unregisteredSince = `-- name: UnregisteredSince :many
SELECT id, livemode, constituted_on, register_error FROM receivables.units
WHERE version > registered_version AND constituted_on <= $1 AND livemode = ANY($2::boolean[])
ORDER BY constituted_on, id
LIMIT 1000
`

type UnregisteredSinceParams struct {
	Day   pgtype.Date
	Modes []bool
}

type UnregisteredSinceRow struct {
	ID            string
	Livemode      bool
	ConstitutedOn pgtype.Date
	RegisterError string
}

// Units not registered as they are, from sales on or before a day: the late ones.
func (q *Queries) UnregisteredSince(ctx context.Context, arg UnregisteredSinceParams) ([]UnregisteredSinceRow, error) {
	rows, err := q.db.Query(ctx, unregisteredSince, arg.Day, arg.Modes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnregisteredSinceRow{}
	for rows.Next() {
		var i UnregisteredSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.Livemode,
			&i.ConstitutedOn,
			&i.RegisterError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
