// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const agendaAsOf = `-- name: AgendaAsOf :many
SELECT u.id, u.arrangement, u.settlement_date, u.currency, u.blocked, u.anticipated, u.registered_version, u.settled_on,
       coalesce(ev.value, 0)::bigint AS value, coalesce(ev.settled, 0)::bigint AS settled,
       coalesce(ev.is_settled, false)::boolean AS is_settled,
       snap.commitments
FROM receivables.units u
LEFT JOIN LATERAL (
    SELECT sum(e.amount) FILTER (WHERE e.kind IN ('constituted', 'reduced')) AS value,
           sum(e.amount) FILTER (WHERE e.kind = 'settled') AS settled,
           bool_or(e.kind = 'settled') AS is_settled
    FROM receivables.unit_events e WHERE e.unit_id = u.id AND e.at <= $1
) ev ON true
LEFT JOIN LATERAL (
    SELECT es.commitments FROM receivables.effect_snapshots es
    WHERE es.unit_id = u.id AND es.observed_at <= $1
    ORDER BY es.observed_at DESC, es.id DESC LIMIT 1
) snap ON true
WHERE u.merchant_id = $2 AND u.recipient_id = $3 AND u.livemode = $4
  AND u.settlement_date BETWEEN $5 AND $6 AND u.created_at <= $1
ORDER BY u.settlement_date, u.arrangement
`

type AgendaAsOfParams struct {
	At          pgtype.Timestamptz
	MerchantID  string
	RecipientID string
	Livemode    bool
	FromDate    pgtype.Date
	ToDate      pgtype.Date
}

type AgendaAsOfRow struct {
	ID                string
	Arrangement       string
	SettlementDate    pgtype.Date
	Currency          string
	Blocked           int64
	Anticipated       int64
	RegisteredVersion int32
	SettledOn         pgtype.Date
	Value             int64
	Settled           int64
	IsSettled         bool
	Commitments       []byte
}

// A merchant's units as they stood at a moment: their value from the events until then,
// their commitments from the last snapshot before it.
func (q *Queries) AgendaAsOf(ctx context.Context, arg AgendaAsOfParams) ([]AgendaAsOfRow, error) {
	rows, err := q.db.Query(ctx, agendaAsOf,
		arg.At,
		arg.MerchantID,
		arg.RecipientID,
		arg.Livemode,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgendaAsOfRow{}
	for rows.Next() {
		var i AgendaAsOfRow
		if err := rows.Scan(
			&i.ID,
			&i.Arrangement,
			&i.SettlementDate,
			&i.Currency,
			&i.Blocked,
			&i.Anticipated,
			&i.RegisteredVersion,
			&i.SettledOn,
			&i.Value,
			&i.Settled,
			&i.IsSettled,
			&i.Commitments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const allLedgerAccounts = `-- name: AllLedgerAccounts :many
SELECT recipient_id, livemode, currency, role, account_id FROM receivables.ledger_accounts WHERE recipient_id <> '' ORDER BY recipient_id, livemode, currency, role
`

func (q *Queries) AllLedgerAccounts(ctx context.Context) ([]ReceivablesLedgerAccount, error) {
	rows, err := q.db.Query(ctx, allLedgerAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceivablesLedgerAccount{}
	for rows.Next() {
		var i ReceivablesLedgerAccount
		if err := rows.Scan(
			&i.RecipientID,
			&i.Livemode,
			&i.Currency,
			&i.Role,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const anticipableUnits = `-- name: AnticipableUnits :many
SELECT id, merchant_id, livemode, arrangement, settlement_date, value, blocked, currency, constituted_on, version, registered_version, registered_at, register_error, register_retry_at, settled_on, settled_amount, payments, created_at, updated_at, recipient_id, anticipated, grade_date FROM receivables.units
WHERE recipient_id = $1 AND livemode = $2 AND settled_on IS NULL AND settlement_date > $3
  AND value > anticipated AND registered_version = version
  AND (cardinality($4::text[]) = 0 OR id = ANY($4::text[]))
  AND created_at <= $5
ORDER BY settlement_date, id
LIMIT 400
FOR UPDATE
`

type AnticipableUnitsParams struct {
	RecipientID       string
	Livemode          bool
	Today             pgtype.Date
	Ids               []string
	ConstitutedBefore pgtype.Timestamptz
}

// A recipient's units Jupiter can buy: registered as they are, not settled, settling
// after today, with something not yet bought.
func (q *Queries) AnticipableUnits(ctx context.Context, arg AnticipableUnitsParams) ([]ReceivablesUnit, error) {
	rows, err := q.db.Query(ctx, anticipableUnits,
		arg.RecipientID,
		arg.Livemode,
		arg.Today,
		arg.Ids,
		arg.ConstitutedBefore,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceivablesUnit{}
	for rows.Next() {
		var i ReceivablesUnit
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Livemode,
			&i.Arrangement,
			&i.SettlementDate,
			&i.Value,
			&i.Blocked,
			&i.Currency,
			&i.ConstitutedOn,
			&i.Version,
			&i.RegisteredVersion,
			&i.RegisteredAt,
			&i.RegisterError,
			&i.RegisterRetryAt,
			&i.SettledOn,
			&i.SettledAmount,
			&i.Payments,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecipientID,
			&i.Anticipated,
			&i.GradeDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const anticipationTotals = `-- name: AnticipationTotals :many
SELECT u.id, u.anticipated, coalesce(sum(au.amount), 0)::bigint AS bought
FROM receivables.units u LEFT JOIN receivables.anticipation_units au ON au.unit_id = u.id
GROUP BY u.id, u.anticipated
`

type AnticipationTotalsRow struct {
	ID          string
	Anticipated int64
	Bought      int64
}

// For the check: what Jupiter bought of each unit.
func (q *Queries) AnticipationTotals(ctx context.Context) ([]AnticipationTotalsRow, error) {
	rows, err := q.db.Query(ctx, anticipationTotals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnticipationTotalsRow{}
	for rows.Next() {
		var i AnticipationTotalsRow
		if err := rows.Scan(&i.ID, &i.Anticipated, &i.Bought); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const anticipationUnits = `-- name: AnticipationUnits :many
SELECT anticipation_id, unit_id, amount, price, days, contract, reported_at FROM receivables.anticipation_units WHERE anticipation_id = $1 ORDER BY unit_id
`

func (q *Queries) AnticipationUnits(ctx context.Context, anticipationID string) ([]ReceivablesAnticipationUnit, error) {
	rows, err := q.db.Query(ctx, anticipationUnits, anticipationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceivablesAnticipationUnit{}
	for rows.Next() {
		var i ReceivablesAnticipationUnit
		if err := rows.Scan(
			&i.AnticipationID,
			&i.UnitID,
			&i.Amount,
			&i.Price,
			&i.Days,
			&i.Contract,
			&i.ReportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const anticipationsToReport = `-- name: AnticipationsToReport :many
SELECT au.anticipation_id, au.unit_id, au.amount, a.created_at
FROM receivables.anticipation_units au JOIN receivables.anticipations a ON a.id = au.anticipation_id
WHERE a.livemode = $1 AND au.reported_at IS NULL
ORDER BY a.created_at, au.anticipation_id, au.unit_id
LIMIT 500
`

type AnticipationsToReportRow struct {
	AnticipationID string
	UnitID         string
	Amount         int64
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) AnticipationsToReport(ctx context.Context, livemode bool) ([]AnticipationsToReportRow, error) {
	rows, err := q.db.Query(ctx, anticipationsToReport, livemode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnticipationsToReportRow{}
	for rows.Next() {
		var i AnticipationsToReportRow
		if err := rows.Scan(
			&i.AnticipationID,
			&i.UnitID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const changeUnitValue = `-- name: ChangeUnitValue :exec
UPDATE receivables.units
SET value = value + $1, anticipated = anticipated + $2,
    constituted_on = greatest(constituted_on, $3), version = version + 1, register_retry_at = NULL, updated_at = $4
WHERE id = $5
`

type ChangeUnitValueParams struct {
	Delta            int64
	AnticipatedDelta int64
	ConstitutedOn    pgtype.Date
	Now              pgtype.Timestamptz
	ID               string
}

// Any change is a new version the registry must take.
func (q *Queries) ChangeUnitValue(ctx context.Context, arg ChangeUnitValueParams) error {
	_, err := q.db.Exec(ctx, changeUnitValue,
		arg.Delta,
		arg.AnticipatedDelta,
		arg.ConstitutedOn,
		arg.Now,
		arg.ID,
	)
	return err
}

const countOptIns = `-- name: CountOptIns :one
SELECT count(*) FROM receivables.opt_ins WHERE merchant_id = $1 AND livemode = $2 AND financier <> $3
`

type CountOptInsParams struct {
	MerchantID string
	Livemode   bool
	Financier  string
}

// Others than financier: changing an existing one never counts against the cap.
func (q *Queries) CountOptIns(ctx context.Context, arg CountOptInsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOptIns, arg.MerchantID, arg.Livemode, arg.Financier)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const debtors = `-- name: Debtors :many
SELECT d.recipient_id, d.livemode, d.currency, d.owed, d.key FROM (
    SELECT recipient_id, livemode, currency, (-sum(amount))::bigint AS owed,
           (recipient_id || '/' || livemode::text || '/' || currency)::text AS key
    FROM receivables.movements
    WHERE bucket = 'available' AND recipient_id <> ''
    GROUP BY recipient_id, livemode, currency
    HAVING sum(amount) < 0
) d
WHERE d.key > $1::text
ORDER BY d.key
LIMIT 200
`

type DebtorsRow struct {
	RecipientID string
	Livemode    bool
	Currency    string
	Owed        int64
	Key         string
}

// Recipients whose available balance is below zero, and by how much: what disputes and
// refunds took that they did not have. A page follows the last one's key.
func (q *Queries) Debtors(ctx context.Context, after string) ([]DebtorsRow, error) {
	rows, err := q.db.Query(ctx, debtors, after)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DebtorsRow{}
	for rows.Next() {
		var i DebtorsRow
		if err := rows.Scan(
			&i.RecipientID,
			&i.Livemode,
			&i.Currency,
			&i.Owed,
			&i.Key,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnticipation = `-- name: GetAnticipation :one
SELECT id, merchant_id, livemode, recipient_id, currency, amount, price, monthly_rate, automatic, ledger_txn, created_at FROM receivables.anticipations WHERE id = $1 AND merchant_id = $2 AND livemode = $3
`

type GetAnticipationParams struct {
	ID         string
	MerchantID string
	Livemode   bool
}

func (q *Queries) GetAnticipation(ctx context.Context, arg GetAnticipationParams) (ReceivablesAnticipation, error) {
	row := q.db.QueryRow(ctx, getAnticipation, arg.ID, arg.MerchantID, arg.Livemode)
	var i ReceivablesAnticipation
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.RecipientID,
		&i.Currency,
		&i.Amount,
		&i.Price,
		&i.MonthlyRate,
		&i.Automatic,
		&i.LedgerTxn,
		&i.CreatedAt,
	)
	return i, err
}

const getGrade = `-- name: GetGrade :one
SELECT livemode, date, entries, total, credited, status, error, ledger_txn, created_at, updated_at FROM receivables.grades WHERE livemode = $1 AND date = $2
`

type GetGradeParams struct {
	Livemode bool
	Date     pgtype.Date
}

func (q *Queries) GetGrade(ctx context.Context, arg GetGradeParams) (ReceivablesGrade, error) {
	row := q.db.QueryRow(ctx, getGrade, arg.Livemode, arg.Date)
	var i ReceivablesGrade
	err := row.Scan(
		&i.Livemode,
		&i.Date,
		&i.Entries,
		&i.Total,
		&i.Credited,
		&i.Status,
		&i.Error,
		&i.LedgerTxn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnit = `-- name: GetUnit :one
SELECT id, merchant_id, livemode, arrangement, settlement_date, value, blocked, currency, constituted_on, version, registered_version, registered_at, register_error, register_retry_at, settled_on, settled_amount, payments, created_at, updated_at, recipient_id, anticipated, grade_date FROM receivables.units WHERE id = $1
`

func (q *Queries) GetUnit(ctx context.Context, id string) (ReceivablesUnit, error) {
	row := q.db.QueryRow(ctx, getUnit, id)
	var i ReceivablesUnit
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Arrangement,
		&i.SettlementDate,
		&i.Value,
		&i.Blocked,
		&i.Currency,
		&i.ConstitutedOn,
		&i.Version,
		&i.RegisteredVersion,
		&i.RegisteredAt,
		&i.RegisterError,
		&i.RegisterRetryAt,
		&i.SettledOn,
		&i.SettledAmount,
		&i.Payments,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecipientID,
		&i.Anticipated,
		&i.GradeDate,
	)
	return i, err
}

const insertAnticipation = `-- name: InsertAnticipation :exec
INSERT INTO receivables.anticipations (id, merchant_id, livemode, recipient_id, currency, amount, price, monthly_rate, automatic, ledger_txn, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertAnticipationParams struct {
	ID          string
	MerchantID  string
	Livemode    bool
	RecipientID string
	Currency    string
	Amount      int64
	Price       int64
	MonthlyRate string
	Automatic   bool
	LedgerTxn   string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertAnticipation(ctx context.Context, arg InsertAnticipationParams) error {
	_, err := q.db.Exec(ctx, insertAnticipation,
		arg.ID,
		arg.MerchantID,
		arg.Livemode,
		arg.RecipientID,
		arg.Currency,
		arg.Amount,
		arg.Price,
		arg.MonthlyRate,
		arg.Automatic,
		arg.LedgerTxn,
		arg.CreatedAt,
	)
	return err
}

const insertAnticipationUnit = `-- name: InsertAnticipationUnit :exec
INSERT INTO receivables.anticipation_units (anticipation_id, unit_id, amount, price, days, contract)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAnticipationUnitParams struct {
	AnticipationID string
	UnitID         string
	Amount         int64
	Price          int64
	Days           int32
	Contract       string
}

func (q *Queries) InsertAnticipationUnit(ctx context.Context, arg InsertAnticipationUnitParams) error {
	_, err := q.db.Exec(ctx, insertAnticipationUnit,
		arg.AnticipationID,
		arg.UnitID,
		arg.Amount,
		arg.Price,
		arg.Days,
		arg.Contract,
	)
	return err
}

const insertDispute = `-- name: InsertDispute :execrows
INSERT INTO receivables.disputes (reference, recipient_id, livemode, currency, amount, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (reference) DO NOTHING
`

type InsertDisputeParams struct {
	Reference   string
	RecipientID string
	Livemode    bool
	Currency    string
	Amount      int64
	Now         pgtype.Timestamptz
}

func (q *Queries) InsertDispute(ctx context.Context, arg InsertDisputeParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDispute,
		arg.Reference,
		arg.RecipientID,
		arg.Livemode,
		arg.Currency,
		arg.Amount,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertGrade = `-- name: InsertGrade :exec
INSERT INTO receivables.grades (livemode, date, entries, total, credited, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, 'built', $6, $6)
`

type InsertGradeParams struct {
	Livemode bool
	Date     pgtype.Date
	Entries  []byte
	Total    int64
	Credited int64
	Now      pgtype.Timestamptz
}

func (q *Queries) InsertGrade(ctx context.Context, arg InsertGradeParams) error {
	_, err := q.db.Exec(ctx, insertGrade,
		arg.Livemode,
		arg.Date,
		arg.Entries,
		arg.Total,
		arg.Credited,
		arg.Now,
	)
	return err
}

const insertInstallment = `-- name: InsertInstallment :exec
INSERT INTO receivables.installments (attempt_id, recipient_id, number, payment_intent, unit_id, gross, fee, net)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertInstallmentParams struct {
	AttemptID     string
	RecipientID   string
	Number        int32
	PaymentIntent string
	UnitID        string
	Gross         int64
	Fee           int64
	Net           int64
}

func (q *Queries) InsertInstallment(ctx context.Context, arg InsertInstallmentParams) error {
	_, err := q.db.Exec(ctx, insertInstallment,
		arg.AttemptID,
		arg.RecipientID,
		arg.Number,
		arg.PaymentIntent,
		arg.UnitID,
		arg.Gross,
		arg.Fee,
		arg.Net,
	)
	return err
}

const insertLedgerAccount = `-- name: InsertLedgerAccount :exec
INSERT INTO receivables.ledger_accounts (recipient_id, livemode, currency, role, account_id)
VALUES ($1, $2, $3, $4, $5)
`

type InsertLedgerAccountParams struct {
	RecipientID string
	Livemode    bool
	Currency    string
	Role        string
	AccountID   string
}

func (q *Queries) InsertLedgerAccount(ctx context.Context, arg InsertLedgerAccountParams) error {
	_, err := q.db.Exec(ctx, insertLedgerAccount,
		arg.RecipientID,
		arg.Livemode,
		arg.Currency,
		arg.Role,
		arg.AccountID,
	)
	return err
}

const insertMovement = `-- name: InsertMovement :exec
INSERT INTO receivables.movements (recipient_id, livemode, currency, bucket, kind, amount, reference, at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertMovementParams struct {
	RecipientID string
	Livemode    bool
	Currency    string
	Bucket      string
	Kind        string
	Amount      int64
	Reference   string
	At          pgtype.Timestamptz
}

func (q *Queries) InsertMovement(ctx context.Context, arg InsertMovementParams) error {
	_, err := q.db.Exec(ctx, insertMovement,
		arg.RecipientID,
		arg.Livemode,
		arg.Currency,
		arg.Bucket,
		arg.Kind,
		arg.Amount,
		arg.Reference,
		arg.At,
	)
	return err
}

const insertQuote = `-- name: InsertQuote :exec
INSERT INTO receivables.anticipation_quotes (id, merchant_id, livemode, recipient_id, monthly_rate, units, amount, price, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertQuoteParams struct {
	ID          string
	MerchantID  string
	Livemode    bool
	RecipientID string
	MonthlyRate string
	Units       []byte
	Amount      int64
	Price       int64
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertQuote(ctx context.Context, arg InsertQuoteParams) error {
	_, err := q.db.Exec(ctx, insertQuote,
		arg.ID,
		arg.MerchantID,
		arg.Livemode,
		arg.RecipientID,
		arg.MonthlyRate,
		arg.Units,
		arg.Amount,
		arg.Price,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const insertReconciliation = `-- name: InsertReconciliation :exec
INSERT INTO receivables.reconciliations (livemode, kind, ran_on, ran_at, divergences)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (livemode, kind, ran_on) DO UPDATE SET ran_at = excluded.ran_at, divergences = excluded.divergences
`

type InsertReconciliationParams struct {
	Livemode    bool
	Kind        string
	RanOn       pgtype.Date
	RanAt       pgtype.Timestamptz
	Divergences int32
}

func (q *Queries) InsertReconciliation(ctx context.Context, arg InsertReconciliationParams) error {
	_, err := q.db.Exec(ctx, insertReconciliation,
		arg.Livemode,
		arg.Kind,
		arg.RanOn,
		arg.RanAt,
		arg.Divergences,
	)
	return err
}

const insertRecovery = `-- name: InsertRecovery :exec
INSERT INTO receivables.recoveries (recipient_id, unit_id, amount, from_free, from_contracts, at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertRecoveryParams struct {
	RecipientID   string
	UnitID        string
	Amount        int64
	FromFree      int64
	FromContracts []byte
	At            pgtype.Timestamptz
}

func (q *Queries) InsertRecovery(ctx context.Context, arg InsertRecoveryParams) error {
	_, err := q.db.Exec(ctx, insertRecovery,
		arg.RecipientID,
		arg.UnitID,
		arg.Amount,
		arg.FromFree,
		arg.FromContracts,
		arg.At,
	)
	return err
}

const insertSnapshot = `-- name: InsertSnapshot :exec
INSERT INTO receivables.effect_snapshots (unit_id, observed_at, commitments) VALUES ($1, $2, $3)
`

type InsertSnapshotParams struct {
	UnitID      string
	ObservedAt  pgtype.Timestamptz
	Commitments []byte
}

func (q *Queries) InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertSnapshot, arg.UnitID, arg.ObservedAt, arg.Commitments)
	return err
}

const insertSplitLine = `-- name: InsertSplitLine :exec
INSERT INTO receivables.split_lines (attempt_id, payment_intent, recipient_id, type, amount, liable, ledger_txn)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertSplitLineParams struct {
	AttemptID     string
	PaymentIntent string
	RecipientID   string
	Type          string
	Amount        int64
	Liable        bool
	LedgerTxn     string
}

func (q *Queries) InsertSplitLine(ctx context.Context, arg InsertSplitLineParams) error {
	_, err := q.db.Exec(ctx, insertSplitLine,
		arg.AttemptID,
		arg.PaymentIntent,
		arg.RecipientID,
		arg.Type,
		arg.Amount,
		arg.Liable,
		arg.LedgerTxn,
	)
	return err
}

const insertUnit = `-- name: InsertUnit :exec
INSERT INTO receivables.units (id, merchant_id, recipient_id, livemode, arrangement, settlement_date, value, currency, constituted_on, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, 0, $7, $8, $9, $9)
ON CONFLICT (recipient_id, livemode, arrangement, settlement_date) DO NOTHING
`

type InsertUnitParams struct {
	ID             string
	MerchantID     string
	RecipientID    string
	Livemode       bool
	Arrangement    string
	SettlementDate pgtype.Date
	Currency       string
	ConstitutedOn  pgtype.Date
	Now            pgtype.Timestamptz
}

func (q *Queries) InsertUnit(ctx context.Context, arg InsertUnitParams) error {
	_, err := q.db.Exec(ctx, insertUnit,
		arg.ID,
		arg.MerchantID,
		arg.RecipientID,
		arg.Livemode,
		arg.Arrangement,
		arg.SettlementDate,
		arg.Currency,
		arg.ConstitutedOn,
		arg.Now,
	)
	return err
}

const insertUnitEvent = `-- name: InsertUnitEvent :exec
INSERT INTO receivables.unit_events (unit_id, at, kind, amount, reference) VALUES ($1, $2, $3, $4, $5)
`

type InsertUnitEventParams struct {
	UnitID    string
	At        pgtype.Timestamptz
	Kind      string
	Amount    int64
	Reference string
}

func (q *Queries) InsertUnitEvent(ctx context.Context, arg InsertUnitEventParams) error {
	_, err := q.db.Exec(ctx, insertUnitEvent,
		arg.UnitID,
		arg.At,
		arg.Kind,
		arg.Amount,
		arg.Reference,
	)
	return err
}

const installmentTotals = `-- name: InstallmentTotals :many
SELECT u.id, u.value, coalesce(sum(i.net - i.reduced), 0)::bigint AS from_installments
FROM receivables.units u LEFT JOIN receivables.installments i ON i.unit_id = u.id
GROUP BY u.id, u.value
`

type InstallmentTotalsRow struct {
	ID               string
	Value            int64
	FromInstallments int64
}

// For the check: each unit's value is what its installments constituted, less reductions.
func (q *Queries) InstallmentTotals(ctx context.Context) ([]InstallmentTotalsRow, error) {
	rows, err := q.db.Query(ctx, installmentTotals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstallmentTotalsRow{}
	for rows.Next() {
		var i InstallmentTotalsRow
		if err := rows.Scan(&i.ID, &i.Value, &i.FromInstallments); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const installmentsOfIntent = `-- name: InstallmentsOfIntent :many
SELECT i.attempt_id, i.number, i.payment_intent, i.unit_id, i.gross, i.fee, i.net, i.reduced, i.recipient_id, i.fee_reduced, (u.settled_on IS NOT NULL)::boolean AS unit_settled
FROM receivables.installments i JOIN receivables.units u ON u.id = i.unit_id
WHERE i.payment_intent = $1
ORDER BY i.recipient_id, i.number
FOR UPDATE OF i, u
`

type InstallmentsOfIntentRow struct {
	AttemptID     string
	Number        int32
	PaymentIntent string
	UnitID        string
	Gross         int64
	Fee           int64
	Net           int64
	Reduced       int64
	RecipientID   string
	FeeReduced    int64
	UnitSettled   bool
}

func (q *Queries) InstallmentsOfIntent(ctx context.Context, paymentIntent string) ([]InstallmentsOfIntentRow, error) {
	rows, err := q.db.Query(ctx, installmentsOfIntent, paymentIntent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstallmentsOfIntentRow{}
	for rows.Next() {
		var i InstallmentsOfIntentRow
		if err := rows.Scan(
			&i.AttemptID,
			&i.Number,
			&i.PaymentIntent,
			&i.UnitID,
			&i.Gross,
			&i.Fee,
			&i.Net,
			&i.Reduced,
			&i.RecipientID,
			&i.FeeReduced,
			&i.UnitSettled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const installmentsOfUnit = `-- name: InstallmentsOfUnit :many
SELECT attempt_id, number, payment_intent, unit_id, gross, fee, net, reduced, recipient_id, fee_reduced FROM receivables.installments WHERE unit_id = $1 ORDER BY attempt_id, recipient_id, number FOR UPDATE
`

func (q *Queries) InstallmentsOfUnit(ctx context.Context, unitID string) ([]ReceivablesInstallment, error) {
	rows, err := q.db.Query(ctx, installmentsOfUnit, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceivablesInstallment{}
	for rows.Next() {
		var i ReceivablesInstallment
		if err := rows.Scan(
			&i.AttemptID,
			&i.Number,
			&i.PaymentIntent,
			&i.UnitID,
			&i.Gross,
			&i.Fee,
			&i.Net,
			&i.Reduced,
			&i.RecipientID,
			&i.FeeReduced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lastReconciliation = `-- name: LastReconciliation :one
SELECT coalesce(max(ran_on), '0001-01-01'::date)::date FROM receivables.reconciliations WHERE livemode = $1 AND kind = $2
`

type LastReconciliationParams struct {
	Livemode bool
	Kind     string
}

func (q *Queries) LastReconciliation(ctx context.Context, arg LastReconciliationParams) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, lastReconciliation, arg.Livemode, arg.Kind)
	var column_1 pgtype.Date
	err := row.Scan(&column_1)
	return column_1, err
}

const latestSnapshot = `-- name: LatestSnapshot :one
SELECT commitments FROM receivables.effect_snapshots
WHERE unit_id = $1 AND observed_at <= $2
ORDER BY observed_at DESC, id DESC LIMIT 1
`

type LatestSnapshotParams struct {
	UnitID string
	At     pgtype.Timestamptz
}

func (q *Queries) LatestSnapshot(ctx context.Context, arg LatestSnapshotParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, latestSnapshot, arg.UnitID, arg.At)
	var commitments []byte
	err := row.Scan(&commitments)
	return commitments, err
}

const latestSnapshots = `-- name: LatestSnapshots :many
SELECT DISTINCT ON (es.unit_id) es.unit_id, es.commitments
FROM receivables.effect_snapshots es JOIN receivables.units u ON u.id = es.unit_id
WHERE u.livemode = $1 AND u.settled_on IS NULL
ORDER BY es.unit_id, es.observed_at DESC, es.id DESC
`

type LatestSnapshotsRow struct {
	UnitID      string
	Commitments []byte
}

// What was last seen committed on each unsettled unit of a mode.
func (q *Queries) LatestSnapshots(ctx context.Context, livemode bool) ([]LatestSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, latestSnapshots, livemode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestSnapshotsRow{}
	for rows.Next() {
		var i LatestSnapshotsRow
		if err := rows.Scan(&i.UnitID, &i.Commitments); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ledgerAccounts = `-- name: LedgerAccounts :many
SELECT role, account_id FROM receivables.ledger_accounts
WHERE recipient_id = $1 AND livemode = $2 AND currency = $3
`

type LedgerAccountsParams struct {
	RecipientID string
	Livemode    bool
	Currency    string
}

type LedgerAccountsRow struct {
	Role      string
	AccountID string
}

func (q *Queries) LedgerAccounts(ctx context.Context, arg LedgerAccountsParams) ([]LedgerAccountsRow, error) {
	rows, err := q.db.Query(ctx, ledgerAccounts, arg.RecipientID, arg.Livemode, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerAccountsRow{}
	for rows.Next() {
		var i LedgerAccountsRow
		if err := rows.Scan(&i.Role, &i.AccountID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccountCreation = `-- name: LockAccountCreation :exec
SELECT pg_advisory_xact_lock(hashtext('receivables/accounts/' || $1::text))
`

func (q *Queries) LockAccountCreation(ctx context.Context, scope string) error {
	_, err := q.db.Exec(ctx, lockAccountCreation, scope)
	return err
}

const lockDispute = `-- name: LockDispute :one
SELECT reference, recipient_id, livemode, currency, amount, reinstated, created_at FROM receivables.disputes WHERE reference = $1 FOR UPDATE
`

func (q *Queries) LockDispute(ctx context.Context, reference string) (ReceivablesDispute, error) {
	row := q.db.QueryRow(ctx, lockDispute, reference)
	var i ReceivablesDispute
	err := row.Scan(
		&i.Reference,
		&i.RecipientID,
		&i.Livemode,
		&i.Currency,
		&i.Amount,
		&i.Reinstated,
		&i.CreatedAt,
	)
	return i, err
}

const lockGrade = `-- name: LockGrade :one
SELECT livemode, date, entries, total, credited, status, error, ledger_txn, created_at, updated_at FROM receivables.grades WHERE livemode = $1 AND date = $2 FOR UPDATE
`

type LockGradeParams struct {
	Livemode bool
	Date     pgtype.Date
}

func (q *Queries) LockGrade(ctx context.Context, arg LockGradeParams) (ReceivablesGrade, error) {
	row := q.db.QueryRow(ctx, lockGrade, arg.Livemode, arg.Date)
	var i ReceivablesGrade
	err := row.Scan(
		&i.Livemode,
		&i.Date,
		&i.Entries,
		&i.Total,
		&i.Credited,
		&i.Status,
		&i.Error,
		&i.LedgerTxn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockQuote = `-- name: LockQuote :one
SELECT id, merchant_id, livemode, recipient_id, monthly_rate, units, amount, price, expires_at, anticipation, created_at FROM receivables.anticipation_quotes WHERE id = $1 AND merchant_id = $2 AND livemode = $3 FOR UPDATE
`

type LockQuoteParams struct {
	ID         string
	MerchantID string
	Livemode   bool
}

func (q *Queries) LockQuote(ctx context.Context, arg LockQuoteParams) (ReceivablesAnticipationQuote, error) {
	row := q.db.QueryRow(ctx, lockQuote, arg.ID, arg.MerchantID, arg.Livemode)
	var i ReceivablesAnticipationQuote
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.RecipientID,
		&i.MonthlyRate,
		&i.Units,
		&i.Amount,
		&i.Price,
		&i.ExpiresAt,
		&i.Anticipation,
		&i.CreatedAt,
	)
	return i, err
}

const lockUnit = `-- name: LockUnit :one
SELECT id, merchant_id, livemode, arrangement, settlement_date, value, blocked, currency, constituted_on, version, registered_version, registered_at, register_error, register_retry_at, settled_on, settled_amount, payments, created_at, updated_at, recipient_id, anticipated, grade_date FROM receivables.units
WHERE recipient_id = $1 AND livemode = $2 AND arrangement = $3 AND settlement_date = $4
FOR UPDATE
`

type LockUnitParams struct {
	RecipientID    string
	Livemode       bool
	Arrangement    string
	SettlementDate pgtype.Date
}

func (q *Queries) LockUnit(ctx context.Context, arg LockUnitParams) (ReceivablesUnit, error) {
	row := q.db.QueryRow(ctx, lockUnit,
		arg.RecipientID,
		arg.Livemode,
		arg.Arrangement,
		arg.SettlementDate,
	)
	var i ReceivablesUnit
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Arrangement,
		&i.SettlementDate,
		&i.Value,
		&i.Blocked,
		&i.Currency,
		&i.ConstitutedOn,
		&i.Version,
		&i.RegisteredVersion,
		&i.RegisteredAt,
		&i.RegisterError,
		&i.RegisterRetryAt,
		&i.SettledOn,
		&i.SettledAmount,
		&i.Payments,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecipientID,
		&i.Anticipated,
		&i.GradeDate,
	)
	return i, err
}

const lockUnitByID = `-- name: LockUnitByID :one
SELECT id, merchant_id, livemode, arrangement, settlement_date, value, blocked, currency, constituted_on, version, registered_version, registered_at, register_error, register_retry_at, settled_on, settled_amount, payments, created_at, updated_at, recipient_id, anticipated, grade_date FROM receivables.units WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockUnitByID(ctx context.Context, id string) (ReceivablesUnit, error) {
	row := q.db.QueryRow(ctx, lockUnitByID, id)
	var i ReceivablesUnit
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Arrangement,
		&i.SettlementDate,
		&i.Value,
		&i.Blocked,
		&i.Currency,
		&i.ConstitutedOn,
		&i.Version,
		&i.RegisteredVersion,
		&i.RegisteredAt,
		&i.RegisterError,
		&i.RegisterRetryAt,
		&i.SettledOn,
		&i.SettledAmount,
		&i.Payments,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecipientID,
		&i.Anticipated,
		&i.GradeDate,
	)
	return i, err
}

const markDisputeReinstated = `-- name: MarkDisputeReinstated :exec
UPDATE receivables.disputes SET reinstated = true WHERE reference = $1
`

func (q *Queries) MarkDisputeReinstated(ctx context.Context, reference string) error {
	_, err := q.db.Exec(ctx, markDisputeReinstated, reference)
	return err
}

const markGraded = `-- name: MarkGraded :exec
UPDATE receivables.units SET grade_date = $1 WHERE id = ANY($2::text[])
`

type MarkGradedParams struct {
	Day   pgtype.Date
	Units []string
}

func (q *Queries) MarkGraded(ctx context.Context, arg MarkGradedParams) error {
	_, err := q.db.Exec(ctx, markGraded, arg.Day, arg.Units)
	return err
}

const markOptInError = `-- name: MarkOptInError :exec
UPDATE receivables.opt_ins SET sync_error = $1, retry_at = $2
WHERE merchant_id = $3 AND livemode = $4 AND financier = $5
`

type MarkOptInErrorParams struct {
	Error      string
	RetryAt    pgtype.Timestamptz
	MerchantID string
	Livemode   bool
	Financier  string
}

func (q *Queries) MarkOptInError(ctx context.Context, arg MarkOptInErrorParams) error {
	_, err := q.db.Exec(ctx, markOptInError,
		arg.Error,
		arg.RetryAt,
		arg.MerchantID,
		arg.Livemode,
		arg.Financier,
	)
	return err
}

const markOptInSynced = `-- name: MarkOptInSynced :exec
UPDATE receivables.opt_ins SET synced = true, sync_error = '', retry_at = NULL
WHERE merchant_id = $1 AND livemode = $2 AND financier = $3 AND updated_at = $4
`

type MarkOptInSyncedParams struct {
	MerchantID string
	Livemode   bool
	Financier  string
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) MarkOptInSynced(ctx context.Context, arg MarkOptInSyncedParams) error {
	_, err := q.db.Exec(ctx, markOptInSynced,
		arg.MerchantID,
		arg.Livemode,
		arg.Financier,
		arg.UpdatedAt,
	)
	return err
}

const markRegisterError = `-- name: MarkRegisterError :exec
UPDATE receivables.units SET register_error = $1, register_retry_at = $2 WHERE id = $3
`

type MarkRegisterErrorParams struct {
	Error   string
	RetryAt pgtype.Timestamptz
	ID      string
}

func (q *Queries) MarkRegisterError(ctx context.Context, arg MarkRegisterErrorParams) error {
	_, err := q.db.Exec(ctx, markRegisterError, arg.Error, arg.RetryAt, arg.ID)
	return err
}

const markRegistered = `-- name: MarkRegistered :exec
UPDATE receivables.units
SET registered_version = greatest(registered_version, $1), registered_at = $2, register_error = ''
WHERE id = $3
`

type MarkRegisteredParams struct {
	Version int32
	Now     pgtype.Timestamptz
	ID      string
}

func (q *Queries) MarkRegistered(ctx context.Context, arg MarkRegisteredParams) error {
	_, err := q.db.Exec(ctx, markRegistered, arg.Version, arg.Now, arg.ID)
	return err
}

const markReported = `-- name: MarkReported :exec
UPDATE receivables.anticipation_units SET reported_at = $1
WHERE anticipation_id = $2 AND unit_id = $3
`

type MarkReportedParams struct {
	Now            pgtype.Timestamptz
	AnticipationID string
	UnitID         string
}

func (q *Queries) MarkReported(ctx context.Context, arg MarkReportedParams) error {
	_, err := q.db.Exec(ctx, markReported, arg.Now, arg.AnticipationID, arg.UnitID)
	return err
}

const markSettled = `-- name: MarkSettled :exec
UPDATE receivables.units
SET settled_on = $1, settled_amount = $2, payments = $3, updated_at = $4
WHERE id = $5 AND settled_on IS NULL
`

type MarkSettledParams struct {
	SettledOn pgtype.Date
	Amount    pgtype.Int8
	Payments  []byte
	Now       pgtype.Timestamptz
	ID        string
}

func (q *Queries) MarkSettled(ctx context.Context, arg MarkSettledParams) error {
	_, err := q.db.Exec(ctx, markSettled,
		arg.SettledOn,
		arg.Amount,
		arg.Payments,
		arg.Now,
		arg.ID,
	)
	return err
}

const movementTotals = `-- name: MovementTotals :many
SELECT recipient_id, livemode, currency, bucket, sum(amount)::bigint AS total
FROM receivables.movements GROUP BY recipient_id, livemode, currency, bucket
`

type MovementTotalsRow struct {
	RecipientID string
	Livemode    bool
	Currency    string
	Bucket      string
	Total       int64
}

func (q *Queries) MovementTotals(ctx context.Context) ([]MovementTotalsRow, error) {
	rows, err := q.db.Query(ctx, movementTotals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MovementTotalsRow{}
	for rows.Next() {
		var i MovementTotalsRow
		if err := rows.Scan(
			&i.RecipientID,
			&i.Livemode,
			&i.Currency,
			&i.Bucket,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openDivergence = `-- name: OpenDivergence :exec
INSERT INTO receivables.divergences (livemode, kind, subject, detail, found_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (livemode, kind, subject) WHERE resolved_at IS NULL DO UPDATE SET detail = excluded.detail
`

type OpenDivergenceParams struct {
	Livemode bool
	Kind     string
	Subject  string
	Detail   string
	FoundAt  pgtype.Timestamptz
}

func (q *Queries) OpenDivergence(ctx context.Context, arg OpenDivergenceParams) error {
	_, err := q.db.Exec(ctx, openDivergence,
		arg.Livemode,
		arg.Kind,
		arg.Subject,
		arg.Detail,
		arg.FoundAt,
	)
	return err
}

const openDivergences = `-- name: OpenDivergences :many
SELECT id, livemode, kind, subject, detail, found_at, resolved_at FROM receivables.divergences WHERE resolved_at IS NULL ORDER BY found_at, id
`

func (q *Queries) OpenDivergences(ctx context.Context) ([]ReceivablesDivergence, error) {
	rows, err := q.db.Query(ctx, openDivergences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceivablesDivergence{}
	for rows.Next() {
		var i ReceivablesDivergence
		if err := rows.Scan(
			&i.ID,
			&i.Livemode,
			&i.Kind,
			&i.Subject,
			&i.Detail,
			&i.FoundAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openGrades = `-- name: OpenGrades :many
SELECT livemode, date, entries, total, credited, status, error, ledger_txn, created_at, updated_at FROM receivables.grades WHERE livemode = $1 AND status IN ('built', 'submitted') ORDER BY date
`

func (q *Queries) OpenGrades(ctx context.Context, livemode bool) ([]ReceivablesGrade, error) {
	rows, err := q.db.Query(ctx, openGrades, livemode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceivablesGrade{}
	for rows.Next() {
		var i ReceivablesGrade
		if err := rows.Scan(
			&i.Livemode,
			&i.Date,
			&i.Entries,
			&i.Total,
			&i.Credited,
			&i.Status,
			&i.Error,
			&i.LedgerTxn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const optInsOf = `-- name: OptInsOf :many
SELECT merchant_id, livemode, financier, active, synced, sync_error, retry_at, updated_at FROM receivables.opt_ins WHERE merchant_id = $1 AND livemode = $2 ORDER BY financier
`

type OptInsOfParams struct {
	MerchantID string
	Livemode   bool
}

func (q *Queries) OptInsOf(ctx context.Context, arg OptInsOfParams) ([]ReceivablesOptIn, error) {
	rows, err := q.db.Query(ctx, optInsOf, arg.MerchantID, arg.Livemode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceivablesOptIn{}
	for rows.Next() {
		var i ReceivablesOptIn
		if err := rows.Scan(
			&i.MerchantID,
			&i.Livemode,
			&i.Financier,
			&i.Active,
			&i.Synced,
			&i.SyncError,
			&i.RetryAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const optInsToSync = `-- name: OptInsToSync :many
SELECT merchant_id, livemode, financier, active, synced, sync_error, retry_at, updated_at FROM receivables.opt_ins
WHERE livemode = $1 AND NOT synced AND (retry_at IS NULL OR retry_at <= $2)
ORDER BY updated_at LIMIT 100
`

type OptInsToSyncParams struct {
	Livemode bool
	Now      pgtype.Timestamptz
}

func (q *Queries) OptInsToSync(ctx context.Context, arg OptInsToSyncParams) ([]ReceivablesOptIn, error) {
	rows, err := q.db.Query(ctx, optInsToSync, arg.Livemode, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceivablesOptIn{}
	for rows.Next() {
		var i ReceivablesOptIn
		if err := rows.Scan(
			&i.MerchantID,
			&i.Livemode,
			&i.Financier,
			&i.Active,
			&i.Synced,
			&i.SyncError,
			&i.RetryAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const peekAnticipableUnits = `-- name: PeekAnticipableUnits :many
SELECT id, merchant_id, livemode, arrangement, settlement_date, value, blocked, currency, constituted_on, version, registered_version, registered_at, register_error, register_retry_at, settled_on, settled_amount, payments, created_at, updated_at, recipient_id, anticipated, grade_date FROM receivables.units
WHERE recipient_id = $1 AND livemode = $2 AND settled_on IS NULL AND settlement_date > $3
  AND value > anticipated AND registered_version = version
  AND (cardinality($4::text[]) = 0 OR id = ANY($4::text[]))
  AND created_at <= $5
ORDER BY settlement_date, id
LIMIT 400
`

type PeekAnticipableUnitsParams struct {
	RecipientID       string
	Livemode          bool
	Today             pgtype.Date
	Ids               []string
	ConstitutedBefore pgtype.Timestamptz
}

// The same, unlocked: for a quote, which changes nothing.
// A recipient's units Jupiter can buy: registered as they are, not settled, settling
// after today, with something not yet bought.
func (q *Queries) PeekAnticipableUnits(ctx context.Context, arg PeekAnticipableUnitsParams) ([]ReceivablesUnit, error) {
	rows, err := q.db.Query(ctx, peekAnticipableUnits,
		arg.RecipientID,
		arg.Livemode,
		arg.Today,
		arg.Ids,
		arg.ConstitutedBefore,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceivablesUnit{}
	for rows.Next() {
		var i ReceivablesUnit
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Livemode,
			&i.Arrangement,
			&i.SettlementDate,
			&i.Value,
			&i.Blocked,
			&i.Currency,
			&i.ConstitutedOn,
			&i.Version,
			&i.RegisteredVersion,
			&i.RegisteredAt,
			&i.RegisterError,
			&i.RegisterRetryAt,
			&i.SettledOn,
			&i.SettledAmount,
			&i.Payments,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecipientID,
			&i.Anticipated,
			&i.GradeDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingByDate = `-- name: PendingByDate :many
SELECT settlement_date, sum(value - anticipated)::bigint AS amount
FROM receivables.units
WHERE recipient_id = $1 AND livemode = $2 AND currency = $3 AND settled_on IS NULL AND value > anticipated
GROUP BY settlement_date ORDER BY settlement_date
LIMIT 400
`

type PendingByDateParams struct {
	RecipientID string
	Livemode    bool
	Currency    string
}

type PendingByDateRow struct {
	SettlementDate pgtype.Date
	Amount         int64
}

func (q *Queries) PendingByDate(ctx context.Context, arg PendingByDateParams) ([]PendingByDateRow, error) {
	rows, err := q.db.Query(ctx, pendingByDate, arg.RecipientID, arg.Livemode, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingByDateRow{}
	for rows.Next() {
		var i PendingByDateRow
		if err := rows.Scan(&i.SettlementDate, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingFromUnits = `-- name: PendingFromUnits :many
SELECT recipient_id, livemode, currency, sum(value - anticipated)::bigint AS pending
FROM receivables.units WHERE settled_on IS NULL AND recipient_id <> ''
GROUP BY recipient_id, livemode, currency
`

type PendingFromUnitsRow struct {
	RecipientID string
	Livemode    bool
	Currency    string
	Pending     int64
}

// What each recipient's unsettled units hold that Jupiter did not buy.
func (q *Queries) PendingFromUnits(ctx context.Context) ([]PendingFromUnitsRow, error) {
	rows, err := q.db.Query(ctx, pendingFromUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingFromUnitsRow{}
	for rows.Next() {
		var i PendingFromUnitsRow
		if err := rows.Scan(
			&i.RecipientID,
			&i.Livemode,
			&i.Currency,
			&i.Pending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoverableUnits = `-- name: RecoverableUnits :many
SELECT id, merchant_id, livemode, arrangement, settlement_date, value, blocked, currency, constituted_on, version, registered_version, registered_at, register_error, register_retry_at, settled_on, settled_amount, payments, created_at, updated_at, recipient_id, anticipated, grade_date FROM receivables.units
WHERE recipient_id = $1 AND livemode = $2 AND currency = $3 AND settled_on IS NULL
  AND settlement_date > $4 AND value - anticipated - blocked > 0
  AND (NOT $5::boolean OR registered_version = version)
ORDER BY settlement_date, id
LIMIT 400
FOR UPDATE
`

type RecoverableUnitsParams struct {
	RecipientID string
	Livemode    bool
	Currency    string
	Today       pgtype.Date
	Registered  bool
}

// A recipient's units that can be reduced to recover what it owes, locked, nearest
// settlement first: unsettled, settling after today, with something not bought by
// Jupiter nor blocked, and, where a registry keeps them, registered as they are.
func (q *Queries) RecoverableUnits(ctx context.Context, arg RecoverableUnitsParams) ([]ReceivablesUnit, error) {
	rows, err := q.db.Query(ctx, recoverableUnits,
		arg.RecipientID,
		arg.Livemode,
		arg.Currency,
		arg.Today,
		arg.Registered,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceivablesUnit{}
	for rows.Next() {
		var i ReceivablesUnit
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Livemode,
			&i.Arrangement,
			&i.SettlementDate,
			&i.Value,
			&i.Blocked,
			&i.Currency,
			&i.ConstitutedOn,
			&i.Version,
			&i.RegisteredVersion,
			&i.RegisteredAt,
			&i.RegisterError,
			&i.RegisterRetryAt,
			&i.SettledOn,
			&i.SettledAmount,
			&i.Payments,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecipientID,
			&i.Anticipated,
			&i.GradeDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoveriesOf = `-- name: RecoveriesOf :many
SELECT id, recipient_id, unit_id, amount, from_free, from_contracts, at FROM receivables.recoveries WHERE recipient_id = $1 ORDER BY id
`

func (q *Queries) RecoveriesOf(ctx context.Context, recipientID string) ([]ReceivablesRecovery, error) {
	rows, err := q.db.Query(ctx, recoveriesOf, recipientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceivablesRecovery{}
	for rows.Next() {
		var i ReceivablesRecovery
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.UnitID,
			&i.Amount,
			&i.FromFree,
			&i.FromContracts,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reduceInstallment = `-- name: ReduceInstallment :exec
UPDATE receivables.installments SET reduced = reduced + $1
WHERE attempt_id = $2 AND recipient_id = $3 AND number = $4
`

type ReduceInstallmentParams struct {
	Amount      int64
	AttemptID   string
	RecipientID string
	Number      int32
}

func (q *Queries) ReduceInstallment(ctx context.Context, arg ReduceInstallmentParams) error {
	_, err := q.db.Exec(ctx, reduceInstallment,
		arg.Amount,
		arg.AttemptID,
		arg.RecipientID,
		arg.Number,
	)
	return err
}

const reduceInstallmentFee = `-- name: ReduceInstallmentFee :exec
UPDATE receivables.installments SET fee_reduced = fee_reduced + $1
WHERE attempt_id = $2 AND recipient_id = $3 AND number = $4
`

type ReduceInstallmentFeeParams struct {
	Amount      int64
	AttemptID   string
	RecipientID string
	Number      int32
}

func (q *Queries) ReduceInstallmentFee(ctx context.Context, arg ReduceInstallmentFeeParams) error {
	_, err := q.db.Exec(ctx, reduceInstallmentFee,
		arg.Amount,
		arg.AttemptID,
		arg.RecipientID,
		arg.Number,
	)
	return err
}

const reregister = `-- name: Reregister :exec
UPDATE receivables.units
SET registered_version = 0, register_retry_at = NULL, constituted_on = greatest(constituted_on, $1)
WHERE id = $2
`

type ReregisterParams struct {
	Today pgtype.Date
	ID    string
}

// The registry disagrees with what it was sent: send it again.
// The correction is due from the day it is found.
func (q *Queries) Reregister(ctx context.Context, arg ReregisterParams) error {
	_, err := q.db.Exec(ctx, reregister, arg.Today, arg.ID)
	return err
}

const resolveDivergences = `-- name: ResolveDivergences :exec
UPDATE receivables.divergences SET resolved_at = $1
WHERE livemode = $2 AND kind = $3 AND resolved_at IS NULL AND NOT (subject = ANY($4::text[]))
`

type ResolveDivergencesParams struct {
	Now      pgtype.Timestamptz
	Livemode bool
	Kind     string
	Still    []string
}

// Those of a kind a reconciliation no longer found.
func (q *Queries) ResolveDivergences(ctx context.Context, arg ResolveDivergencesParams) error {
	_, err := q.db.Exec(ctx, resolveDivergences,
		arg.Now,
		arg.Livemode,
		arg.Kind,
		arg.Still,
	)
	return err
}

const setGradeStatus = `-- name: SetGradeStatus :execrows
UPDATE receivables.grades SET status = $1, error = $2, ledger_txn = $3, updated_at = $4
WHERE livemode = $5 AND date = $6 AND status = $7
`

type SetGradeStatusParams struct {
	Status     string
	Error      string
	LedgerTxn  string
	Now        pgtype.Timestamptz
	Livemode   bool
	Date       pgtype.Date
	FromStatus string
}

// Moves a grade on from the status it was read in; none moves when another pass did.
func (q *Queries) SetGradeStatus(ctx context.Context, arg SetGradeStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setGradeStatus,
		arg.Status,
		arg.Error,
		arg.LedgerTxn,
		arg.Now,
		arg.Livemode,
		arg.Date,
		arg.FromStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setOptIn = `-- name: SetOptIn :exec
INSERT INTO receivables.opt_ins (merchant_id, livemode, financier, active, synced, updated_at)
VALUES ($1, $2, $3, $4, false, $5)
ON CONFLICT (merchant_id, livemode, financier) DO UPDATE
SET active = excluded.active, synced = false, sync_error = '', retry_at = NULL, updated_at = excluded.updated_at
`

type SetOptInParams struct {
	MerchantID string
	Livemode   bool
	Financier  string
	Active     bool
	Now        pgtype.Timestamptz
}

func (q *Queries) SetOptIn(ctx context.Context, arg SetOptInParams) error {
	_, err := q.db.Exec(ctx, setOptIn,
		arg.MerchantID,
		arg.Livemode,
		arg.Financier,
		arg.Active,
		arg.Now,
	)
	return err
}

const splitLinesOfIntent = `-- name: SplitLinesOfIntent :many
SELECT attempt_id, payment_intent, recipient_id, type, amount, liable, ledger_txn FROM receivables.split_lines WHERE payment_intent = $1 ORDER BY recipient_id, type
`

func (q *Queries) SplitLinesOfIntent(ctx context.Context, paymentIntent string) ([]ReceivablesSplitLine, error) {
	rows, err := q.db.Query(ctx, splitLinesOfIntent, paymentIntent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceivablesSplitLine{}
	for rows.Next() {
		var i ReceivablesSplitLine
		if err := rows.Scan(
			&i.AttemptID,
			&i.PaymentIntent,
			&i.RecipientID,
			&i.Type,
			&i.Amount,
			&i.Liable,
			&i.LedgerTxn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unitFees = `-- name: UnitFees :many
SELECT unit_id, sum(fee - fee_reduced)::bigint AS fee, sum(net - reduced)::bigint AS net
FROM receivables.installments
WHERE unit_id = ANY($1::text[])
GROUP BY unit_id
`

type UnitFeesRow struct {
	UnitID string
	Fee    int64
	Net    int64
}

// What the network still pays Jupiter in fees on each of some units, and what their
// installments hold net.
func (q *Queries) UnitFees(ctx context.Context, units []string) ([]UnitFeesRow, error) {
	rows, err := q.db.Query(ctx, unitFees, units)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnitFeesRow{}
	for rows.Next() {
		var i UnitFeesRow
		if err := rows.Scan(&i.UnitID, &i.Fee, &i.Net); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unitsDue = `-- name: UnitsDue :many
SELECT id FROM receivables.units
WHERE livemode = $1 AND settlement_date <= $2 AND settled_on IS NULL AND id > $3
ORDER BY id LIMIT 500
`

type UnitsDueParams struct {
	Livemode bool
	Day      pgtype.Date
	After    string
}

// A page of the units of a mode due by a day and not settled.
func (q *Queries) UnitsDue(ctx context.Context, arg UnitsDueParams) ([]string, error) {
	rows, err := q.db.Query(ctx, unitsDue, arg.Livemode, arg.Day, arg.After)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unitsToGrade = `-- name: UnitsToGrade :many
SELECT id, merchant_id, livemode, arrangement, settlement_date, value, blocked, currency, constituted_on, version, registered_version, registered_at, register_error, register_retry_at, settled_on, settled_amount, payments, created_at, updated_at, recipient_id, anticipated, grade_date FROM receivables.units
WHERE livemode = $1 AND settled_on <= $2 AND grade_date IS NULL
ORDER BY id
FOR UPDATE
`

type UnitsToGradeParams struct {
	Livemode bool
	Day      pgtype.Date
}

// The units of a mode settled by a day that no grade carries, locked: those of an
// earlier day whose grade was never built go in this one.
func (q *Queries) UnitsToGrade(ctx context.Context, arg UnitsToGradeParams) ([]ReceivablesUnit, error) {
	rows, err := q.db.Query(ctx, unitsToGrade, arg.Livemode, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceivablesUnit{}
	for rows.Next() {
		var i ReceivablesUnit
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Livemode,
			&i.Arrangement,
			&i.SettlementDate,
			&i.Value,
			&i.Blocked,
			&i.Currency,
			&i.ConstitutedOn,
			&i.Version,
			&i.RegisteredVersion,
			&i.RegisteredAt,
			&i.RegisterError,
			&i.RegisterRetryAt,
			&i.SettledOn,
			&i.SettledAmount,
			&i.Payments,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecipientID,
			&i.Anticipated,
			&i.GradeDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unitsToReconcile = `-- name: UnitsToReconcile :many
SELECT id, merchant_id, livemode, arrangement, settlement_date, value, blocked, currency, constituted_on, version, registered_version, registered_at, register_error, register_retry_at, settled_on, settled_amount, payments, created_at, updated_at, recipient_id, anticipated, grade_date FROM receivables.units
WHERE livemode = $1 AND (settled_on IS NULL OR settlement_date >= $2)
ORDER BY settlement_date, id
`

type UnitsToReconcileParams struct {
	Livemode bool
	Since    pgtype.Date
}

// A mode's units still unsettled, or settled on or after since.
func (q *Queries) UnitsToReconcile(ctx context.Context, arg UnitsToReconcileParams) ([]ReceivablesUnit, error) {
	rows, err := q.db.Query(ctx, unitsToReconcile, arg.Livemode, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceivablesUnit{}
	for rows.Next() {
		var i ReceivablesUnit
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Livemode,
			&i.Arrangement,
			&i.SettlementDate,
			&i.Value,
			&i.Blocked,
			&i.Currency,
			&i.ConstitutedOn,
			&i.Version,
			&i.RegisteredVersion,
			&i.RegisteredAt,
			&i.RegisterError,
			&i.RegisterRetryAt,
			&i.SettledOn,
			&i.SettledAmount,
			&i.Payments,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecipientID,
			&i.Anticipated,
			&i.GradeDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unitsToRegister = `-- name: UnitsToRegister :many
SELECT id, merchant_id, livemode, arrangement, settlement_date, value, blocked, currency, constituted_on, version, registered_version, registered_at, register_error, register_retry_at, settled_on, settled_amount, payments, created_at, updated_at, recipient_id, anticipated, grade_date FROM receivables.units
WHERE livemode = $1 AND version > registered_version AND (register_retry_at IS NULL OR register_retry_at <= $2)
ORDER BY updated_at, id
LIMIT $3::integer
`

type UnitsToRegisterParams struct {
	Livemode bool
	Now      pgtype.Timestamptz
	MaxCount int32
}

func (q *Queries) UnitsToRegister(ctx context.Context, arg UnitsToRegisterParams) ([]ReceivablesUnit, error) {
	rows, err := q.db.Query(ctx, unitsToRegister, arg.Livemode, arg.Now, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceivablesUnit{}
	for rows.Next() {
		var i ReceivablesUnit
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Livemode,
			&i.Arrangement,
			&i.SettlementDate,
			&i.Value,
			&i.Blocked,
			&i.Currency,
			&i.ConstitutedOn,
			&i.Version,
			&i.RegisteredVersion,
			&i.RegisteredAt,
			&i.RegisterError,
			&i.RegisterRetryAt,
			&i.SettledOn,
			&i.SettledAmount,
			&i.Payments,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecipientID,
			&i.Anticipated,
			&i.GradeDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unregisteredSince = `-- name: UnregisteredSince :many
SELECT id, livemode, constituted_on, register_error FROM receivables.units
WHERE version > registered_version AND constituted_on <= $1 AND livemode = ANY($2::boolean[])
ORDER BY constituted_on, id
LIMIT 1000
`

type UnregisteredSinceParams struct {
	Day   pgtype.Date
	Modes []bool
}

type UnregisteredSinceRow struct {
	ID            string
	Livemode      bool
	ConstitutedOn pgtype.Date
	RegisterError string
}

// Units not registered as they are, from sales on or before a day: the late ones.
func (q *Queries) UnregisteredSince(ctx context.Context, arg UnregisteredSinceParams) ([]UnregisteredSinceRow, error) {
	rows, err := q.db.Query(ctx, unregisteredSince, arg.Day, arg.Modes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnregisteredSinceRow{}
	for rows.Next() {
		var i UnregisteredSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.Livemode,
			&i.ConstitutedOn,
			&i.RegisterError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const useQuote = `-- name: UseQuote :exec
UPDATE receivables.anticipation_quotes SET anticipation = $1 WHERE id = $2
`

type UseQuoteParams struct {
	Anticipation pgtype.Text
	ID           string
}

func (q *Queries) UseQuote(ctx context.Context, arg UseQuoteParams) error {
	_, err := q.db.Exec(ctx, useQuote, arg.Anticipation, arg.ID)
	return err
}
