// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AcquirerClearingException struct {
	ID                   int64
	BusinessDate         pgtype.Date
	Kind                 string
	Rrn                  string
	NetworkTransactionID string
	Amount               int64
	MerchantCode         string
	Reason               string
	ResolvedAt           pgtype.Timestamptz
}

type AcquirerClearingFile struct {
	BusinessDate pgtype.Date
	Sha256       []byte
	Records      int32
	ImportedAt   pgtype.Timestamptz
}

type AcquirerClearingRecord struct {
	BusinessDate         pgtype.Date
	Line                 int32
	Kind                 string
	Rrn                  string
	NetworkTransactionID string
	Amount               int64
	MerchantCode         string
}

type AcquirerExchange struct {
	Key                  string
	Kind                 string
	AuthorizationKey     pgtype.Text
	Mti                  string
	Stan                 string
	Rrn                  string
	TransmittedAt        string
	Amount               int64
	Installments         pgtype.Int4
	MerchantCode         string
	State                string
	ResponseCode         string
	AuthorizationCode    string
	NetworkTransactionID string
	DeclineCode          string
	LateResponseCode     string
	ForwardStan          pgtype.Text
	ForwardAttempts      int32
	NextForwardAt        pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}
