// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MerchantApiKey struct {
	ID         string
	MerchantID string
	Livemode   bool
	Kind       string
	Name       string
	Hash       []byte
	Last4      string
	Scopes     []string
	CreatedAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type MerchantMerchant struct {
	ID         string
	Name       string
	ApiVersion string
	CreatedAt  pgtype.Timestamptz
	TaxID      string
}
