// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authenticateKey = `-- name: AuthenticateKey :one
SELECT k.id, k.merchant_id, k.livemode, k.kind, k.scopes, m.api_version
FROM merchant.api_keys k
JOIN merchant.merchants m ON m.id = k.merchant_id
WHERE k.hash = $1 AND k.revoked_at IS NULL
`

type AuthenticateKeyRow struct {
	ID         string
	MerchantID string
	Livemode   bool
	Kind       string
	Scopes     []string
	ApiVersion string
}

func (q *Queries) AuthenticateKey(ctx context.Context, hash []byte) (AuthenticateKeyRow, error) {
	row := q.db.QueryRow(ctx, authenticateKey, hash)
	var i AuthenticateKeyRow
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Kind,
		&i.Scopes,
		&i.ApiVersion,
	)
	return i, err
}

const getKey = `-- name: GetKey :one
SELECT id, merchant_id, livemode, kind, name, last4, scopes, created_at, revoked_at
FROM merchant.api_keys
WHERE id = $1 AND merchant_id = $2 AND livemode = $3
`

type GetKeyParams struct {
	ID         string
	MerchantID string
	Livemode   bool
}

type GetKeyRow struct {
	ID         string
	MerchantID string
	Livemode   bool
	Kind       string
	Name       string
	Last4      string
	Scopes     []string
	CreatedAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

func (q *Queries) GetKey(ctx context.Context, arg GetKeyParams) (GetKeyRow, error) {
	row := q.db.QueryRow(ctx, getKey, arg.ID, arg.MerchantID, arg.Livemode)
	var i GetKeyRow
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Kind,
		&i.Name,
		&i.Last4,
		&i.Scopes,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getMerchant = `-- name: GetMerchant :one
SELECT id, name, api_version, tax_id, created_at FROM merchant.merchants WHERE id = $1
`

type GetMerchantRow struct {
	ID         string
	Name       string
	ApiVersion string
	TaxID      string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) GetMerchant(ctx context.Context, id string) (GetMerchantRow, error) {
	row := q.db.QueryRow(ctx, getMerchant, id)
	var i GetMerchantRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiVersion,
		&i.TaxID,
		&i.CreatedAt,
	)
	return i, err
}

const insertKey = `-- name: InsertKey :exec
INSERT INTO merchant.api_keys (id, merchant_id, livemode, kind, name, hash, last4, scopes, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertKeyParams struct {
	ID         string
	MerchantID string
	Livemode   bool
	Kind       string
	Name       string
	Hash       []byte
	Last4      string
	Scopes     []string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertKey(ctx context.Context, arg InsertKeyParams) error {
	_, err := q.db.Exec(ctx, insertKey,
		arg.ID,
		arg.MerchantID,
		arg.Livemode,
		arg.Kind,
		arg.Name,
		arg.Hash,
		arg.Last4,
		arg.Scopes,
		arg.CreatedAt,
	)
	return err
}

const insertMerchant = `-- name: InsertMerchant :exec
INSERT INTO merchant.merchants (id, name, api_version, created_at) VALUES ($1, $2, $3, $4)
`

type InsertMerchantParams struct {
	ID         string
	Name       string
	ApiVersion string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertMerchant(ctx context.Context, arg InsertMerchantParams) error {
	_, err := q.db.Exec(ctx, insertMerchant,
		arg.ID,
		arg.Name,
		arg.ApiVersion,
		arg.CreatedAt,
	)
	return err
}

const listKeys = `-- name: ListKeys :many
SELECT id, merchant_id, livemode, kind, name, last4, scopes, created_at, revoked_at
FROM merchant.api_keys
WHERE merchant_id = $1 AND livemode = $2
  AND ($3::text = '' OR id < $3)
  AND ($4::text = '' OR id > $4)
ORDER BY CASE WHEN $4 <> '' THEN id END ASC, id DESC
LIMIT $5::integer
`

type ListKeysParams struct {
	MerchantID    string
	Livemode      bool
	StartingAfter string
	EndingBefore  string
	MaxCount      int32
}

type ListKeysRow struct {
	ID         string
	MerchantID string
	Livemode   bool
	Kind       string
	Name       string
	Last4      string
	Scopes     []string
	CreatedAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

// Newest first. With ending_before, rows come oldest first and the caller reverses them.
func (q *Queries) ListKeys(ctx context.Context, arg ListKeysParams) ([]ListKeysRow, error) {
	rows, err := q.db.Query(ctx, listKeys,
		arg.MerchantID,
		arg.Livemode,
		arg.StartingAfter,
		arg.EndingBefore,
		arg.MaxCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKeysRow{}
	for rows.Next() {
		var i ListKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Livemode,
			&i.Kind,
			&i.Name,
			&i.Last4,
			&i.Scopes,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const merchantByTaxID = `-- name: MerchantByTaxID :one
SELECT id FROM merchant.merchants WHERE tax_id = $1
`

func (q *Queries) MerchantByTaxID(ctx context.Context, taxID string) (string, error) {
	row := q.db.QueryRow(ctx, merchantByTaxID, taxID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const revokeKey = `-- name: RevokeKey :one
UPDATE merchant.api_keys SET revoked_at = $1::timestamptz
WHERE id = $2 AND merchant_id = $3 AND livemode = $4 AND revoked_at IS NULL
RETURNING id, merchant_id, livemode, kind, name, last4, scopes, created_at, revoked_at
`

type RevokeKeyParams struct {
	Now        pgtype.Timestamptz
	ID         string
	MerchantID string
	Livemode   bool
}

type RevokeKeyRow struct {
	ID         string
	MerchantID string
	Livemode   bool
	Kind       string
	Name       string
	Last4      string
	Scopes     []string
	CreatedAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

func (q *Queries) RevokeKey(ctx context.Context, arg RevokeKeyParams) (RevokeKeyRow, error) {
	row := q.db.QueryRow(ctx, revokeKey,
		arg.Now,
		arg.ID,
		arg.MerchantID,
		arg.Livemode,
	)
	var i RevokeKeyRow
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Kind,
		&i.Name,
		&i.Last4,
		&i.Scopes,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const setTaxID = `-- name: SetTaxID :execrows
UPDATE merchant.merchants SET tax_id = $1 WHERE id = $2 AND tax_id = ''
`

type SetTaxIDParams struct {
	TaxID string
	ID    string
}

func (q *Queries) SetTaxID(ctx context.Context, arg SetTaxIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTaxID, arg.TaxID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
