// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RecipientsRecipient struct {
	ID                    string
	MerchantID            string
	Livemode              bool
	Name                  string
	TaxID                 string
	IsDefault             bool
	Status                string
	PayoutMethod          string
	PixKey                string
	BankIspb              string
	BankBranch            string
	BankAccount           string
	TransferInterval      string
	TransferDay           int32
	AutoAnticipation      bool
	AutoAnticipationDelay int32
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}
