// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const autoAnticipating = `-- name: AutoAnticipating :many
SELECT id, merchant_id, livemode, name, tax_id, is_default, status, payout_method, pix_key, bank_ispb, bank_branch, bank_account, transfer_interval, transfer_day, auto_anticipation, auto_anticipation_delay, created_at, updated_at, payouts_held FROM recipients.recipients
WHERE livemode = $1 AND auto_anticipation AND status = 'verified' AND id > $2
ORDER BY id LIMIT 200
`

type AutoAnticipatingParams struct {
	Livemode bool
	After    string
}

// A page of them, after the last one a pass reached.
func (q *Queries) AutoAnticipating(ctx context.Context, arg AutoAnticipatingParams) ([]RecipientsRecipient, error) {
	rows, err := q.db.Query(ctx, autoAnticipating, arg.Livemode, arg.After)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipientsRecipient{}
	for rows.Next() {
		var i RecipientsRecipient
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Livemode,
			&i.Name,
			&i.TaxID,
			&i.IsDefault,
			&i.Status,
			&i.PayoutMethod,
			&i.PixKey,
			&i.BankIspb,
			&i.BankBranch,
			&i.BankAccount,
			&i.TransferInterval,
			&i.TransferDay,
			&i.AutoAnticipation,
			&i.AutoAnticipationDelay,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PayoutsHeld,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countRecipients = `-- name: CountRecipients :one
SELECT count(*) FROM recipients.recipients WHERE merchant_id = $1 AND livemode = $2
`

type CountRecipientsParams struct {
	MerchantID string
	Livemode   bool
}

func (q *Queries) CountRecipients(ctx context.Context, arg CountRecipientsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecipients, arg.MerchantID, arg.Livemode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const defaultRecipient = `-- name: DefaultRecipient :one
SELECT id, merchant_id, livemode, name, tax_id, is_default, status, payout_method, pix_key, bank_ispb, bank_branch, bank_account, transfer_interval, transfer_day, auto_anticipation, auto_anticipation_delay, created_at, updated_at, payouts_held FROM recipients.recipients WHERE merchant_id = $1 AND livemode = $2 AND is_default
`

type DefaultRecipientParams struct {
	MerchantID string
	Livemode   bool
}

func (q *Queries) DefaultRecipient(ctx context.Context, arg DefaultRecipientParams) (RecipientsRecipient, error) {
	row := q.db.QueryRow(ctx, defaultRecipient, arg.MerchantID, arg.Livemode)
	var i RecipientsRecipient
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Name,
		&i.TaxID,
		&i.IsDefault,
		&i.Status,
		&i.PayoutMethod,
		&i.PixKey,
		&i.BankIspb,
		&i.BankBranch,
		&i.BankAccount,
		&i.TransferInterval,
		&i.TransferDay,
		&i.AutoAnticipation,
		&i.AutoAnticipationDelay,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayoutsHeld,
	)
	return i, err
}

const getRecipient = `-- name: GetRecipient :one
SELECT id, merchant_id, livemode, name, tax_id, is_default, status, payout_method, pix_key, bank_ispb, bank_branch, bank_account, transfer_interval, transfer_day, auto_anticipation, auto_anticipation_delay, created_at, updated_at, payouts_held FROM recipients.recipients WHERE id = $1 AND merchant_id = $2 AND livemode = $3
`

type GetRecipientParams struct {
	ID         string
	MerchantID string
	Livemode   bool
}

func (q *Queries) GetRecipient(ctx context.Context, arg GetRecipientParams) (RecipientsRecipient, error) {
	row := q.db.QueryRow(ctx, getRecipient, arg.ID, arg.MerchantID, arg.Livemode)
	var i RecipientsRecipient
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Name,
		&i.TaxID,
		&i.IsDefault,
		&i.Status,
		&i.PayoutMethod,
		&i.PixKey,
		&i.BankIspb,
		&i.BankBranch,
		&i.BankAccount,
		&i.TransferInterval,
		&i.TransferDay,
		&i.AutoAnticipation,
		&i.AutoAnticipationDelay,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayoutsHeld,
	)
	return i, err
}

const getRecipientByID = `-- name: GetRecipientByID :one
SELECT id, merchant_id, livemode, name, tax_id, is_default, status, payout_method, pix_key, bank_ispb, bank_branch, bank_account, transfer_interval, transfer_day, auto_anticipation, auto_anticipation_delay, created_at, updated_at, payouts_held FROM recipients.recipients WHERE id = $1
`

func (q *Queries) GetRecipientByID(ctx context.Context, id string) (RecipientsRecipient, error) {
	row := q.db.QueryRow(ctx, getRecipientByID, id)
	var i RecipientsRecipient
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Name,
		&i.TaxID,
		&i.IsDefault,
		&i.Status,
		&i.PayoutMethod,
		&i.PixKey,
		&i.BankIspb,
		&i.BankBranch,
		&i.BankAccount,
		&i.TransferInterval,
		&i.TransferDay,
		&i.AutoAnticipation,
		&i.AutoAnticipationDelay,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayoutsHeld,
	)
	return i, err
}

const insertRecipient = `-- name: InsertRecipient :exec
INSERT INTO recipients.recipients (id, merchant_id, livemode, name, tax_id, is_default, status, payout_method, pix_key,
    bank_ispb, bank_branch, bank_account, transfer_interval, transfer_day, auto_anticipation, auto_anticipation_delay,
    created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15, $16,
    $17, $17)
`

type InsertRecipientParams struct {
	ID                    string
	MerchantID            string
	Livemode              bool
	Name                  string
	TaxID                 string
	IsDefault             bool
	Status                string
	PayoutMethod          string
	PixKey                string
	BankIspb              string
	BankBranch            string
	BankAccount           string
	TransferInterval      string
	TransferDay           int32
	AutoAnticipation      bool
	AutoAnticipationDelay int32
	Now                   pgtype.Timestamptz
}

func (q *Queries) InsertRecipient(ctx context.Context, arg InsertRecipientParams) error {
	_, err := q.db.Exec(ctx, insertRecipient,
		arg.ID,
		arg.MerchantID,
		arg.Livemode,
		arg.Name,
		arg.TaxID,
		arg.IsDefault,
		arg.Status,
		arg.PayoutMethod,
		arg.PixKey,
		arg.BankIspb,
		arg.BankBranch,
		arg.BankAccount,
		arg.TransferInterval,
		arg.TransferDay,
		arg.AutoAnticipation,
		arg.AutoAnticipationDelay,
		arg.Now,
	)
	return err
}

const listRecipients = `-- name: ListRecipients :many
SELECT id, merchant_id, livemode, name, tax_id, is_default, status, payout_method, pix_key, bank_ispb, bank_branch, bank_account, transfer_interval, transfer_day, auto_anticipation, auto_anticipation_delay, created_at, updated_at, payouts_held FROM recipients.recipients
WHERE merchant_id = $1 AND livemode = $2
  AND ($3::text = '' OR id < $3)
  AND ($4::text = '' OR id > $4)
ORDER BY CASE WHEN $4 <> '' THEN id END ASC, id DESC
LIMIT $5::integer
`

type ListRecipientsParams struct {
	MerchantID    string
	Livemode      bool
	StartingAfter string
	EndingBefore  string
	MaxCount      int32
}

func (q *Queries) ListRecipients(ctx context.Context, arg ListRecipientsParams) ([]RecipientsRecipient, error) {
	rows, err := q.db.Query(ctx, listRecipients,
		arg.MerchantID,
		arg.Livemode,
		arg.StartingAfter,
		arg.EndingBefore,
		arg.MaxCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipientsRecipient{}
	for rows.Next() {
		var i RecipientsRecipient
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Livemode,
			&i.Name,
			&i.TaxID,
			&i.IsDefault,
			&i.Status,
			&i.PayoutMethod,
			&i.PixKey,
			&i.BankIspb,
			&i.BankBranch,
			&i.BankAccount,
			&i.TransferInterval,
			&i.TransferDay,
			&i.AutoAnticipation,
			&i.AutoAnticipationDelay,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PayoutsHeld,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRecipient = `-- name: LockRecipient :one
SELECT id, merchant_id, livemode, name, tax_id, is_default, status, payout_method, pix_key, bank_ispb, bank_branch, bank_account, transfer_interval, transfer_day, auto_anticipation, auto_anticipation_delay, created_at, updated_at, payouts_held FROM recipients.recipients WHERE id = $1 AND merchant_id = $2 AND livemode = $3 FOR UPDATE
`

type LockRecipientParams struct {
	ID         string
	MerchantID string
	Livemode   bool
}

func (q *Queries) LockRecipient(ctx context.Context, arg LockRecipientParams) (RecipientsRecipient, error) {
	row := q.db.QueryRow(ctx, lockRecipient, arg.ID, arg.MerchantID, arg.Livemode)
	var i RecipientsRecipient
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Name,
		&i.TaxID,
		&i.IsDefault,
		&i.Status,
		&i.PayoutMethod,
		&i.PixKey,
		&i.BankIspb,
		&i.BankBranch,
		&i.BankAccount,
		&i.TransferInterval,
		&i.TransferDay,
		&i.AutoAnticipation,
		&i.AutoAnticipationDelay,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayoutsHeld,
	)
	return i, err
}

const recipientsOf = `-- name: RecipientsOf :many
SELECT id, merchant_id, livemode, name, tax_id, is_default, status, payout_method, pix_key, bank_ispb, bank_branch, bank_account, transfer_interval, transfer_day, auto_anticipation, auto_anticipation_delay, created_at, updated_at, payouts_held FROM recipients.recipients WHERE merchant_id = $1 AND livemode = $2 AND id = ANY($3::text[])
`

type RecipientsOfParams struct {
	MerchantID string
	Livemode   bool
	Ids        []string
}

func (q *Queries) RecipientsOf(ctx context.Context, arg RecipientsOfParams) ([]RecipientsRecipient, error) {
	rows, err := q.db.Query(ctx, recipientsOf, arg.MerchantID, arg.Livemode, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipientsRecipient{}
	for rows.Next() {
		var i RecipientsRecipient
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Livemode,
			&i.Name,
			&i.TaxID,
			&i.IsDefault,
			&i.Status,
			&i.PayoutMethod,
			&i.PixKey,
			&i.BankIspb,
			&i.BankBranch,
			&i.BankAccount,
			&i.TransferInterval,
			&i.TransferDay,
			&i.AutoAnticipation,
			&i.AutoAnticipationDelay,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PayoutsHeld,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveRecipient = `-- name: SaveRecipient :exec
UPDATE recipients.recipients
SET name = $1, status = $2, payout_method = $3, pix_key = $4, bank_ispb = $5,
    bank_branch = $6, bank_account = $7, transfer_interval = $8,
    transfer_day = $9, auto_anticipation = $10, auto_anticipation_delay = $11,
    updated_at = $12
WHERE id = $13
`

type SaveRecipientParams struct {
	Name                  string
	Status                string
	PayoutMethod          string
	PixKey                string
	BankIspb              string
	BankBranch            string
	BankAccount           string
	TransferInterval      string
	TransferDay           int32
	AutoAnticipation      bool
	AutoAnticipationDelay int32
	UpdatedAt             pgtype.Timestamptz
	ID                    string
}

func (q *Queries) SaveRecipient(ctx context.Context, arg SaveRecipientParams) error {
	_, err := q.db.Exec(ctx, saveRecipient,
		arg.Name,
		arg.Status,
		arg.PayoutMethod,
		arg.PixKey,
		arg.BankIspb,
		arg.BankBranch,
		arg.BankAccount,
		arg.TransferInterval,
		arg.TransferDay,
		arg.AutoAnticipation,
		arg.AutoAnticipationDelay,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setPayoutsHeld = `-- name: SetPayoutsHeld :exec
UPDATE recipients.recipients SET payouts_held = $1, updated_at = $2 WHERE id = $3
`

type SetPayoutsHeldParams struct {
	Held bool
	Now  pgtype.Timestamptz
	ID   string
}

func (q *Queries) SetPayoutsHeld(ctx context.Context, arg SetPayoutsHeldParams) error {
	_, err := q.db.Exec(ctx, setPayoutsHeld, arg.Held, arg.Now, arg.ID)
	return err
}

const transferringRecipients = `-- name: TransferringRecipients :many
SELECT id, merchant_id, livemode, name, tax_id, is_default, status, payout_method, pix_key, bank_ispb, bank_branch, bank_account, transfer_interval, transfer_day, auto_anticipation, auto_anticipation_delay, created_at, updated_at, payouts_held FROM recipients.recipients
WHERE livemode = $1 AND transfer_interval <> 'manual' AND status = 'verified' AND id > $2
ORDER BY id LIMIT 200
`

type TransferringRecipientsParams struct {
	Livemode bool
	After    string
}

// A page of the verified recipients of a mode whose payouts are scheduled.
func (q *Queries) TransferringRecipients(ctx context.Context, arg TransferringRecipientsParams) ([]RecipientsRecipient, error) {
	rows, err := q.db.Query(ctx, transferringRecipients, arg.Livemode, arg.After)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipientsRecipient{}
	for rows.Next() {
		var i RecipientsRecipient
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Livemode,
			&i.Name,
			&i.TaxID,
			&i.IsDefault,
			&i.Status,
			&i.PayoutMethod,
			&i.PixKey,
			&i.BankIspb,
			&i.BankBranch,
			&i.BankAccount,
			&i.TransferInterval,
			&i.TransferDay,
			&i.AutoAnticipation,
			&i.AutoAnticipationDelay,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PayoutsHeld,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
