// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthenticationTransaction struct {
	ServerTransID       string
	AttemptID           string
	IntentID            string
	MerchantID          string
	Livemode            bool
	TransStatus         string
	DsTransID           string
	AcsTransID          string
	AcsUrl              string
	Eci                 string
	AuthenticationValue string
	ReturnUrl           string
	ResultStatus        string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}
