// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTransaction = `-- name: GetTransaction :one
SELECT server_trans_id, attempt_id, intent_id, merchant_id, livemode, trans_status, ds_trans_id, acs_trans_id, acs_url, eci, authentication_value, return_url, result_status, created_at, updated_at FROM authentication.transactions WHERE server_trans_id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, serverTransID string) (AuthenticationTransaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, serverTransID)
	var i AuthenticationTransaction
	err := row.Scan(
		&i.ServerTransID,
		&i.AttemptID,
		&i.IntentID,
		&i.MerchantID,
		&i.Livemode,
		&i.TransStatus,
		&i.DsTransID,
		&i.AcsTransID,
		&i.AcsUrl,
		&i.Eci,
		&i.AuthenticationValue,
		&i.ReturnUrl,
		&i.ResultStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO authentication.transactions (server_trans_id, attempt_id, intent_id, merchant_id, livemode, trans_status,
                                         ds_trans_id, acs_trans_id, acs_url, eci, authentication_value, return_url,
                                         created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, $12, $13, $13)
ON CONFLICT (attempt_id) DO NOTHING
RETURNING server_trans_id, attempt_id, intent_id, merchant_id, livemode, trans_status, ds_trans_id, acs_trans_id, acs_url, eci, authentication_value, return_url, result_status, created_at, updated_at
`

type InsertTransactionParams struct {
	ServerTransID       string
	AttemptID           string
	IntentID            string
	MerchantID          string
	Livemode            bool
	TransStatus         string
	DsTransID           string
	AcsTransID          string
	AcsUrl              string
	Eci                 string
	AuthenticationValue string
	ReturnUrl           string
	Now                 pgtype.Timestamptz
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (AuthenticationTransaction, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.ServerTransID,
		arg.AttemptID,
		arg.IntentID,
		arg.MerchantID,
		arg.Livemode,
		arg.TransStatus,
		arg.DsTransID,
		arg.AcsTransID,
		arg.AcsUrl,
		arg.Eci,
		arg.AuthenticationValue,
		arg.ReturnUrl,
		arg.Now,
	)
	var i AuthenticationTransaction
	err := row.Scan(
		&i.ServerTransID,
		&i.AttemptID,
		&i.IntentID,
		&i.MerchantID,
		&i.Livemode,
		&i.TransStatus,
		&i.DsTransID,
		&i.AcsTransID,
		&i.AcsUrl,
		&i.Eci,
		&i.AuthenticationValue,
		&i.ReturnUrl,
		&i.ResultStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordResult = `-- name: RecordResult :execrows
UPDATE authentication.transactions SET result_status = $1, updated_at = $2
WHERE server_trans_id = $3 AND result_status = ''
`

type RecordResultParams struct {
	ResultStatus  string
	Now           pgtype.Timestamptz
	ServerTransID string
}

func (q *Queries) RecordResult(ctx context.Context, arg RecordResultParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordResult, arg.ResultStatus, arg.Now, arg.ServerTransID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const transactionForAttempt = `-- name: TransactionForAttempt :one
SELECT server_trans_id, attempt_id, intent_id, merchant_id, livemode, trans_status, ds_trans_id, acs_trans_id, acs_url, eci, authentication_value, return_url, result_status, created_at, updated_at FROM authentication.transactions WHERE attempt_id = $1
`

func (q *Queries) TransactionForAttempt(ctx context.Context, attemptID string) (AuthenticationTransaction, error) {
	row := q.db.QueryRow(ctx, transactionForAttempt, attemptID)
	var i AuthenticationTransaction
	err := row.Scan(
		&i.ServerTransID,
		&i.AttemptID,
		&i.IntentID,
		&i.MerchantID,
		&i.Livemode,
		&i.TransStatus,
		&i.DsTransID,
		&i.AcsTransID,
		&i.AcsUrl,
		&i.Eci,
		&i.AuthenticationValue,
		&i.ReturnUrl,
		&i.ResultStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
