//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ApiKeyKind.
const (
	Publishable ApiKeyKind = "publishable"
	Restricted  ApiKeyKind = "restricted"
	Secret      ApiKeyKind = "secret"
)

// Valid indicates whether the value is a known member of the ApiKeyKind enum.
func (e ApiKeyKind) Valid() bool {
	switch e {
	case Publishable:
		return true
	case Restricted:
		return true
	case Secret:
		return true
	default:
		return false
	}
}

// Defines values for ApiKeyObject.
const (
	ApiKeyObjectApiKey ApiKeyObject = "api_key"
)

// Valid indicates whether the value is a known member of the ApiKeyObject enum.
func (e ApiKeyObject) Valid() bool {
	switch e {
	case ApiKeyObjectApiKey:
		return true
	default:
		return false
	}
}

// Defines values for ApiKeyListObject.
const (
	ApiKeyListObjectList ApiKeyListObject = "list"
)

// Valid indicates whether the value is a known member of the ApiKeyListObject enum.
func (e ApiKeyListObject) Valid() bool {
	switch e {
	case ApiKeyListObjectList:
		return true
	default:
		return false
	}
}

// Defines values for CancelPaymentIntentRequestCancellationReason.
const (
	CancelPaymentIntentRequestCancellationReasonAbandoned           CancelPaymentIntentRequestCancellationReason = "abandoned"
	CancelPaymentIntentRequestCancellationReasonDuplicate           CancelPaymentIntentRequestCancellationReason = "duplicate"
	CancelPaymentIntentRequestCancellationReasonFraudulent          CancelPaymentIntentRequestCancellationReason = "fraudulent"
	CancelPaymentIntentRequestCancellationReasonRequestedByCustomer CancelPaymentIntentRequestCancellationReason = "requested_by_customer"
)

// Valid indicates whether the value is a known member of the CancelPaymentIntentRequestCancellationReason enum.
func (e CancelPaymentIntentRequestCancellationReason) Valid() bool {
	switch e {
	case CancelPaymentIntentRequestCancellationReasonAbandoned:
		return true
	case CancelPaymentIntentRequestCancellationReasonDuplicate:
		return true
	case CancelPaymentIntentRequestCancellationReasonFraudulent:
		return true
	case CancelPaymentIntentRequestCancellationReasonRequestedByCustomer:
		return true
	default:
		return false
	}
}

// Defines values for CompleteActionRequestOutcome.
const (
	CompleteActionRequestOutcomeFailed    CompleteActionRequestOutcome = "failed"
	CompleteActionRequestOutcomeSucceeded CompleteActionRequestOutcome = "succeeded"
)

// Valid indicates whether the value is a known member of the CompleteActionRequestOutcome enum.
func (e CompleteActionRequestOutcome) Valid() bool {
	switch e {
	case CompleteActionRequestOutcomeFailed:
		return true
	case CompleteActionRequestOutcomeSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for CreatePaymentIntentRequestCaptureMethod.
const (
	CreatePaymentIntentRequestCaptureMethodAutomatic CreatePaymentIntentRequestCaptureMethod = "automatic"
	CreatePaymentIntentRequestCaptureMethodManual    CreatePaymentIntentRequestCaptureMethod = "manual"
)

// Valid indicates whether the value is a known member of the CreatePaymentIntentRequestCaptureMethod enum.
func (e CreatePaymentIntentRequestCaptureMethod) Valid() bool {
	switch e {
	case CreatePaymentIntentRequestCaptureMethodAutomatic:
		return true
	case CreatePaymentIntentRequestCaptureMethodManual:
		return true
	default:
		return false
	}
}

// Defines values for CreatePaymentMethodRequestType.
const (
	CreatePaymentMethodRequestTypeCard CreatePaymentMethodRequestType = "card"
)

// Valid indicates whether the value is a known member of the CreatePaymentMethodRequestType enum.
func (e CreatePaymentMethodRequestType) Valid() bool {
	switch e {
	case CreatePaymentMethodRequestTypeCard:
		return true
	default:
		return false
	}
}

// Defines values for CreateRefundRequestReason.
const (
	CreateRefundRequestReasonDuplicate           CreateRefundRequestReason = "duplicate"
	CreateRefundRequestReasonFraudulent          CreateRefundRequestReason = "fraudulent"
	CreateRefundRequestReasonRequestedByCustomer CreateRefundRequestReason = "requested_by_customer"
)

// Valid indicates whether the value is a known member of the CreateRefundRequestReason enum.
func (e CreateRefundRequestReason) Valid() bool {
	switch e {
	case CreateRefundRequestReasonDuplicate:
		return true
	case CreateRefundRequestReasonFraudulent:
		return true
	case CreateRefundRequestReasonRequestedByCustomer:
		return true
	default:
		return false
	}
}

// Defines values for DeletedObjectDeleted.
const (
	True DeletedObjectDeleted = true
)

// Valid indicates whether the value is a known member of the DeletedObjectDeleted enum.
func (e DeletedObjectDeleted) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// Defines values for ErrorType.
const (
	ApiError            ErrorType = "api_error"
	AuthenticationError ErrorType = "authentication_error"
	CardError           ErrorType = "card_error"
	IdempotencyError    ErrorType = "idempotency_error"
	InvalidRequestError ErrorType = "invalid_request_error"
	PermissionError     ErrorType = "permission_error"
	RateLimitError      ErrorType = "rate_limit_error"
)

// Valid indicates whether the value is a known member of the ErrorType enum.
func (e ErrorType) Valid() bool {
	switch e {
	case ApiError:
		return true
	case AuthenticationError:
		return true
	case CardError:
		return true
	case IdempotencyError:
		return true
	case InvalidRequestError:
		return true
	case PermissionError:
		return true
	case RateLimitError:
		return true
	default:
		return false
	}
}

// Defines values for EventObject.
const (
	EventObjectEvent EventObject = "event"
)

// Valid indicates whether the value is a known member of the EventObject enum.
func (e EventObject) Valid() bool {
	switch e {
	case EventObjectEvent:
		return true
	default:
		return false
	}
}

// Defines values for EventListObject.
const (
	EventListObjectList EventListObject = "list"
)

// Valid indicates whether the value is a known member of the EventListObject enum.
func (e EventListObject) Valid() bool {
	switch e {
	case EventListObjectList:
		return true
	default:
		return false
	}
}

// Defines values for ListMetaObject.
const (
	ListMetaObjectList ListMetaObject = "list"
)

// Valid indicates whether the value is a known member of the ListMetaObject enum.
func (e ListMetaObject) Valid() bool {
	switch e {
	case ListMetaObjectList:
		return true
	default:
		return false
	}
}

// Defines values for PaymentIntentCaptureMethod.
const (
	PaymentIntentCaptureMethodAutomatic PaymentIntentCaptureMethod = "automatic"
	PaymentIntentCaptureMethodManual    PaymentIntentCaptureMethod = "manual"
)

// Valid indicates whether the value is a known member of the PaymentIntentCaptureMethod enum.
func (e PaymentIntentCaptureMethod) Valid() bool {
	switch e {
	case PaymentIntentCaptureMethodAutomatic:
		return true
	case PaymentIntentCaptureMethodManual:
		return true
	default:
		return false
	}
}

// Defines values for PaymentIntentObject.
const (
	PaymentIntentObjectPaymentIntent PaymentIntentObject = "payment_intent"
)

// Valid indicates whether the value is a known member of the PaymentIntentObject enum.
func (e PaymentIntentObject) Valid() bool {
	switch e {
	case PaymentIntentObjectPaymentIntent:
		return true
	default:
		return false
	}
}

// Defines values for PaymentIntentStatus.
const (
	PaymentIntentStatusCanceled              PaymentIntentStatus = "canceled"
	PaymentIntentStatusProcessing            PaymentIntentStatus = "processing"
	PaymentIntentStatusRequiresAction        PaymentIntentStatus = "requires_action"
	PaymentIntentStatusRequiresCapture       PaymentIntentStatus = "requires_capture"
	PaymentIntentStatusRequiresConfirmation  PaymentIntentStatus = "requires_confirmation"
	PaymentIntentStatusRequiresPaymentMethod PaymentIntentStatus = "requires_payment_method"
	PaymentIntentStatusSucceeded             PaymentIntentStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the PaymentIntentStatus enum.
func (e PaymentIntentStatus) Valid() bool {
	switch e {
	case PaymentIntentStatusCanceled:
		return true
	case PaymentIntentStatusProcessing:
		return true
	case PaymentIntentStatusRequiresAction:
		return true
	case PaymentIntentStatusRequiresCapture:
		return true
	case PaymentIntentStatusRequiresConfirmation:
		return true
	case PaymentIntentStatusRequiresPaymentMethod:
		return true
	case PaymentIntentStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for PaymentIntentListObject.
const (
	PaymentIntentListObjectList PaymentIntentListObject = "list"
)

// Valid indicates whether the value is a known member of the PaymentIntentListObject enum.
func (e PaymentIntentListObject) Valid() bool {
	switch e {
	case PaymentIntentListObjectList:
		return true
	default:
		return false
	}
}

// Defines values for PaymentMethodObject.
const (
	PaymentMethodObjectPaymentMethod PaymentMethodObject = "payment_method"
)

// Valid indicates whether the value is a known member of the PaymentMethodObject enum.
func (e PaymentMethodObject) Valid() bool {
	switch e {
	case PaymentMethodObjectPaymentMethod:
		return true
	default:
		return false
	}
}

// Defines values for PaymentMethodType.
const (
	PaymentMethodTypeCard PaymentMethodType = "card"
)

// Valid indicates whether the value is a known member of the PaymentMethodType enum.
func (e PaymentMethodType) Valid() bool {
	switch e {
	case PaymentMethodTypeCard:
		return true
	default:
		return false
	}
}

// Defines values for PaymentMethodCardBrand.
const (
	Amex       PaymentMethodCardBrand = "amex"
	Elo        PaymentMethodCardBrand = "elo"
	Hipercard  PaymentMethodCardBrand = "hipercard"
	Mastercard PaymentMethodCardBrand = "mastercard"
	Unknown    PaymentMethodCardBrand = "unknown"
	Visa       PaymentMethodCardBrand = "visa"
)

// Valid indicates whether the value is a known member of the PaymentMethodCardBrand enum.
func (e PaymentMethodCardBrand) Valid() bool {
	switch e {
	case Amex:
		return true
	case Elo:
		return true
	case Hipercard:
		return true
	case Mastercard:
		return true
	case Unknown:
		return true
	case Visa:
		return true
	default:
		return false
	}
}

// Defines values for RefundObject.
const (
	RefundObjectRefund RefundObject = "refund"
)

// Valid indicates whether the value is a known member of the RefundObject enum.
func (e RefundObject) Valid() bool {
	switch e {
	case RefundObjectRefund:
		return true
	default:
		return false
	}
}

// Defines values for RefundStatus.
const (
	RefundStatusFailed    RefundStatus = "failed"
	RefundStatusPending   RefundStatus = "pending"
	RefundStatusSucceeded RefundStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the RefundStatus enum.
func (e RefundStatus) Valid() bool {
	switch e {
	case RefundStatusFailed:
		return true
	case RefundStatusPending:
		return true
	case RefundStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for RefundListObject.
const (
	RefundListObjectList RefundListObject = "list"
)

// Valid indicates whether the value is a known member of the RefundListObject enum.
func (e RefundListObject) Valid() bool {
	switch e {
	case RefundListObjectList:
		return true
	default:
		return false
	}
}

// Defines values for UpdateWebhookEndpointRequestStatus.
const (
	UpdateWebhookEndpointRequestStatusDisabled UpdateWebhookEndpointRequestStatus = "disabled"
	UpdateWebhookEndpointRequestStatusEnabled  UpdateWebhookEndpointRequestStatus = "enabled"
)

// Valid indicates whether the value is a known member of the UpdateWebhookEndpointRequestStatus enum.
func (e UpdateWebhookEndpointRequestStatus) Valid() bool {
	switch e {
	case UpdateWebhookEndpointRequestStatusDisabled:
		return true
	case UpdateWebhookEndpointRequestStatusEnabled:
		return true
	default:
		return false
	}
}

// Defines values for WebhookEndpointObject.
const (
	WebhookEndpointObjectWebhookEndpoint WebhookEndpointObject = "webhook_endpoint"
)

// Valid indicates whether the value is a known member of the WebhookEndpointObject enum.
func (e WebhookEndpointObject) Valid() bool {
	switch e {
	case WebhookEndpointObjectWebhookEndpoint:
		return true
	default:
		return false
	}
}

// Defines values for WebhookEndpointStatus.
const (
	WebhookEndpointStatusDisabled WebhookEndpointStatus = "disabled"
	WebhookEndpointStatusEnabled  WebhookEndpointStatus = "enabled"
)

// Valid indicates whether the value is a known member of the WebhookEndpointStatus enum.
func (e WebhookEndpointStatus) Valid() bool {
	switch e {
	case WebhookEndpointStatusDisabled:
		return true
	case WebhookEndpointStatusEnabled:
		return true
	default:
		return false
	}
}

// Defines values for WebhookEndpointListObject.
const (
	WebhookEndpointListObjectList WebhookEndpointListObject = "list"
)

// Valid indicates whether the value is a known member of the WebhookEndpointListObject enum.
func (e WebhookEndpointListObject) Valid() bool {
	switch e {
	case WebhookEndpointListObjectList:
		return true
	default:
		return false
	}
}

// ApiKey defines model for ApiKey.
type ApiKey struct {
	Created  int64        `json:"created"`
	Id       string       `json:"id"`
	Kind     ApiKeyKind   `json:"kind"`
	Last4    string       `json:"last4"`
	Livemode bool         `json:"livemode"`
	Name     string       `json:"name"`
	Object   ApiKeyObject `json:"object"`
	Revoked  *int64       `json:"revoked,omitempty"`
	Scopes   []string     `json:"scopes"`

	// Value The key itself, present only in the response that created it.
	Value *string `json:"value,omitempty"`
}

// ApiKeyKind defines model for ApiKey.Kind.
type ApiKeyKind string

// ApiKeyObject defines model for ApiKey.Object.
type ApiKeyObject string

// ApiKeyList defines model for ApiKeyList.
type ApiKeyList struct {
	Data    []ApiKey         `json:"data"`
	HasMore bool             `json:"has_more"`
	Object  ApiKeyListObject `json:"object"`
	Url     string           `json:"url"`
}

// ApiKeyListObject defines model for ApiKeyList.Object.
type ApiKeyListObject string

// CancelPaymentIntentRequest defines model for CancelPaymentIntentRequest.
type CancelPaymentIntentRequest struct {
	CancellationReason *CancelPaymentIntentRequestCancellationReason `json:"cancellation_reason,omitempty"`
}

// CancelPaymentIntentRequestCancellationReason defines model for CancelPaymentIntentRequest.CancellationReason.
type CancelPaymentIntentRequestCancellationReason string

// CapturePaymentIntentRequest defines model for CapturePaymentIntentRequest.
type CapturePaymentIntentRequest struct {
	AmountToCapture *int64 `json:"amount_to_capture,omitempty"`
}

// CardDetails Either number and expiry, with an optional cvc, or a token from the vault.
type CardDetails struct {
	Cvc      *string `json:"cvc,omitempty"`
	ExpMonth *int    `json:"exp_month,omitempty"`
	ExpYear  *int    `json:"exp_year,omitempty"`
	Number   *string `json:"number,omitempty"`
	Token    *string `json:"token,omitempty"`
}

// CompleteActionRequest defines model for CompleteActionRequest.
type CompleteActionRequest struct {
	Outcome CompleteActionRequestOutcome `json:"outcome"`
}

// CompleteActionRequestOutcome defines model for CompleteActionRequest.Outcome.
type CompleteActionRequestOutcome string

// ConfirmPaymentIntentRequest defines model for ConfirmPaymentIntentRequest.
type ConfirmPaymentIntentRequest struct {
	PaymentMethod *string `json:"payment_method,omitempty"`
}

// CreateApiKeyRequest defines model for CreateApiKeyRequest.
type CreateApiKeyRequest struct {
	Name   *string  `json:"name,omitempty"`
	Scopes []string `json:"scopes"`
}

// CreatePaymentIntentRequest defines model for CreatePaymentIntentRequest.
type CreatePaymentIntentRequest struct {
	Amount        int64                                    `json:"amount"`
	CaptureMethod *CreatePaymentIntentRequestCaptureMethod `json:"capture_method,omitempty"`
	Confirm       *bool                                    `json:"confirm,omitempty"`
	Currency      string                                   `json:"currency"`
	Description   *string                                  `json:"description,omitempty"`
	PaymentMethod *string                                  `json:"payment_method,omitempty"`
}

// CreatePaymentIntentRequestCaptureMethod defines model for CreatePaymentIntentRequest.CaptureMethod.
type CreatePaymentIntentRequestCaptureMethod string

// CreatePaymentMethodRequest defines model for CreatePaymentMethodRequest.
type CreatePaymentMethodRequest struct {
	// Card Either number and expiry, with an optional cvc, or a token from the vault.
	Card CardDetails                    `json:"card"`
	Type CreatePaymentMethodRequestType `json:"type"`
}

// CreatePaymentMethodRequestType defines model for CreatePaymentMethodRequest.Type.
type CreatePaymentMethodRequestType string

// CreateRefundRequest defines model for CreateRefundRequest.
type CreateRefundRequest struct {
	Amount        *int64                     `json:"amount,omitempty"`
	PaymentIntent string                     `json:"payment_intent"`
	Reason        *CreateRefundRequestReason `json:"reason,omitempty"`
}

// CreateRefundRequestReason defines model for CreateRefundRequest.Reason.
type CreateRefundRequestReason string

// CreateWebhookEndpointRequest defines model for CreateWebhookEndpointRequest.
type CreateWebhookEndpointRequest struct {
	Description   *string  `json:"description,omitempty"`
	EnabledEvents []string `json:"enabled_events"`
	Url           string   `json:"url"`
}

// DeletedObject defines model for DeletedObject.
type DeletedObject struct {
	Deleted DeletedObjectDeleted `json:"deleted"`
	Id      string               `json:"id"`
	Object  string               `json:"object"`
}

// DeletedObjectDeleted defines model for DeletedObject.Deleted.
type DeletedObjectDeleted bool

// Error defines model for Error.
type Error struct {
	Code          string         `json:"code"`
	DeclineCode   *string        `json:"decline_code,omitempty"`
	DocUrl        string         `json:"doc_url"`
	Message       string         `json:"message"`
	Param         *string        `json:"param,omitempty"`
	PaymentIntent *PaymentIntent `json:"payment_intent,omitempty"`
	RequestId     string         `json:"request_id"`
	Type          ErrorType      `json:"type"`
}

// ErrorType defines model for Error.Type.
type ErrorType string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error Error `json:"error"`
}

// Event defines model for Event.
type Event struct {
	Created  int64       `json:"created"`
	Id       string      `json:"id"`
	Livemode bool        `json:"livemode"`
	Object   EventObject `json:"object"`

	// RelatedObject What the event is about. Events are thin: fetch the object for its current state,
	// or ask for it inline with include[]=related_object.
	RelatedObject RelatedObject `json:"related_object"`
	Type          string        `json:"type"`
}

// EventObject defines model for Event.Object.
type EventObject string

// EventList defines model for EventList.
type EventList struct {
	Data    []Event         `json:"data"`
	HasMore bool            `json:"has_more"`
	Object  EventListObject `json:"object"`
	Url     string          `json:"url"`
}

// EventListObject defines model for EventList.Object.
type EventListObject string

// ListMeta defines model for ListMeta.
type ListMeta struct {
	HasMore bool           `json:"has_more"`
	Object  ListMetaObject `json:"object"`
	Url     string         `json:"url"`
}

// ListMetaObject defines model for ListMeta.Object.
type ListMetaObject string

// NextAction defines model for NextAction.
type NextAction struct {
	// Type use_test_authentication: complete it with the test helper.
	Type string `json:"type"`
}

// PaymentError defines model for PaymentError.
type PaymentError struct {
	Code        string  `json:"code"`
	DeclineCode *string `json:"decline_code,omitempty"`
	Message     string  `json:"message"`
}

// PaymentIntent defines model for PaymentIntent.
type PaymentIntent struct {
	// Amount In the currency's minor unit, such as centavos.
	Amount             int64                      `json:"amount"`
	AmountCapturable   int64                      `json:"amount_capturable"`
	AmountReceived     int64                      `json:"amount_received"`
	AmountRefunded     int64                      `json:"amount_refunded"`
	CancellationReason *string                    `json:"cancellation_reason"`
	CaptureMethod      PaymentIntentCaptureMethod `json:"capture_method"`
	Created            int64                      `json:"created"`

	// Currency Lower-case ISO 4217 code.
	Currency         string              `json:"currency"`
	Description      string              `json:"description"`
	Id               string              `json:"id"`
	LastPaymentError *PaymentError       `json:"last_payment_error"`
	LatestAttempt    *string             `json:"latest_attempt"`
	Livemode         bool                `json:"livemode"`
	NextAction       *NextAction         `json:"next_action"`
	Object           PaymentIntentObject `json:"object"`
	PaymentMethod    *string             `json:"payment_method"`
	Status           PaymentIntentStatus `json:"status"`
}

// PaymentIntentCaptureMethod defines model for PaymentIntent.CaptureMethod.
type PaymentIntentCaptureMethod string

// PaymentIntentObject defines model for PaymentIntent.Object.
type PaymentIntentObject string

// PaymentIntentStatus defines model for PaymentIntent.Status.
type PaymentIntentStatus string

// PaymentIntentList defines model for PaymentIntentList.
type PaymentIntentList struct {
	Data    []PaymentIntent         `json:"data"`
	HasMore bool                    `json:"has_more"`
	Object  PaymentIntentListObject `json:"object"`
	Url     string                  `json:"url"`
}

// PaymentIntentListObject defines model for PaymentIntentList.Object.
type PaymentIntentListObject string

// PaymentMethod defines model for PaymentMethod.
type PaymentMethod struct {
	Card     PaymentMethodCard   `json:"card"`
	Created  int64               `json:"created"`
	Id       string              `json:"id"`
	Livemode bool                `json:"livemode"`
	Object   PaymentMethodObject `json:"object"`
	Type     PaymentMethodType   `json:"type"`
}

// PaymentMethodObject defines model for PaymentMethod.Object.
type PaymentMethodObject string

// PaymentMethodType defines model for PaymentMethod.Type.
type PaymentMethodType string

// PaymentMethodCard defines model for PaymentMethodCard.
type PaymentMethodCard struct {
	// Bin The first eight digits of a number of sixteen or more, else the first six.
	Bin      string                 `json:"bin"`
	Brand    PaymentMethodCardBrand `json:"brand"`
	ExpMonth int                    `json:"exp_month"`
	ExpYear  int                    `json:"exp_year"`

	// Fingerprint The same for the same card number across this merchant's payment methods.
	Fingerprint string `json:"fingerprint"`
	Last4       string `json:"last4"`
}

// PaymentMethodCardBrand defines model for PaymentMethodCard.Brand.
type PaymentMethodCardBrand string

// Refund defines model for Refund.
type Refund struct {
	Amount        int64        `json:"amount"`
	Created       int64        `json:"created"`
	Currency      string       `json:"currency"`
	FailureReason *string      `json:"failure_reason"`
	Id            string       `json:"id"`
	Livemode      bool         `json:"livemode"`
	Object        RefundObject `json:"object"`
	PaymentIntent string       `json:"payment_intent"`
	Reason        *string      `json:"reason"`
	Status        RefundStatus `json:"status"`
}

// RefundObject defines model for Refund.Object.
type RefundObject string

// RefundStatus defines model for Refund.Status.
type RefundStatus string

// RefundList defines model for RefundList.
type RefundList struct {
	Data    []Refund         `json:"data"`
	HasMore bool             `json:"has_more"`
	Object  RefundListObject `json:"object"`
	Url     string           `json:"url"`
}

// RefundListObject defines model for RefundList.Object.
type RefundListObject string

// RelatedObject What the event is about. Events are thin: fetch the object for its current state,
// or ask for it inline with include[]=related_object.
type RelatedObject struct {
	Id string `json:"id"`

	// Object The object's current state, when included and it still exists.
	Object *map[string]interface{} `json:"object,omitempty"`
	Type   string                  `json:"type"`
	Url    string                  `json:"url"`
}

// ResendEventRequest defines model for ResendEventRequest.
type ResendEventRequest struct {
	WebhookEndpoint *string `json:"webhook_endpoint,omitempty"`
}

// RollSecretRequest defines model for RollSecretRequest.
type RollSecretRequest struct {
	ExpireCurrentIn *int `json:"expire_current_in,omitempty"`
}

// UpdatePaymentIntentRequest defines model for UpdatePaymentIntentRequest.
type UpdatePaymentIntentRequest struct {
	Amount        *int64  `json:"amount,omitempty"`
	Description   *string `json:"description,omitempty"`
	PaymentMethod *string `json:"payment_method,omitempty"`
}

// UpdateWebhookEndpointRequest defines model for UpdateWebhookEndpointRequest.
type UpdateWebhookEndpointRequest struct {
	Description   *string                             `json:"description,omitempty"`
	EnabledEvents *[]string                           `json:"enabled_events,omitempty"`
	Status        *UpdateWebhookEndpointRequestStatus `json:"status,omitempty"`
	Url           *string                             `json:"url,omitempty"`
}

// UpdateWebhookEndpointRequestStatus defines model for UpdateWebhookEndpointRequest.Status.
type UpdateWebhookEndpointRequestStatus string

// WebhookEndpoint defines model for WebhookEndpoint.
type WebhookEndpoint struct {
	ApiVersion    string                `json:"api_version"`
	Created       int64                 `json:"created"`
	Description   string                `json:"description"`
	EnabledEvents []string              `json:"enabled_events"`
	Id            string                `json:"id"`
	Livemode      bool                  `json:"livemode"`
	Object        WebhookEndpointObject `json:"object"`

	// Secret The signing secret, present only when it was just created or rolled.
	Secret *string               `json:"secret,omitempty"`
	Status WebhookEndpointStatus `json:"status"`
	Url    string                `json:"url"`
}

// WebhookEndpointObject defines model for WebhookEndpoint.Object.
type WebhookEndpointObject string

// WebhookEndpointStatus defines model for WebhookEndpoint.Status.
type WebhookEndpointStatus string

// WebhookEndpointList defines model for WebhookEndpointList.
type WebhookEndpointList struct {
	Data    []WebhookEndpoint         `json:"data"`
	HasMore bool                      `json:"has_more"`
	Object  WebhookEndpointListObject `json:"object"`
	Url     string                    `json:"url"`
}

// WebhookEndpointListObject defines model for WebhookEndpointList.Object.
type WebhookEndpointListObject string

// EndingBefore defines model for EndingBefore.
type EndingBefore = string

// ID defines model for ID.
type ID = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// Include defines model for Include.
type Include = []string

// Limit defines model for Limit.
type Limit = int

// StartingAfter defines model for StartingAfter.
type StartingAfter = string

// Failure defines model for Failure.
type Failure = ErrorResponse

// ListApiKeysParams defines parameters for ListApiKeys.
type ListApiKeysParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter An object id; the page starts with the next older object.
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore An object id; the page ends with the next newer object.
	EndingBefore *EndingBefore `form:"ending_before,omitempty" json:"ending_before,omitempty"`
}

// CreateApiKeyParams defines parameters for CreateApiKey.
type CreateApiKeyParams struct {
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// RevokeApiKeyParams defines parameters for RevokeApiKey.
type RevokeApiKeyParams struct {
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// ListEventsParams defines parameters for ListEvents.
type ListEventsParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter An object id; the page starts with the next older object.
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore An object id; the page ends with the next newer object.
	EndingBefore *EndingBefore `form:"ending_before,omitempty" json:"ending_before,omitempty"`
	Type         *string       `form:"type,omitempty" json:"type,omitempty"`

	// Include Related objects to return inline. Events accept related_object.
	Include *Include `form:"include[],omitempty" json:"include[],omitempty"`
}

// GetEventParams defines parameters for GetEvent.
type GetEventParams struct {
	// Include Related objects to return inline. Events accept related_object.
	Include *Include `form:"include[],omitempty" json:"include[],omitempty"`
}

// ResendEventParams defines parameters for ResendEvent.
type ResendEventParams struct {
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// ListPaymentIntentsParams defines parameters for ListPaymentIntents.
type ListPaymentIntentsParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter An object id; the page starts with the next older object.
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore An object id; the page ends with the next newer object.
	EndingBefore *EndingBefore `form:"ending_before,omitempty" json:"ending_before,omitempty"`
}

// CreatePaymentIntentParams defines parameters for CreatePaymentIntent.
type CreatePaymentIntentParams struct {
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// UpdatePaymentIntentParams defines parameters for UpdatePaymentIntent.
type UpdatePaymentIntentParams struct {
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// CancelPaymentIntentParams defines parameters for CancelPaymentIntent.
type CancelPaymentIntentParams struct {
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// CapturePaymentIntentParams defines parameters for CapturePaymentIntent.
type CapturePaymentIntentParams struct {
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// ConfirmPaymentIntentParams defines parameters for ConfirmPaymentIntent.
type ConfirmPaymentIntentParams struct {
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// CreatePaymentMethodParams defines parameters for CreatePaymentMethod.
type CreatePaymentMethodParams struct {
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// ListRefundsParams defines parameters for ListRefunds.
type ListRefundsParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter An object id; the page starts with the next older object.
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore An object id; the page ends with the next newer object.
	EndingBefore  *EndingBefore `form:"ending_before,omitempty" json:"ending_before,omitempty"`
	PaymentIntent *string       `form:"payment_intent,omitempty" json:"payment_intent,omitempty"`
}

// CreateRefundParams defines parameters for CreateRefund.
type CreateRefundParams struct {
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// CompletePaymentIntentActionParams defines parameters for CompletePaymentIntentAction.
type CompletePaymentIntentActionParams struct {
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// ListWebhookEndpointsParams defines parameters for ListWebhookEndpoints.
type ListWebhookEndpointsParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter An object id; the page starts with the next older object.
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore An object id; the page ends with the next newer object.
	EndingBefore *EndingBefore `form:"ending_before,omitempty" json:"ending_before,omitempty"`
}

// CreateWebhookEndpointParams defines parameters for CreateWebhookEndpoint.
type CreateWebhookEndpointParams struct {
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// UpdateWebhookEndpointParams defines parameters for UpdateWebhookEndpoint.
type UpdateWebhookEndpointParams struct {
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// RollWebhookEndpointSecretParams defines parameters for RollWebhookEndpointSecret.
type RollWebhookEndpointSecretParams struct {
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = CreateApiKeyRequest

// ResendEventJSONRequestBody defines body for ResendEvent for application/json ContentType.
type ResendEventJSONRequestBody = ResendEventRequest

// CreatePaymentIntentJSONRequestBody defines body for CreatePaymentIntent for application/json ContentType.
type CreatePaymentIntentJSONRequestBody = CreatePaymentIntentRequest

// UpdatePaymentIntentJSONRequestBody defines body for UpdatePaymentIntent for application/json ContentType.
type UpdatePaymentIntentJSONRequestBody = UpdatePaymentIntentRequest

// CancelPaymentIntentJSONRequestBody defines body for CancelPaymentIntent for application/json ContentType.
type CancelPaymentIntentJSONRequestBody = CancelPaymentIntentRequest

// CapturePaymentIntentJSONRequestBody defines body for CapturePaymentIntent for application/json ContentType.
type CapturePaymentIntentJSONRequestBody = CapturePaymentIntentRequest

// ConfirmPaymentIntentJSONRequestBody defines body for ConfirmPaymentIntent for application/json ContentType.
type ConfirmPaymentIntentJSONRequestBody = ConfirmPaymentIntentRequest

// CreatePaymentMethodJSONRequestBody defines body for CreatePaymentMethod for application/json ContentType.
type CreatePaymentMethodJSONRequestBody = CreatePaymentMethodRequest

// CreateRefundJSONRequestBody defines body for CreateRefund for application/json ContentType.
type CreateRefundJSONRequestBody = CreateRefundRequest

// CompletePaymentIntentActionJSONRequestBody defines body for CompletePaymentIntentAction for application/json ContentType.
type CompletePaymentIntentActionJSONRequestBody = CompleteActionRequest

// CreateWebhookEndpointJSONRequestBody defines body for CreateWebhookEndpoint for application/json ContentType.
type CreateWebhookEndpointJSONRequestBody = CreateWebhookEndpointRequest

// UpdateWebhookEndpointJSONRequestBody defines body for UpdateWebhookEndpoint for application/json ContentType.
type UpdateWebhookEndpointJSONRequestBody = UpdateWebhookEndpointRequest

// RollWebhookEndpointSecretJSONRequestBody defines body for RollWebhookEndpointSecret for application/json ContentType.
type RollWebhookEndpointSecretJSONRequestBody = RollSecretRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /v1/api_keys)
	ListApiKeys(w http.ResponseWriter, r *http.Request, params ListApiKeysParams)

	// (POST /v1/api_keys)
	CreateApiKey(w http.ResponseWriter, r *http.Request, params CreateApiKeyParams)

	// (GET /v1/api_keys/{id})
	GetApiKey(w http.ResponseWriter, r *http.Request, id ID)

	// (POST /v1/api_keys/{id}/revoke)
	RevokeApiKey(w http.ResponseWriter, r *http.Request, id ID, params RevokeApiKeyParams)

	// (GET /v1/events)
	ListEvents(w http.ResponseWriter, r *http.Request, params ListEventsParams)

	// (GET /v1/events/{id})
	GetEvent(w http.ResponseWriter, r *http.Request, id ID, params GetEventParams)

	// (POST /v1/events/{id}/resend)
	ResendEvent(w http.ResponseWriter, r *http.Request, id ID, params ResendEventParams)

	// (GET /v1/payment_intents)
	ListPaymentIntents(w http.ResponseWriter, r *http.Request, params ListPaymentIntentsParams)

	// (POST /v1/payment_intents)
	CreatePaymentIntent(w http.ResponseWriter, r *http.Request, params CreatePaymentIntentParams)

	// (GET /v1/payment_intents/{id})
	GetPaymentIntent(w http.ResponseWriter, r *http.Request, id ID)

	// (POST /v1/payment_intents/{id})
	UpdatePaymentIntent(w http.ResponseWriter, r *http.Request, id ID, params UpdatePaymentIntentParams)

	// (POST /v1/payment_intents/{id}/cancel)
	CancelPaymentIntent(w http.ResponseWriter, r *http.Request, id ID, params CancelPaymentIntentParams)

	// (POST /v1/payment_intents/{id}/capture)
	CapturePaymentIntent(w http.ResponseWriter, r *http.Request, id ID, params CapturePaymentIntentParams)

	// (POST /v1/payment_intents/{id}/confirm)
	ConfirmPaymentIntent(w http.ResponseWriter, r *http.Request, id ID, params ConfirmPaymentIntentParams)

	// (POST /v1/payment_methods)
	CreatePaymentMethod(w http.ResponseWriter, r *http.Request, params CreatePaymentMethodParams)

	// (GET /v1/payment_methods/{id})
	GetPaymentMethod(w http.ResponseWriter, r *http.Request, id ID)

	// (GET /v1/refunds)
	ListRefunds(w http.ResponseWriter, r *http.Request, params ListRefundsParams)

	// (POST /v1/refunds)
	CreateRefund(w http.ResponseWriter, r *http.Request, params CreateRefundParams)

	// (GET /v1/refunds/{id})
	GetRefund(w http.ResponseWriter, r *http.Request, id ID)

	// (POST /v1/test_helpers/payment_intents/{id}/complete_action)
	CompletePaymentIntentAction(w http.ResponseWriter, r *http.Request, id ID, params CompletePaymentIntentActionParams)

	// (GET /v1/webhook_endpoints)
	ListWebhookEndpoints(w http.ResponseWriter, r *http.Request, params ListWebhookEndpointsParams)

	// (POST /v1/webhook_endpoints)
	CreateWebhookEndpoint(w http.ResponseWriter, r *http.Request, params CreateWebhookEndpointParams)

	// (DELETE /v1/webhook_endpoints/{id})
	DeleteWebhookEndpoint(w http.ResponseWriter, r *http.Request, id ID)

	// (GET /v1/webhook_endpoints/{id})
	GetWebhookEndpoint(w http.ResponseWriter, r *http.Request, id ID)

	// (POST /v1/webhook_endpoints/{id})
	UpdateWebhookEndpoint(w http.ResponseWriter, r *http.Request, id ID, params UpdateWebhookEndpointParams)

	// (POST /v1/webhook_endpoints/{id}/roll_secret)
	RollWebhookEndpointSecret(w http.ResponseWriter, r *http.Request, id ID, params RollWebhookEndpointSecretParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListApiKeys operation middleware
func (siw *ServerInterfaceWrapper) ListApiKeys(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListApiKeysParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "starting_after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "starting_after", r.URL.Query(), &params.StartingAfter, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "starting_after"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "starting_after", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "ending_before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "ending_before", r.URL.Query(), &params.EndingBefore, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "ending_before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ending_before", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApiKeys(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateApiKey operation middleware
func (siw *ServerInterfaceWrapper) CreateApiKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateApiKeyParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateApiKey(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiKey operation middleware
func (siw *ServerInterfaceWrapper) GetApiKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiKey(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeApiKey operation middleware
func (siw *ServerInterfaceWrapper) RevokeApiKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RevokeApiKeyParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeApiKey(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEvents operation middleware
func (siw *ServerInterfaceWrapper) ListEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEventsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "starting_after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "starting_after", r.URL.Query(), &params.StartingAfter, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "starting_after"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "starting_after", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "ending_before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "ending_before", r.URL.Query(), &params.EndingBefore, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "ending_before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ending_before", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "include[]" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "include[]", r.URL.Query(), &params.Include, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "include[]"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include[]", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvent operation middleware
func (siw *ServerInterfaceWrapper) GetEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventParams

	// ------------- Optional query parameter "include[]" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "include[]", r.URL.Query(), &params.Include, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "include[]"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include[]", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvent(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResendEvent operation middleware
func (siw *ServerInterfaceWrapper) ResendEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ResendEventParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResendEvent(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPaymentIntents operation middleware
func (siw *ServerInterfaceWrapper) ListPaymentIntents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPaymentIntentsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "starting_after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "starting_after", r.URL.Query(), &params.StartingAfter, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "starting_after"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "starting_after", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "ending_before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "ending_before", r.URL.Query(), &params.EndingBefore, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "ending_before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ending_before", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPaymentIntents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePaymentIntent operation middleware
func (siw *ServerInterfaceWrapper) CreatePaymentIntent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreatePaymentIntentParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePaymentIntent(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPaymentIntent operation middleware
func (siw *ServerInterfaceWrapper) GetPaymentIntent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPaymentIntent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePaymentIntent operation middleware
func (siw *ServerInterfaceWrapper) UpdatePaymentIntent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdatePaymentIntentParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePaymentIntent(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelPaymentIntent operation middleware
func (siw *ServerInterfaceWrapper) CancelPaymentIntent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CancelPaymentIntentParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelPaymentIntent(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CapturePaymentIntent operation middleware
func (siw *ServerInterfaceWrapper) CapturePaymentIntent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CapturePaymentIntentParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CapturePaymentIntent(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConfirmPaymentIntent operation middleware
func (siw *ServerInterfaceWrapper) ConfirmPaymentIntent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ConfirmPaymentIntentParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConfirmPaymentIntent(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePaymentMethod operation middleware
func (siw *ServerInterfaceWrapper) CreatePaymentMethod(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreatePaymentMethodParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePaymentMethod(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPaymentMethod operation middleware
func (siw *ServerInterfaceWrapper) GetPaymentMethod(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPaymentMethod(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRefunds operation middleware
func (siw *ServerInterfaceWrapper) ListRefunds(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRefundsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "starting_after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "starting_after", r.URL.Query(), &params.StartingAfter, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "starting_after"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "starting_after", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "ending_before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "ending_before", r.URL.Query(), &params.EndingBefore, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "ending_before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ending_before", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "payment_intent" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "payment_intent", r.URL.Query(), &params.PaymentIntent, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "payment_intent"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "payment_intent", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRefunds(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRefund operation middleware
func (siw *ServerInterfaceWrapper) CreateRefund(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateRefundParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRefund(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRefund operation middleware
func (siw *ServerInterfaceWrapper) GetRefund(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRefund(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompletePaymentIntentAction operation middleware
func (siw *ServerInterfaceWrapper) CompletePaymentIntentAction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CompletePaymentIntentActionParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompletePaymentIntentAction(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWebhookEndpoints operation middleware
func (siw *ServerInterfaceWrapper) ListWebhookEndpoints(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListWebhookEndpointsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "starting_after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "starting_after", r.URL.Query(), &params.StartingAfter, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "starting_after"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "starting_after", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "ending_before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "ending_before", r.URL.Query(), &params.EndingBefore, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "ending_before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ending_before", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWebhookEndpoints(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWebhookEndpoint operation middleware
func (siw *ServerInterfaceWrapper) CreateWebhookEndpoint(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateWebhookEndpointParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWebhookEndpoint(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteWebhookEndpoint operation middleware
func (siw *ServerInterfaceWrapper) DeleteWebhookEndpoint(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteWebhookEndpoint(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWebhookEndpoint operation middleware
func (siw *ServerInterfaceWrapper) GetWebhookEndpoint(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWebhookEndpoint(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateWebhookEndpoint operation middleware
func (siw *ServerInterfaceWrapper) UpdateWebhookEndpoint(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateWebhookEndpointParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateWebhookEndpoint(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RollWebhookEndpointSecret operation middleware
func (siw *ServerInterfaceWrapper) RollWebhookEndpointSecret(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RollWebhookEndpointSecretParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RollWebhookEndpointSecret(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/payment_methods", wrapper.CreatePaymentMethod)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/payment_methods/{id}", wrapper.GetPaymentMethod)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/payment_intents", wrapper.ListPaymentIntents)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/payment_intents", wrapper.CreatePaymentIntent)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/payment_intents/{id}", wrapper.GetPaymentIntent)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/payment_intents/{id}", wrapper.UpdatePaymentIntent)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/payment_intents/{id}/confirm", wrapper.ConfirmPaymentIntent)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/payment_intents/{id}/capture", wrapper.CapturePaymentIntent)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/payment_intents/{id}/cancel", wrapper.CancelPaymentIntent)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/refunds", wrapper.ListRefunds)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/refunds", wrapper.CreateRefund)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/refunds/{id}", wrapper.GetRefund)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/test_helpers/payment_intents/{id}/complete_action", wrapper.CompletePaymentIntentAction)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/api_keys", wrapper.ListApiKeys)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/api_keys", wrapper.CreateApiKey)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/api_keys/{id}", wrapper.GetApiKey)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/api_keys/{id}/revoke", wrapper.RevokeApiKey)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/webhook_endpoints", wrapper.ListWebhookEndpoints)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/webhook_endpoints", wrapper.CreateWebhookEndpoint)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/webhook_endpoints/{id}", wrapper.DeleteWebhookEndpoint)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/webhook_endpoints/{id}", wrapper.GetWebhookEndpoint)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/webhook_endpoints/{id}", wrapper.UpdateWebhookEndpoint)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/webhook_endpoints/{id}/roll_secret", wrapper.RollWebhookEndpointSecret)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/events", wrapper.ListEvents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/events/{id}", wrapper.GetEvent)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/events/{id}/resend", wrapper.ResendEvent)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fzrc9u6cv9XMGxncu4MIys5ObmpM/3gm6Qd9+Y0Hjvt+RB7FIhciTgmAV4AlK1m9L93FgDfoCTLkh+T",
	"+00iSDx2f7vYF/AjiESWCw5cq+D4R5BTSTPQIM2/TzxmfP43mAkJ+D8GFUmWayZ4cByccCKmf0KkCYvf",
	"E50AyekcCPBYkRumE/OIw60mHG5AupdHQRgw/PwfBchlEAacZhAcB2DGmkztYGGgogQyiqPqZY4vKC0Z",
	"nwerVRicfsTnppec6qTuhMVBGEj4R8EkxMGxlgVs6CmGLBcaeLT8OyyrXhOgMci638ZrL/G9ZqcZvf0M",
	"fK6T4Pj1b7+FvkF4lBaxh4LnkFINsaOMIloQCbqQnDCeMg4j8mmBnCE0iiDXRNr3JzUl4TZPRQzlUn2E",
	"ZXb0b1etWTMNmfLQpJo/lZIu8b/SyxQfzITM8P9nljFdUaozWGoamwPFMKNFqoPjV+MQacWyIsM/+I9x",
	"968alXENc5CGbBeaSs34/GSmQW4NP4VfdQEo0ngjAJUbbkLNeOtwswoDCSoXXIGh4X9QlhZWRCLBNXBD",
	"H5rnKYsoTvfoT4Vz/tHo818lzILj4F+OagE8sq3q6JOUQp67Eex47bV/TYAgzEFpMqMshXhkSOY6wP5P",
	"cuYQnUuRg9TMzjWSgBjCn8hRqi3V374J+kwIUaB8GLlm3DQAR/Z9CxREEpDveTFNmUroNAUjifhJhMNd",
	"hf1eUqr0G2//KVtAJmJoNE6FSIHyYFUyzPOZZXBzYjRnk2tYeoeXsBDXA5TgRZqaRTjB6lNGRSIHdTdR",
	"WtC08KgB5OY1LAnTCtJZSHIJCrgmgqdLwriBcYk3ohOqiWMiYQbNfY1Tq8BvVic6yjQo65joqFkyo1pX",
	"WAGlJp3rZBU6cH1mygI9Tb/MguNv60GNb/8OmgarsIvJmOq2UlrXjx27T97Osk2f/blfrcLgA+URpGd0",
	"mQHXp0Zez60wmdXEMUPG0PSsMckZTRWEXVkyHaVGxCcSqBPyEnxxYRUABGEwk7SIixS4djsUKNTk0+Uk",
	"KpQWmdE4dEp5LLhXXFYeNnyguS4k7GElNBMF1xMtJpHt0ysVGxS2Z34y/giaslRtnE9bJD4xnYAkvMim",
	"IAnlMYHbnMllaBU75UTktisSLaKQCEko0eIaOJlJkRmRWeC+Mwq6S40WkVdY4TafZILrpNHakHdsXgKV",
	"/lY7UW+/ZlZ+66NPMJHlKWg4iXBxu7FSFDoSGTSBqIooAogBxd1uF36ANeWn7ObKO00+YzLbA+5y28Uk",
	"A52IeFsqGc1k9cBuw5Y7SMN2MxZJj3nbaPmM8VPb+GqDTnK9XQ2uaW+SfGfxDQMn+A1WVJtooUVGNYuw",
	"D8oLmnr308iiwr9nR4WUaD57KdiS/S5XfGzZBjZNwjuiNKaxkQe/m6533RdkvGkba+rGCuQ1zU0XG4XU",
	"tIbdl7srOodZweMHhlPJIlbZwx4D7J475kb6dCYxTKI/YJoIcf2Jx7lgu4reMIx/86IYOJqY8QQWpfu9",
	"k5IJg0KmXU90/ObdJuLgV71J+Ej0EVLQEH+prOvusk1zg49aFnAVerTAgDtR2+13MWXLcX1TNh5Uf6pR",
	"26doaqAIHe7J8Asimjgy93kDStG5/zsTUBlo6QrIOnXR2hmCVSURkwGSdvUJOkJgiBKiPk+Aa+ebVo9R",
	"i1R/cpAZU6rZzviCpiyelCNXz+vgSPVMUg0TEwxwj7ZWZdY3KUnaWmfNhUGWV05zj/VQImKj492bWncF",
	"jTEXjnUH8LHX+8B9V9cI8ICj2wwbbaKBC0p9qRZZQukusum42fA2S5r0pjNI18dxLy1L7+FdVhPpwSKh",
	"apK5UOo2HE2RAD6G+hVR14AveVENaz/00fu/4VZbn6M/65L9bQetUDDRKJdtZXJMIufCEKbrIBy+SRJI",
	"c5CbAxam1TdLpwP3rtuH9XdnZh3ltGaOp5VSHzKn2uQ8tVGe0jx9oUjGuJCk4EyHRBVRQqgiEXBNF0Ih",
	"DbdQLM6pt4a9jWb9uMN3EiJgC4jv+hUam1t/NRBCGYi/NZyNe3srd9LRTfelzbnP4gbky4gqIKcXX8ib",
	"16/+ShAnHpz3HJ1e+9BWQJWelPZCtZFtpxdbQrO66oY2Te9WkLWGLNdbUX9DfBZu9YRW6mS7eTZUkHeW",
	"ffU4aNyv8xM3Lk1pqgvVHMdpADXp9BbWLc71NShuPndEMI5CBErhGM3PLIiDsBWhsSKxTYxmMLTb93d7",
	"ElOttEelNkx9aqSvIvri38OVF8ZtsPjVwfpQdEvhPo7J0LPNdzUdWqEHzw63RVih1QXGGO6u6/Zkj3ZQ",
	"5RPP3YIeg6hvRkO2Ak2DSj1iTxn3Z2pmTCpNgM0TTWI2Z1oRMSO0jFWLGVHsVgNwDEpnQkJIIDWJm/Jb",
	"xW69u8NU0nZabcEUNbuY0iDdsmgGt0EYQCqCMEhYXjUU/JqLG+4l9L1i2zPG5yBzybj2U0TRDMhMSKLL",
	"PzilKngfSaEU0QlTJAMZJZTrF4o4eBALD+UlyFCCsAMIS7fQsKxOZNVrbiywvRofNGywbJ3lto25sLNx",
	"0aPBzOaW72Ib7UmArSpfu69uFdzbYcvNbTVIZ2PcNnVxp22xs5Rq4o39scOC9arF4udxNiI79n12oLbz",
	"35P2PzD5jFJugg2EKUKnotB1nYpEPcf4MZmBjqzvZ7s3+gF1pSW9JkhdCC/RyaHq2jW7uhfrOFaFK//e",
	"qXu55L2k3sbAoj+MawHZ12j2uxfd2ZKbBHg5r9ikJRm2sTQlcMuUbqoxsSmAsqUfb9DstrYh//0cFPDY",
	"MGG30PWNjX9PwAXAt8zEnYs0vYBIwo7DmqQuTByVJ6yMm9u8wtvxm3etOqHxdmnn/8njR86lHSShNbDO",
	"55266Ot+13UQBjFT9ueaGNgWOY8e3ToU8+z1OZssQKohN/1u2/smp/8utOySb09bfU/8fRR3RV5+E5DN",
	"OeNzYt/plDBZranJDVXkz0LV5UtCEilSU722lVlwN2jsaCTYtFjbBe6wqGEbNKGy3jDooO5xLIQu9Hc2",
	"FSweCsn08gL7dk4TUAnypLCOhhnUYM88rnmcaJ3bskbGZ6KPqP8qcqZBvqgdBnJydmqsDLmsS+HsR1NQ",
	"ttzHcqEEmgQeg8QaOW7MiUuOL7meX/6ve9kW+r633kksosL4JO2OSxvADTC65Jf8pI56O2uFOuwbUFd1",
	"j6aujypCiaWBrVEakb/DUqGQzNgtxJf8u42lfyc0Qpkx8fKXiEeCDDCGxvcJYnTyHZvxV91si1/1jSAc",
	"FiBJxm7NHC21zr5cfHX1wwrrpjqlzI4CI3JCJGi5rGP2xpEz0+dx9eCST0W8dFXKquHTVkzB70WhcSWo",
	"EOicMv6+3aGjV8xmM0DKuk4ZMm1WKIithaeZNoXHjmcIgSAMKr0cvB6/fvty/G8vfx0bpZYDpzkLjoNf",
	"R+PRr8ay14lB5dHi1ZErBDX/51aLoRCZQNNpjHFcprQtKbIhsboOfkA061eObEn0Ktz4YrukeYsPWhX4",
	"GBdt1R2/Ho/3VnPcKOn0FByf2OJqMUMGqtBU9CtteT+ym5wr8/aPUk37qKyVxjE0nSN9g5OzU9NvgC5I",
	"LpRnk7FlGihIbeEakVOtiCmstQBCYEJsNx5TO2ue2tFxm2lzvVlKdme2dw4PWPYY6+tvIl7ujTO+crdV",
	"W1G7GPmBwTFUic7hBlnhajNZyY+94mIVtsT46AeLV4Oy/J+gd2Xpx4eQsiFCIp4PTbQjW/aOfZeS1ibe",
	"uWm/B/3C3QTnUSjuzgAcivK1ST+453wqTcqnueWE/nM+Lh6x5mjVZhC4U1EH5X5dSLJ2U7N82ve25ljb",
	"QcNG1WU+O5TkPRjRhyTOEOGgtD0yvmfc1HDtaXwENKClakQyjZka4gE8wc0RRuMeoS2vBb4il/VDVUyt",
	"exBjI253CP6+bdEIyj2kHt2/AeKJLq76h+CeO4LaiYD1SrsVW/w5/YV+3n2thi3TfY66+1a1Z+3ut3Ik",
	"2lMKjZ/rCjkURhEouuIR2PCVa0AfQ8sC0F82SU6dUH3JXYkZOtjqBjXLm/Hr2pMuB+DihkxpdI1+yUBR",
	"ifV8fT5Ki95P21XxRt4f2GPp1GT4NUkbAYdAoV+3bDQB7snsjw8o+o9H20EJTyifeySc2LsFTJpRlQJt",
	"Y89tBnjyR897A1+TEPunWHbE8siWoA1bj/b0sG8DWQiGu68xCbEsWkj2f4ZIhM0QdQlVaF56olD9A8nP",
	"G3BrTlgf2HJ8FgCrTlgPIcy8oAhNU3RBciq1qTHjbVi9L28G0Db0mQJVPn3mOyb+3PE1fPD9nwBrHMT1",
	"A+yrZGBum8npckS+ViaqvbunaZ06rJJfbCU9cf//EpKqMOuS/1KV3P8lJJ3aZ3M0f4PRWyaEjNGcALep",
	"OmNel4b1iPyBVjg+l5SlL0pLG4GfCqVDW4hDl2b6dbU1Kbhm6SUvc0gp0DJv5Q64W7ufEpcCJxJyITU6",
	"AF5b3HPy/ZmL0pqz/D+lKFlMqmHpuaALY10iQEN73QTu+GX9r7SPyusoqpsoCFOqsDEjgzbjGttkcvmt",
	"KZlIQOKqlTLpZymKeULqhDjGmE2SW5EbusTOqgGwPI1FySXPC20h3ii3VSAxN8w4OftwSj5eXBBzGQH6",
	"sXae1wC5cXtFoY8b1ymhSmgIZHPAF8p+W1o5UhRlNtx8X98FZNNDLpF8yd1kTN82U4fv23ng8kfkK/5W",
	"JMNqkSmQKKUsA6soGMeNMBGFLC8DueQu9Y7JZTGrk81V9QCObPLlVPmmttHr/r08GfH0ve72vQWPY947",
	"cm2QaBfx2JtEl4I7JNHbet27MvthvO4nQltbHL4+Snru3nlmua1eRfhwluuQ/G4Ukq+NrDpO7DuiWjJv",
	"OM7i3uh5KbVp2Nu8/UrWdvS0tWv7DpUHVqtlXf9QDhtb98nxtoxv1Ju78u/ACvORqGYq+exZdzXkn9kj",
	"8o0zsgN+GsqzsVvQSBqRs5QurQGDtlhibrU0R6kkipipjWo5X07ujpvOmgRVZK6ysRVNCN1Nkq3iPucX",
	"alF3vUXCwq2vZd+fVEdhn7Ov5Lue7WcIoX6tL3BoQL1bNr7eHOjUHv+caVNfFfja7b2i7b43eDeTeoBt",
	"kqa8et0WXrbr/nevwOyQ5WnbAgMnbh5YD/RK+YeLM0ueNSo0LcMOg6Ih7VAZEvbmrr6WsBeN3RsLB7Yr",
	"2tehDZC9XLQ5i2DXGx9KZofssqdOyC0RXGmcA6s8XxJ4HyR8YmngZ6W9CjPl+MAYWKuwjvCI2qQ+/Obf",
	"IU+VKkxUGPVte1cckQ/lKWLzX5lYa/XSFBSLTVXCTMhL3jsSi18J9LN/cesm796+GY9DrE/KhNLEHpPF",
	"lIwg7kIWqUhEOVE3TGNAuDyTY270w0M5qJHwNW/kEw/1dthzUd3v/oyrGHtnlQ+c3rijemtszgZDh9yg",
	"G6f3DB+b5/a+XSEHbIjectmcpzSH9o6Pjl69/utoPBqPXh2/G78bG265ocprlXtBw1XYayqzL42m0pFu",
	"PGp5HY3nVaF941l/nY1GV+u5ulr9/wA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
