// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const abandonedIdempotencyKeys = `-- name: AbandonedIdempotencyKeys :many
WITH stale AS (SELECT $3::timestamptz AS before)
SELECT k.id FROM api.idempotency_keys k, stale
WHERE k.response_status IS NULL AND k.recovery_point <> 'started' AND k.completer_runs < $1::integer
  AND ((k.locked_at IS NOT NULL AND k.locked_at < stale.before)
       OR (k.locked_at IS NULL AND k.last_run_at < stale.before))
  AND k.last_run_at < stale.before - least(power(2, k.completer_runs), 60) * interval '1 minute'
ORDER BY k.last_run_at
LIMIT $2::integer
`

type AbandonedIdempotencyKeysParams struct {
	MaxRuns     int32
	MaxCount    int32
	StaleBefore pgtype.Timestamptz
}

// Keys whose request committed some work and then stopped: the runner died while it
// held the lock, or failed and released it. Keys still at 'started' did nothing and
// are left for the client to retry.
// Each run of the completer waits longer before the next, up to an hour, so that a
// request held up by an outage of a counterparty outlasts a day of it.
func (q *Queries) AbandonedIdempotencyKeys(ctx context.Context, arg AbandonedIdempotencyKeysParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, abandonedIdempotencyKeys, arg.MaxRuns, arg.MaxCount, arg.StaleBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const advanceIdempotencyKey = `-- name: AdvanceIdempotencyKey :exec
UPDATE api.idempotency_keys SET recovery_point = $1, recovery_state = $2
WHERE id = $3 AND lock_token = $4
`

type AdvanceIdempotencyKeyParams struct {
	RecoveryPoint string
	RecoveryState []byte
	ID            int64
	LockToken     pgtype.UUID
}

func (q *Queries) AdvanceIdempotencyKey(ctx context.Context, arg AdvanceIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, advanceIdempotencyKey,
		arg.RecoveryPoint,
		arg.RecoveryState,
		arg.ID,
		arg.LockToken,
	)
	return err
}

const checkIdempotencyLock = `-- name: CheckIdempotencyLock :one
SELECT recovery_point FROM api.idempotency_keys WHERE id = $1 AND lock_token = $2 FOR UPDATE
`

type CheckIdempotencyLockParams struct {
	ID        int64
	LockToken pgtype.UUID
}

func (q *Queries) CheckIdempotencyLock(ctx context.Context, arg CheckIdempotencyLockParams) (string, error) {
	row := q.db.QueryRow(ctx, checkIdempotencyLock, arg.ID, arg.LockToken)
	var recovery_point string
	err := row.Scan(&recovery_point)
	return recovery_point, err
}

const countCompleterRun = `-- name: CountCompleterRun :exec
UPDATE api.idempotency_keys SET completer_runs = completer_runs + 1 WHERE id = $1
`

func (q *Queries) CountCompleterRun(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, countCompleterRun, id)
	return err
}

const finishIdempotencyKey = `-- name: FinishIdempotencyKey :execrows
UPDATE api.idempotency_keys
SET recovery_point = 'finished', response_status = $1, response_body = $2,
    lock_token = NULL, locked_at = NULL
WHERE id = $3 AND lock_token = $4
`

type FinishIdempotencyKeyParams struct {
	ResponseStatus pgtype.Int4
	ResponseBody   []byte
	ID             int64
	LockToken      pgtype.UUID
}

func (q *Queries) FinishIdempotencyKey(ctx context.Context, arg FinishIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishIdempotencyKey,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ID,
		arg.LockToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const health = `-- name: Health :one
SELECT count(*)::bigint FROM api.idempotency_keys WHERE response_status IS NULL AND last_run_at < $1::timestamptz
`

// Requests that stopped between phases and have waited longer than the completer should
// take to finish them.
func (q *Queries) Health(ctx context.Context, before pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, health, before)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :one
INSERT INTO api.idempotency_keys (
    merchant_id, livemode, key, fingerprint, operation, path_id, request_body, api_version,
    key_id, key_kind, key_scopes, recovery_point, lock_token, locked_at, created_at, last_run_at, request_sealed
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, 'started', $12, $13::timestamptz, $13::timestamptz, $13::timestamptz, true
)
ON CONFLICT (merchant_id, livemode, key) DO NOTHING
RETURNING id
`

type InsertIdempotencyKeyParams struct {
	MerchantID  string
	Livemode    bool
	Key         string
	Fingerprint []byte
	Operation   string
	PathID      string
	RequestBody []byte
	ApiVersion  string
	KeyID       string
	KeyKind     string
	KeyScopes   []string
	LockToken   pgtype.UUID
	Now         pgtype.Timestamptz
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertIdempotencyKey,
		arg.MerchantID,
		arg.Livemode,
		arg.Key,
		arg.Fingerprint,
		arg.Operation,
		arg.PathID,
		arg.RequestBody,
		arg.ApiVersion,
		arg.KeyID,
		arg.KeyKind,
		arg.KeyScopes,
		arg.LockToken,
		arg.Now,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lockIdempotencyKeyByID = `-- name: LockIdempotencyKeyByID :one
SELECT id, merchant_id, livemode, key, fingerprint, operation, path_id, request_body, api_version, key_id, key_kind, key_scopes, recovery_point, lock_token, locked_at, response_status, response_body, created_at, last_run_at, recovery_state, completer_runs, request_sealed FROM api.idempotency_keys WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockIdempotencyKeyByID(ctx context.Context, id int64) (ApiIdempotencyKey, error) {
	row := q.db.QueryRow(ctx, lockIdempotencyKeyByID, id)
	var i ApiIdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Key,
		&i.Fingerprint,
		&i.Operation,
		&i.PathID,
		&i.RequestBody,
		&i.ApiVersion,
		&i.KeyID,
		&i.KeyKind,
		&i.KeyScopes,
		&i.RecoveryPoint,
		&i.LockToken,
		&i.LockedAt,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.LastRunAt,
		&i.RecoveryState,
		&i.CompleterRuns,
		&i.RequestSealed,
	)
	return i, err
}

const lockIdempotencyKeyRow = `-- name: LockIdempotencyKeyRow :one
SELECT id, merchant_id, livemode, key, fingerprint, operation, path_id, request_body, api_version, key_id, key_kind, key_scopes, recovery_point, lock_token, locked_at, response_status, response_body, created_at, last_run_at, recovery_state, completer_runs, request_sealed FROM api.idempotency_keys
WHERE merchant_id = $1 AND livemode = $2 AND key = $3
FOR UPDATE
`

type LockIdempotencyKeyRowParams struct {
	MerchantID string
	Livemode   bool
	Key        string
}

func (q *Queries) LockIdempotencyKeyRow(ctx context.Context, arg LockIdempotencyKeyRowParams) (ApiIdempotencyKey, error) {
	row := q.db.QueryRow(ctx, lockIdempotencyKeyRow, arg.MerchantID, arg.Livemode, arg.Key)
	var i ApiIdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Key,
		&i.Fingerprint,
		&i.Operation,
		&i.PathID,
		&i.RequestBody,
		&i.ApiVersion,
		&i.KeyID,
		&i.KeyKind,
		&i.KeyScopes,
		&i.RecoveryPoint,
		&i.LockToken,
		&i.LockedAt,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.LastRunAt,
		&i.RecoveryState,
		&i.CompleterRuns,
		&i.RequestSealed,
	)
	return i, err
}

const reapIdempotencyKeys = `-- name: ReapIdempotencyKeys :execrows
DELETE FROM api.idempotency_keys
WHERE created_at < $1::timestamptz
  AND (response_status IS NOT NULL OR recovery_point = 'started')
  AND locked_at IS NULL
`

func (q *Queries) ReapIdempotencyKeys(ctx context.Context, createdBefore pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, reapIdempotencyKeys, createdBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseIdempotencyKey = `-- name: ReleaseIdempotencyKey :exec
UPDATE api.idempotency_keys SET lock_token = NULL, locked_at = NULL WHERE id = $1 AND lock_token = $2
`

type ReleaseIdempotencyKeyParams struct {
	ID        int64
	LockToken pgtype.UUID
}

func (q *Queries) ReleaseIdempotencyKey(ctx context.Context, arg ReleaseIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, releaseIdempotencyKey, arg.ID, arg.LockToken)
	return err
}

const releaseStaleStartedKeys = `-- name: ReleaseStaleStartedKeys :exec
UPDATE api.idempotency_keys SET lock_token = NULL, locked_at = NULL
WHERE response_status IS NULL AND recovery_point = 'started' AND locked_at < $1::timestamptz
`

func (q *Queries) ReleaseStaleStartedKeys(ctx context.Context, staleBefore pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, releaseStaleStartedKeys, staleBefore)
	return err
}

const takeIdempotencyLock = `-- name: TakeIdempotencyLock :exec
UPDATE api.idempotency_keys
SET lock_token = $1, locked_at = $2::timestamptz, last_run_at = $2::timestamptz
WHERE id = $3
`

type TakeIdempotencyLockParams struct {
	LockToken pgtype.UUID
	Now       pgtype.Timestamptz
	ID        int64
}

func (q *Queries) TakeIdempotencyLock(ctx context.Context, arg TakeIdempotencyLockParams) error {
	_, err := q.db.Exec(ctx, takeIdempotencyLock, arg.LockToken, arg.Now, arg.ID)
	return err
}
