// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const abandonedIdempotencyKeys = `-- name: AbandonedIdempotencyKeys :many
SELECT id FROM api.idempotency_keys
WHERE response_status IS NULL AND recovery_point <> 'started'
  AND ((locked_at IS NOT NULL AND locked_at < $1::timestamptz)
       OR (locked_at IS NULL AND last_run_at < $1::timestamptz))
ORDER BY last_run_at
LIMIT $2::integer
`

type AbandonedIdempotencyKeysParams struct {
	StaleBefore pgtype.Timestamptz
	MaxCount    int32
}

// Keys whose request committed some work and then stopped: the runner died while it
// held the lock, or failed and released it. Keys still at 'started' did nothing and
// are left for the client to retry.
func (q *Queries) AbandonedIdempotencyKeys(ctx context.Context, arg AbandonedIdempotencyKeysParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, abandonedIdempotencyKeys, arg.StaleBefore, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const advanceIdempotencyKey = `-- name: AdvanceIdempotencyKey :exec
UPDATE api.idempotency_keys SET recovery_point = $1 WHERE id = $2 AND lock_token = $3
`

type AdvanceIdempotencyKeyParams struct {
	RecoveryPoint string
	ID            int64
	LockToken     pgtype.UUID
}

func (q *Queries) AdvanceIdempotencyKey(ctx context.Context, arg AdvanceIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, advanceIdempotencyKey, arg.RecoveryPoint, arg.ID, arg.LockToken)
	return err
}

const checkIdempotencyLock = `-- name: CheckIdempotencyLock :one
SELECT recovery_point FROM api.idempotency_keys WHERE id = $1 AND lock_token = $2 FOR UPDATE
`

type CheckIdempotencyLockParams struct {
	ID        int64
	LockToken pgtype.UUID
}

func (q *Queries) CheckIdempotencyLock(ctx context.Context, arg CheckIdempotencyLockParams) (string, error) {
	row := q.db.QueryRow(ctx, checkIdempotencyLock, arg.ID, arg.LockToken)
	var recovery_point string
	err := row.Scan(&recovery_point)
	return recovery_point, err
}

const finishIdempotencyKey = `-- name: FinishIdempotencyKey :execrows
UPDATE api.idempotency_keys
SET recovery_point = 'finished', response_status = $1, response_body = $2,
    lock_token = NULL, locked_at = NULL
WHERE id = $3 AND lock_token = $4
`

type FinishIdempotencyKeyParams struct {
	ResponseStatus pgtype.Int4
	ResponseBody   []byte
	ID             int64
	LockToken      pgtype.UUID
}

func (q *Queries) FinishIdempotencyKey(ctx context.Context, arg FinishIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishIdempotencyKey,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ID,
		arg.LockToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :one
INSERT INTO api.idempotency_keys (
    merchant_id, livemode, key, fingerprint, operation, path_id, request_body, api_version,
    key_id, key_kind, key_scopes, recovery_point, lock_token, locked_at, created_at, last_run_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, 'started', $12, $13::timestamptz, $13::timestamptz, $13::timestamptz
)
ON CONFLICT (merchant_id, livemode, key) DO NOTHING
RETURNING id
`

type InsertIdempotencyKeyParams struct {
	MerchantID  string
	Livemode    bool
	Key         string
	Fingerprint []byte
	Operation   string
	PathID      string
	RequestBody []byte
	ApiVersion  string
	KeyID       string
	KeyKind     string
	KeyScopes   []string
	LockToken   pgtype.UUID
	Now         pgtype.Timestamptz
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertIdempotencyKey,
		arg.MerchantID,
		arg.Livemode,
		arg.Key,
		arg.Fingerprint,
		arg.Operation,
		arg.PathID,
		arg.RequestBody,
		arg.ApiVersion,
		arg.KeyID,
		arg.KeyKind,
		arg.KeyScopes,
		arg.LockToken,
		arg.Now,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lockIdempotencyKeyByID = `-- name: LockIdempotencyKeyByID :one
SELECT id, merchant_id, livemode, key, fingerprint, operation, path_id, request_body, api_version, key_id, key_kind, key_scopes, recovery_point, lock_token, locked_at, response_status, response_body, created_at, last_run_at FROM api.idempotency_keys WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockIdempotencyKeyByID(ctx context.Context, id int64) (ApiIdempotencyKey, error) {
	row := q.db.QueryRow(ctx, lockIdempotencyKeyByID, id)
	var i ApiIdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Key,
		&i.Fingerprint,
		&i.Operation,
		&i.PathID,
		&i.RequestBody,
		&i.ApiVersion,
		&i.KeyID,
		&i.KeyKind,
		&i.KeyScopes,
		&i.RecoveryPoint,
		&i.LockToken,
		&i.LockedAt,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.LastRunAt,
	)
	return i, err
}

const lockIdempotencyKeyRow = `-- name: LockIdempotencyKeyRow :one
SELECT id, merchant_id, livemode, key, fingerprint, operation, path_id, request_body, api_version, key_id, key_kind, key_scopes, recovery_point, lock_token, locked_at, response_status, response_body, created_at, last_run_at FROM api.idempotency_keys
WHERE merchant_id = $1 AND livemode = $2 AND key = $3
FOR UPDATE
`

type LockIdempotencyKeyRowParams struct {
	MerchantID string
	Livemode   bool
	Key        string
}

func (q *Queries) LockIdempotencyKeyRow(ctx context.Context, arg LockIdempotencyKeyRowParams) (ApiIdempotencyKey, error) {
	row := q.db.QueryRow(ctx, lockIdempotencyKeyRow, arg.MerchantID, arg.Livemode, arg.Key)
	var i ApiIdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Key,
		&i.Fingerprint,
		&i.Operation,
		&i.PathID,
		&i.RequestBody,
		&i.ApiVersion,
		&i.KeyID,
		&i.KeyKind,
		&i.KeyScopes,
		&i.RecoveryPoint,
		&i.LockToken,
		&i.LockedAt,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.LastRunAt,
	)
	return i, err
}

const reapIdempotencyKeys = `-- name: ReapIdempotencyKeys :execrows
DELETE FROM api.idempotency_keys
WHERE created_at < $1::timestamptz
  AND (response_status IS NOT NULL OR recovery_point = 'started')
  AND locked_at IS NULL
`

func (q *Queries) ReapIdempotencyKeys(ctx context.Context, createdBefore pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, reapIdempotencyKeys, createdBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseIdempotencyKey = `-- name: ReleaseIdempotencyKey :exec
UPDATE api.idempotency_keys SET lock_token = NULL, locked_at = NULL WHERE id = $1 AND lock_token = $2
`

type ReleaseIdempotencyKeyParams struct {
	ID        int64
	LockToken pgtype.UUID
}

func (q *Queries) ReleaseIdempotencyKey(ctx context.Context, arg ReleaseIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, releaseIdempotencyKey, arg.ID, arg.LockToken)
	return err
}

const releaseStaleStartedKeys = `-- name: ReleaseStaleStartedKeys :exec
UPDATE api.idempotency_keys SET lock_token = NULL, locked_at = NULL
WHERE response_status IS NULL AND recovery_point = 'started' AND locked_at < $1::timestamptz
`

func (q *Queries) ReleaseStaleStartedKeys(ctx context.Context, staleBefore pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, releaseStaleStartedKeys, staleBefore)
	return err
}

const takeIdempotencyLock = `-- name: TakeIdempotencyLock :exec
UPDATE api.idempotency_keys
SET lock_token = $1, locked_at = $2::timestamptz, last_run_at = $2::timestamptz
WHERE id = $3
`

type TakeIdempotencyLockParams struct {
	LockToken pgtype.UUID
	Now       pgtype.Timestamptz
	ID        int64
}

func (q *Queries) TakeIdempotencyLock(ctx context.Context, arg TakeIdempotencyLockParams) error {
	_, err := q.db.Exec(ctx, takeIdempotencyLock, arg.LockToken, arg.Now, arg.ID)
	return err
}
