// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LedgerAccount struct {
	ID          string
	Book        string
	Code        string
	Currency    string
	Normal      string
	NonNegative bool
	Batched     bool
	Clearing    bool
	CreatedAt   pgtype.Timestamptz
}

type LedgerBalance struct {
	AccountID      string
	Normal         string
	NonNegative    bool
	Batched        bool
	PostedDebits   int64
	PostedCredits  int64
	PendingDebits  int64
	PendingCredits int64
	DriftedAt      pgtype.Timestamptz
}

type LedgerBalanceQueue struct {
	EntrySeq       int64
	AccountID      string
	PostedDebits   int64
	PostedCredits  int64
	PendingDebits  int64
	PendingCredits int64
}

type LedgerEntry struct {
	Seq             int64
	TransactionID   string
	TransactionKind string
	AccountID       string
	Book            string
	Currency        string
	Layer           string
	Amount          int64
}

type LedgerTransaction struct {
	ID           string
	Kind         string
	ResolvesID   pgtype.Text
	ResolvesKind pgtype.Text
	ReversesID   pgtype.Text
	ExpiresAt    pgtype.Timestamptz
	EntryCount   int32
	Description  string
	CreatedAt    pgtype.Timestamptz
}
