// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyQueuedDeltas = `-- name: ApplyQueuedDeltas :one
WITH batch AS (
    DELETE FROM ledger.balance_queue
    WHERE entry_seq IN (SELECT entry_seq FROM ledger.balance_queue ORDER BY entry_seq LIMIT $1::integer)
    RETURNING account_id, posted_debits, posted_credits, pending_debits, pending_credits
), sums AS (
    SELECT account_id, count(*) AS n,
           sum(posted_debits)::bigint AS posted_debits, sum(posted_credits)::bigint AS posted_credits,
           sum(pending_debits)::bigint AS pending_debits, sum(pending_credits)::bigint AS pending_credits
    FROM batch
    GROUP BY account_id
), applied AS (
    UPDATE ledger.balances b
       SET posted_debits   = b.posted_debits + s.posted_debits,
           posted_credits  = b.posted_credits + s.posted_credits,
           pending_debits  = b.pending_debits + s.pending_debits,
           pending_credits = b.pending_credits + s.pending_credits
      FROM sums s
     WHERE b.account_id = s.account_id
    RETURNING s.n
)
SELECT coalesce(sum(n), 0)::bigint FROM applied
`

// Applies the oldest queued deltas in entry order, in one statement: the rows are
// deleted and their sums added to the cached balances atomically.
func (q *Queries) ApplyQueuedDeltas(ctx context.Context, maxCount int32) (int64, error) {
	row := q.db.QueryRow(ctx, applyQueuedDeltas, maxCount)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const balanceMismatches = `-- name: BalanceMismatches :many
WITH recomputed AS (
    SELECT e.account_id,
           sum(d.posted_debits)::bigint AS posted_debits, sum(d.posted_credits)::bigint AS posted_credits,
           sum(d.pending_debits)::bigint AS pending_debits, sum(d.pending_credits)::bigint AS pending_credits
    FROM ledger.entries e
    CROSS JOIN LATERAL ledger.entry_deltas(e.transaction_kind, e.layer, e.amount) d
    GROUP BY e.account_id
), queued AS (
    SELECT account_id,
           sum(posted_debits)::bigint AS posted_debits, sum(posted_credits)::bigint AS posted_credits,
           sum(pending_debits)::bigint AS pending_debits, sum(pending_credits)::bigint AS pending_credits
    FROM ledger.balance_queue
    GROUP BY account_id
)
SELECT b.account_id,
       (b.posted_debits + coalesce(q.posted_debits, 0))::bigint     AS cached_posted_debits,
       (b.posted_credits + coalesce(q.posted_credits, 0))::bigint   AS cached_posted_credits,
       (b.pending_debits + coalesce(q.pending_debits, 0))::bigint   AS cached_pending_debits,
       (b.pending_credits + coalesce(q.pending_credits, 0))::bigint AS cached_pending_credits,
       coalesce(r.posted_debits, 0)::bigint   AS posted_debits,
       coalesce(r.posted_credits, 0)::bigint  AS posted_credits,
       coalesce(r.pending_debits, 0)::bigint  AS pending_debits,
       coalesce(r.pending_credits, 0)::bigint AS pending_credits
FROM ledger.balances b
LEFT JOIN recomputed r ON r.account_id = b.account_id
LEFT JOIN queued q ON q.account_id = b.account_id
WHERE ($1::text[] IS NULL OR b.account_id = ANY($1::text[]))
  AND (b.posted_debits + coalesce(q.posted_debits, 0), b.posted_credits + coalesce(q.posted_credits, 0),
       b.pending_debits + coalesce(q.pending_debits, 0), b.pending_credits + coalesce(q.pending_credits, 0))
      IS DISTINCT FROM
      (coalesce(r.posted_debits, 0), coalesce(r.posted_credits, 0),
       coalesce(r.pending_debits, 0), coalesce(r.pending_credits, 0))
ORDER BY b.account_id
`

type BalanceMismatchesRow struct {
	AccountID            string
	CachedPostedDebits   int64
	CachedPostedCredits  int64
	CachedPendingDebits  int64
	CachedPendingCredits int64
	PostedDebits         int64
	PostedCredits        int64
	PendingDebits        int64
	PendingCredits       int64
}

func (q *Queries) BalanceMismatches(ctx context.Context, only []string) ([]BalanceMismatchesRow, error) {
	rows, err := q.db.Query(ctx, balanceMismatches, only)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BalanceMismatchesRow{}
	for rows.Next() {
		var i BalanceMismatchesRow
		if err := rows.Scan(
			&i.AccountID,
			&i.CachedPostedDebits,
			&i.CachedPostedCredits,
			&i.CachedPendingDebits,
			&i.CachedPendingCredits,
			&i.PostedDebits,
			&i.PostedCredits,
			&i.PendingDebits,
			&i.PendingCredits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearingAccountsNotAtZero = `-- name: ClearingAccountsNotAtZero :many
SELECT a.id, sum(e.amount)::bigint AS posted_balance, max(t.created_at)::timestamptz AS last_activity
FROM ledger.accounts a
JOIN ledger.entries e ON e.account_id = a.id AND e.layer = 'posted'
JOIN ledger.transactions t ON t.id = e.transaction_id
WHERE a.clearing
GROUP BY a.id
HAVING sum(e.amount) <> 0 AND max(t.created_at) < $1::timestamptz
ORDER BY a.id
`

type ClearingAccountsNotAtZeroRow struct {
	ID            string
	PostedBalance int64
	LastActivity  pgtype.Timestamptz
}

func (q *Queries) ClearingAccountsNotAtZero(ctx context.Context, settledBefore pgtype.Timestamptz) ([]ClearingAccountsNotAtZeroRow, error) {
	rows, err := q.db.Query(ctx, clearingAccountsNotAtZero, settledBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClearingAccountsNotAtZeroRow{}
	for rows.Next() {
		var i ClearingAccountsNotAtZeroRow
		if err := rows.Scan(&i.ID, &i.PostedBalance, &i.LastActivity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const duePendingTransfers = `-- name: DuePendingTransfers :many
SELECT t.id
FROM ledger.transactions t
WHERE t.kind = 'pending'
  AND t.expires_at <= $1::timestamptz
  AND NOT EXISTS (SELECT 1 FROM ledger.transactions r WHERE r.resolves_id = t.id)
ORDER BY t.expires_at, t.id
LIMIT $2::integer
`

type DuePendingTransfersParams struct {
	Now      pgtype.Timestamptz
	MaxCount int32
}

func (q *Queries) DuePendingTransfers(ctx context.Context, arg DuePendingTransfersParams) ([]string, error) {
	rows, err := q.db.Query(ctx, duePendingTransfers, arg.Now, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccounts = `-- name: GetAccounts :many
SELECT id, book, code, currency, normal, non_negative, batched, clearing, created_at
FROM ledger.accounts
WHERE id = ANY($1::text[])
`

func (q *Queries) GetAccounts(ctx context.Context, ids []string) ([]LedgerAccount, error) {
	rows, err := q.db.Query(ctx, getAccounts, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerAccount{}
	for rows.Next() {
		var i LedgerAccount
		if err := rows.Scan(
			&i.ID,
			&i.Book,
			&i.Code,
			&i.Currency,
			&i.Normal,
			&i.NonNegative,
			&i.Batched,
			&i.Clearing,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBalance = `-- name: GetBalance :one
SELECT b.account_id, b.drifted_at, a.currency, a.normal,
       (b.posted_debits + coalesce(q.posted_debits, 0))::bigint     AS posted_debits,
       (b.posted_credits + coalesce(q.posted_credits, 0))::bigint   AS posted_credits,
       (b.pending_debits + coalesce(q.pending_debits, 0))::bigint   AS pending_debits,
       (b.pending_credits + coalesce(q.pending_credits, 0))::bigint AS pending_credits
FROM ledger.balances b
JOIN ledger.accounts a ON a.id = b.account_id
LEFT JOIN LATERAL (
    SELECT sum(posted_debits) AS posted_debits, sum(posted_credits) AS posted_credits,
           sum(pending_debits) AS pending_debits, sum(pending_credits) AS pending_credits
    FROM ledger.balance_queue
    WHERE account_id = b.account_id
) q ON true
WHERE b.account_id = $1
`

type GetBalanceRow struct {
	AccountID      string
	DriftedAt      pgtype.Timestamptz
	Currency       string
	Normal         string
	PostedDebits   int64
	PostedCredits  int64
	PendingDebits  int64
	PendingCredits int64
}

func (q *Queries) GetBalance(ctx context.Context, accountID string) (GetBalanceRow, error) {
	row := q.db.QueryRow(ctx, getBalance, accountID)
	var i GetBalanceRow
	err := row.Scan(
		&i.AccountID,
		&i.DriftedAt,
		&i.Currency,
		&i.Normal,
		&i.PostedDebits,
		&i.PostedCredits,
		&i.PendingDebits,
		&i.PendingCredits,
	)
	return i, err
}

const getEntries = `-- name: GetEntries :many
SELECT seq, transaction_id, transaction_kind, account_id, book, currency, layer, amount
FROM ledger.entries
WHERE transaction_id = $1
ORDER BY seq
`

func (q *Queries) GetEntries(ctx context.Context, transactionID string) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, getEntries, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.Seq,
			&i.TransactionID,
			&i.TransactionKind,
			&i.AccountID,
			&i.Book,
			&i.Currency,
			&i.Layer,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResolution = `-- name: GetResolution :one
SELECT id, kind FROM ledger.transactions WHERE resolves_id = $1
`

type GetResolutionRow struct {
	ID   string
	Kind string
}

func (q *Queries) GetResolution(ctx context.Context, resolvesID pgtype.Text) (GetResolutionRow, error) {
	row := q.db.QueryRow(ctx, getResolution, resolvesID)
	var i GetResolutionRow
	err := row.Scan(&i.ID, &i.Kind)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, kind, resolves_id, reverses_id, expires_at, entry_count, description, created_at
FROM ledger.transactions
WHERE id = $1
`

type GetTransactionRow struct {
	ID          string
	Kind        string
	ResolvesID  pgtype.Text
	ReversesID  pgtype.Text
	ExpiresAt   pgtype.Timestamptz
	EntryCount  int32
	Description string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetTransaction(ctx context.Context, id string) (GetTransactionRow, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i GetTransactionRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ResolvesID,
		&i.ReversesID,
		&i.ExpiresAt,
		&i.EntryCount,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const health = `-- name: Health :one
SELECT
    (SELECT count(*) FROM ledger.balance_queue)::bigint AS queued,
    (SELECT t.created_at FROM ledger.balance_queue q
     JOIN ledger.entries e ON e.seq = q.entry_seq JOIN ledger.transactions t ON t.id = e.transaction_id
     ORDER BY q.entry_seq LIMIT 1)::timestamptz AS oldest_queued,
    (SELECT count(*) FROM ledger.balances WHERE drifted_at IS NOT NULL)::bigint AS drifted
`

type HealthRow struct {
	Queued       int64
	OldestQueued pgtype.Timestamptz
	Drifted      int64
}

// The batched balance deltas not yet applied, when the oldest was posted, and the
// accounts the checker found drifted.
func (q *Queries) Health(ctx context.Context) (HealthRow, error) {
	row := q.db.QueryRow(ctx, health)
	var i HealthRow
	err := row.Scan(&i.Queued, &i.OldestQueued, &i.Drifted)
	return i, err
}

const inconsistentLinks = `-- name: InconsistentLinks :many
SELECT l.id, l.kind
FROM ledger.transactions l
WHERE (l.resolves_id IS NOT NULL OR l.reverses_id IS NOT NULL)
  AND EXISTS (
      SELECT 1
      FROM ledger.entries e
      WHERE e.transaction_id IN (l.id, coalesce(l.resolves_id, l.reverses_id))
        AND e.layer = CASE WHEN l.resolves_id IS NOT NULL THEN 'pending' ELSE 'posted' END
      GROUP BY e.account_id
      HAVING sum(e.amount) <> 0
  )
ORDER BY l.id
`

type InconsistentLinksRow struct {
	ID   string
	Kind string
}

// A resolution must release exactly its hold, and a reversal must exactly cancel the
// posted entries of what it reverses, account by account.
func (q *Queries) InconsistentLinks(ctx context.Context) ([]InconsistentLinksRow, error) {
	rows, err := q.db.Query(ctx, inconsistentLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InconsistentLinksRow{}
	for rows.Next() {
		var i InconsistentLinksRow
		if err := rows.Scan(&i.ID, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO ledger.accounts (id, book, code, currency, normal, non_negative, batched, clearing, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertAccountParams struct {
	ID          string
	Book        string
	Code        string
	Currency    string
	Normal      string
	NonNegative bool
	Batched     bool
	Clearing    bool
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.Exec(ctx, insertAccount,
		arg.ID,
		arg.Book,
		arg.Code,
		arg.Currency,
		arg.Normal,
		arg.NonNegative,
		arg.Batched,
		arg.Clearing,
		arg.CreatedAt,
	)
	return err
}

const insertEntries = `-- name: InsertEntries :exec
INSERT INTO ledger.entries (transaction_id, transaction_kind, account_id, book, currency, layer, amount)
SELECT $1::text, $2::text,
       unnest($3::text[]), unnest($4::text[]), unnest($5::text[]),
       unnest($6::text[]), unnest($7::bigint[])
`

type InsertEntriesParams struct {
	TransactionID   string
	TransactionKind string
	AccountIds      []string
	Books           []string
	Currencies      []string
	Layers          []string
	Amounts         []int64
}

// Set-returning functions in a select list advance together, so the arrays are zipped
// in order, and rows are inserted (and balance rows locked) in the order Go sorted them.
func (q *Queries) InsertEntries(ctx context.Context, arg InsertEntriesParams) error {
	_, err := q.db.Exec(ctx, insertEntries,
		arg.TransactionID,
		arg.TransactionKind,
		arg.AccountIds,
		arg.Books,
		arg.Currencies,
		arg.Layers,
		arg.Amounts,
	)
	return err
}

const insertTransaction = `-- name: InsertTransaction :exec
INSERT INTO ledger.transactions (id, kind, resolves_id, reverses_id, expires_at, entry_count, description, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertTransactionParams struct {
	ID          string
	Kind        string
	ResolvesID  pgtype.Text
	ReversesID  pgtype.Text
	ExpiresAt   pgtype.Timestamptz
	EntryCount  int32
	Description string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.Exec(ctx, insertTransaction,
		arg.ID,
		arg.Kind,
		arg.ResolvesID,
		arg.ReversesID,
		arg.ExpiresAt,
		arg.EntryCount,
		arg.Description,
		arg.CreatedAt,
	)
	return err
}

const lockApplier = `-- name: LockApplier :exec
SELECT pg_advisory_xact_lock(hashtext('ledger.balance_queue'))
`

func (q *Queries) LockApplier(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockApplier)
	return err
}

const lockBalance = `-- name: LockBalance :one
SELECT account_id FROM ledger.balances WHERE account_id = $1 FOR UPDATE
`

func (q *Queries) LockBalance(ctx context.Context, accountID string) (string, error) {
	row := q.db.QueryRow(ctx, lockBalance, accountID)
	var account_id string
	err := row.Scan(&account_id)
	return account_id, err
}

const lockBalances = `-- name: LockBalances :exec
SELECT account_id FROM ledger.balances WHERE account_id = ANY($1::text[]) ORDER BY account_id FOR UPDATE
`

func (q *Queries) LockBalances(ctx context.Context, accountIds []string) error {
	_, err := q.db.Exec(ctx, lockBalances, accountIds)
	return err
}

const markDrifted = `-- name: MarkDrifted :exec
UPDATE ledger.balances SET drifted_at = $1::timestamptz
WHERE account_id = ANY($2::text[]) AND drifted_at IS NULL
`

type MarkDriftedParams struct {
	Now        pgtype.Timestamptz
	AccountIds []string
}

func (q *Queries) MarkDrifted(ctx context.Context, arg MarkDriftedParams) error {
	_, err := q.db.Exec(ctx, markDrifted, arg.Now, arg.AccountIds)
	return err
}

const overduePendingTransfers = `-- name: OverduePendingTransfers :many
SELECT t.id, t.expires_at
FROM ledger.transactions t
WHERE t.kind = 'pending'
  AND t.expires_at < $1::timestamptz
  AND NOT EXISTS (SELECT 1 FROM ledger.transactions r WHERE r.resolves_id = t.id)
ORDER BY t.expires_at, t.id
`

type OverduePendingTransfersRow struct {
	ID        string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) OverduePendingTransfers(ctx context.Context, overdueBefore pgtype.Timestamptz) ([]OverduePendingTransfersRow, error) {
	rows, err := q.db.Query(ctx, overduePendingTransfers, overdueBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OverduePendingTransfersRow{}
	for rows.Next() {
		var i OverduePendingTransfersRow
		if err := rows.Scan(&i.ID, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repairBalance = `-- name: RepairBalance :exec
WITH recomputed AS (
    SELECT coalesce(sum(d.posted_debits), 0)::bigint AS posted_debits,
           coalesce(sum(d.posted_credits), 0)::bigint AS posted_credits,
           coalesce(sum(d.pending_debits), 0)::bigint AS pending_debits,
           coalesce(sum(d.pending_credits), 0)::bigint AS pending_credits
    FROM ledger.entries e
    CROSS JOIN LATERAL ledger.entry_deltas(e.transaction_kind, e.layer, e.amount) d
    WHERE e.account_id = $1::text
), queued AS (
    SELECT coalesce(sum(posted_debits), 0)::bigint AS posted_debits,
           coalesce(sum(posted_credits), 0)::bigint AS posted_credits,
           coalesce(sum(pending_debits), 0)::bigint AS pending_debits,
           coalesce(sum(pending_credits), 0)::bigint AS pending_credits
    FROM ledger.balance_queue
    WHERE account_id = $1::text
)
UPDATE ledger.balances b
   SET posted_debits   = r.posted_debits - q.posted_debits,
       posted_credits  = r.posted_credits - q.posted_credits,
       pending_debits  = r.pending_debits - q.pending_debits,
       pending_credits = r.pending_credits - q.pending_credits,
       drifted_at      = NULL
  FROM recomputed r, queued q
 WHERE b.account_id = $1::text
`

// Resets one cached balance to what its entries prove, net of deltas still queued, and
// clears its drift mark. Run it while holding the balance row's lock.
func (q *Queries) RepairBalance(ctx context.Context, accountID string) error {
	_, err := q.db.Exec(ctx, repairBalance, accountID)
	return err
}

const tryApplierLock = `-- name: TryApplierLock :one
SELECT pg_try_advisory_xact_lock(hashtext('ledger.balance_queue'))
`

func (q *Queries) TryApplierLock(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, tryApplierLock)
	var pg_try_advisory_xact_lock bool
	err := row.Scan(&pg_try_advisory_xact_lock)
	return pg_try_advisory_xact_lock, err
}

const unbalancedTransactions = `-- name: UnbalancedTransactions :many
SELECT t.id, t.entry_count, count(e.seq)::integer AS actual_count
FROM ledger.transactions t
LEFT JOIN ledger.entries e ON e.transaction_id = t.id
GROUP BY t.id, t.entry_count
HAVING count(e.seq) <> t.entry_count
    OR EXISTS (
        SELECT 1 FROM ledger.entries x
        WHERE x.transaction_id = t.id
        GROUP BY x.book, x.currency, x.layer
        HAVING sum(x.amount) <> 0
    )
ORDER BY t.id
`

type UnbalancedTransactionsRow struct {
	ID          string
	EntryCount  int32
	ActualCount int32
}

func (q *Queries) UnbalancedTransactions(ctx context.Context) ([]UnbalancedTransactionsRow, error) {
	rows, err := q.db.Query(ctx, unbalancedTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnbalancedTransactionsRow{}
	for rows.Next() {
		var i UnbalancedTransactionsRow
		if err := rows.Scan(&i.ID, &i.EntryCount, &i.ActualCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
