// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeSecrets = `-- name: ActiveSecrets :many
SELECT id, sealed FROM events.endpoint_secrets
WHERE endpoint_id = $1 AND (expires_at IS NULL OR expires_at > $2::timestamptz)
ORDER BY created_at DESC, id DESC
`

type ActiveSecretsParams struct {
	EndpointID string
	Now        pgtype.Timestamptz
}

type ActiveSecretsRow struct {
	ID     string
	Sealed []byte
}

func (q *Queries) ActiveSecrets(ctx context.Context, arg ActiveSecretsParams) ([]ActiveSecretsRow, error) {
	rows, err := q.db.Query(ctx, activeSecrets, arg.EndpointID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActiveSecretsRow{}
	for rows.Next() {
		var i ActiveSecretsRow
		if err := rows.Scan(&i.ID, &i.Sealed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteEndpoint = `-- name: DeleteEndpoint :one
UPDATE events.endpoints SET deleted_at = $1::timestamptz
WHERE id = $2 AND merchant_id = $3 AND livemode = $4 AND deleted_at IS NULL
RETURNING id, merchant_id, livemode, url, description, enabled_events, status, api_version, created_at, deleted_at
`

type DeleteEndpointParams struct {
	Now        pgtype.Timestamptz
	ID         string
	MerchantID string
	Livemode   bool
}

func (q *Queries) DeleteEndpoint(ctx context.Context, arg DeleteEndpointParams) (EventsEndpoint, error) {
	row := q.db.QueryRow(ctx, deleteEndpoint,
		arg.Now,
		arg.ID,
		arg.MerchantID,
		arg.Livemode,
	)
	var i EventsEndpoint
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Url,
		&i.Description,
		&i.EnabledEvents,
		&i.Status,
		&i.ApiVersion,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const expireSecrets = `-- name: ExpireSecrets :exec
UPDATE events.endpoint_secrets
SET expires_at = least(coalesce(expires_at, $1::timestamptz), $1::timestamptz)
WHERE endpoint_id = $2 AND (expires_at IS NULL OR expires_at > $3::timestamptz)
`

type ExpireSecretsParams struct {
	ExpiresAt  pgtype.Timestamptz
	EndpointID string
	Now        pgtype.Timestamptz
}

func (q *Queries) ExpireSecrets(ctx context.Context, arg ExpireSecretsParams) error {
	_, err := q.db.Exec(ctx, expireSecrets, arg.ExpiresAt, arg.EndpointID, arg.Now)
	return err
}

const getEndpoint = `-- name: GetEndpoint :one
SELECT id, merchant_id, livemode, url, description, enabled_events, status, api_version, created_at, deleted_at FROM events.endpoints WHERE id = $1 AND merchant_id = $2 AND livemode = $3 AND deleted_at IS NULL
`

type GetEndpointParams struct {
	ID         string
	MerchantID string
	Livemode   bool
}

func (q *Queries) GetEndpoint(ctx context.Context, arg GetEndpointParams) (EventsEndpoint, error) {
	row := q.db.QueryRow(ctx, getEndpoint, arg.ID, arg.MerchantID, arg.Livemode)
	var i EventsEndpoint
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Url,
		&i.Description,
		&i.EnabledEvents,
		&i.Status,
		&i.ApiVersion,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEndpointByID = `-- name: GetEndpointByID :one
SELECT id, merchant_id, livemode, url, description, enabled_events, status, api_version, created_at, deleted_at FROM events.endpoints WHERE id = $1
`

func (q *Queries) GetEndpointByID(ctx context.Context, id string) (EventsEndpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointByID, id)
	var i EventsEndpoint
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Url,
		&i.Description,
		&i.EnabledEvents,
		&i.Status,
		&i.ApiVersion,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, merchant_id, livemode, type, object_id, object_type, created_at FROM events.events WHERE id = $1 AND merchant_id = $2 AND livemode = $3
`

type GetEventParams struct {
	ID         string
	MerchantID string
	Livemode   bool
}

func (q *Queries) GetEvent(ctx context.Context, arg GetEventParams) (EventsEvent, error) {
	row := q.db.QueryRow(ctx, getEvent, arg.ID, arg.MerchantID, arg.Livemode)
	var i EventsEvent
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Type,
		&i.ObjectID,
		&i.ObjectType,
		&i.CreatedAt,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, merchant_id, livemode, type, object_id, object_type, created_at FROM events.events WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id string) (EventsEvent, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i EventsEvent
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Type,
		&i.ObjectID,
		&i.ObjectType,
		&i.CreatedAt,
	)
	return i, err
}

const insertDelivery = `-- name: InsertDelivery :exec
INSERT INTO events.deliveries (id, event_id, endpoint_id, attempt, succeeded, response_status, error, duration_ms, attempted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertDeliveryParams struct {
	ID             string
	EventID        string
	EndpointID     string
	Attempt        int32
	Succeeded      bool
	ResponseStatus pgtype.Int4
	Error          string
	DurationMs     int32
	AttemptedAt    pgtype.Timestamptz
}

func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) error {
	_, err := q.db.Exec(ctx, insertDelivery,
		arg.ID,
		arg.EventID,
		arg.EndpointID,
		arg.Attempt,
		arg.Succeeded,
		arg.ResponseStatus,
		arg.Error,
		arg.DurationMs,
		arg.AttemptedAt,
	)
	return err
}

const insertEndpoint = `-- name: InsertEndpoint :exec
INSERT INTO events.endpoints (id, merchant_id, livemode, url, description, enabled_events, status, api_version, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertEndpointParams struct {
	ID            string
	MerchantID    string
	Livemode      bool
	Url           string
	Description   string
	EnabledEvents []string
	Status        string
	ApiVersion    string
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) InsertEndpoint(ctx context.Context, arg InsertEndpointParams) error {
	_, err := q.db.Exec(ctx, insertEndpoint,
		arg.ID,
		arg.MerchantID,
		arg.Livemode,
		arg.Url,
		arg.Description,
		arg.EnabledEvents,
		arg.Status,
		arg.ApiVersion,
		arg.CreatedAt,
	)
	return err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events.events (id, merchant_id, livemode, type, object_id, object_type, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertEventParams struct {
	ID         string
	MerchantID string
	Livemode   bool
	Type       string
	ObjectID   string
	ObjectType string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.ID,
		arg.MerchantID,
		arg.Livemode,
		arg.Type,
		arg.ObjectID,
		arg.ObjectType,
		arg.CreatedAt,
	)
	return err
}

const insertSecret = `-- name: InsertSecret :exec
INSERT INTO events.endpoint_secrets (id, endpoint_id, sealed, created_at) VALUES ($1, $2, $3, $4)
`

type InsertSecretParams struct {
	ID         string
	EndpointID string
	Sealed     []byte
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertSecret(ctx context.Context, arg InsertSecretParams) error {
	_, err := q.db.Exec(ctx, insertSecret,
		arg.ID,
		arg.EndpointID,
		arg.Sealed,
		arg.CreatedAt,
	)
	return err
}

const listDeliveries = `-- name: ListDeliveries :many
SELECT id, event_id, endpoint_id, attempt, succeeded, response_status, error, duration_ms, attempted_at FROM events.deliveries WHERE event_id = $1 ORDER BY attempted_at, id
`

func (q *Queries) ListDeliveries(ctx context.Context, eventID string) ([]EventsDelivery, error) {
	rows, err := q.db.Query(ctx, listDeliveries, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventsDelivery{}
	for rows.Next() {
		var i EventsDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EndpointID,
			&i.Attempt,
			&i.Succeeded,
			&i.ResponseStatus,
			&i.Error,
			&i.DurationMs,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndpoints = `-- name: ListEndpoints :many
SELECT id, merchant_id, livemode, url, description, enabled_events, status, api_version, created_at, deleted_at FROM events.endpoints
WHERE merchant_id = $1 AND livemode = $2 AND deleted_at IS NULL
  AND ($3::text = '' OR id < $3)
  AND ($4::text = '' OR id > $4)
ORDER BY CASE WHEN $4 <> '' THEN id END ASC, id DESC
LIMIT $5::integer
`

type ListEndpointsParams struct {
	MerchantID    string
	Livemode      bool
	StartingAfter string
	EndingBefore  string
	MaxCount      int32
}

func (q *Queries) ListEndpoints(ctx context.Context, arg ListEndpointsParams) ([]EventsEndpoint, error) {
	rows, err := q.db.Query(ctx, listEndpoints,
		arg.MerchantID,
		arg.Livemode,
		arg.StartingAfter,
		arg.EndingBefore,
		arg.MaxCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventsEndpoint{}
	for rows.Next() {
		var i EventsEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Livemode,
			&i.Url,
			&i.Description,
			&i.EnabledEvents,
			&i.Status,
			&i.ApiVersion,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, merchant_id, livemode, type, object_id, object_type, created_at FROM events.events
WHERE merchant_id = $1 AND livemode = $2
  AND ($3::text = '' OR type = $3)
  AND ($4::text = '' OR id < $4)
  AND ($5::text = '' OR id > $5)
ORDER BY CASE WHEN $5 <> '' THEN id END ASC, id DESC
LIMIT $6::integer
`

type ListEventsParams struct {
	MerchantID    string
	Livemode      bool
	Type          string
	StartingAfter string
	EndingBefore  string
	MaxCount      int32
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]EventsEvent, error) {
	rows, err := q.db.Query(ctx, listEvents,
		arg.MerchantID,
		arg.Livemode,
		arg.Type,
		arg.StartingAfter,
		arg.EndingBefore,
		arg.MaxCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventsEvent{}
	for rows.Next() {
		var i EventsEvent
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Livemode,
			&i.Type,
			&i.ObjectID,
			&i.ObjectType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEndpoint = `-- name: LockEndpoint :one
SELECT id, merchant_id, livemode, url, description, enabled_events, status, api_version, created_at, deleted_at FROM events.endpoints WHERE id = $1 AND merchant_id = $2 AND livemode = $3 AND deleted_at IS NULL FOR UPDATE
`

type LockEndpointParams struct {
	ID         string
	MerchantID string
	Livemode   bool
}

func (q *Queries) LockEndpoint(ctx context.Context, arg LockEndpointParams) (EventsEndpoint, error) {
	row := q.db.QueryRow(ctx, lockEndpoint, arg.ID, arg.MerchantID, arg.Livemode)
	var i EventsEndpoint
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Url,
		&i.Description,
		&i.EnabledEvents,
		&i.Status,
		&i.ApiVersion,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const subscribedEndpoints = `-- name: SubscribedEndpoints :many
SELECT id FROM events.endpoints
WHERE merchant_id = $1 AND livemode = $2
  AND deleted_at IS NULL AND status = 'enabled'
  AND ($3::text = ANY(enabled_events) OR '*' = ANY(enabled_events))
ORDER BY id
`

type SubscribedEndpointsParams struct {
	MerchantID string
	Livemode   bool
	Type       string
}

func (q *Queries) SubscribedEndpoints(ctx context.Context, arg SubscribedEndpointsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, subscribedEndpoints, arg.MerchantID, arg.Livemode, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEndpoint = `-- name: UpdateEndpoint :one
UPDATE events.endpoints
SET url = $1, description = $2, enabled_events = $3, status = $4
WHERE id = $5 AND merchant_id = $6 AND livemode = $7 AND deleted_at IS NULL
RETURNING id, merchant_id, livemode, url, description, enabled_events, status, api_version, created_at, deleted_at
`

type UpdateEndpointParams struct {
	Url           string
	Description   string
	EnabledEvents []string
	Status        string
	ID            string
	MerchantID    string
	Livemode      bool
}

func (q *Queries) UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (EventsEndpoint, error) {
	row := q.db.QueryRow(ctx, updateEndpoint,
		arg.Url,
		arg.Description,
		arg.EnabledEvents,
		arg.Status,
		arg.ID,
		arg.MerchantID,
		arg.Livemode,
	)
	var i EventsEndpoint
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Url,
		&i.Description,
		&i.EnabledEvents,
		&i.Status,
		&i.ApiVersion,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
