// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SubscriptionsCycle struct {
	SubscriptionID string
	Number         int32
	DueDate        pgtype.Date
	PaymentIntent  string
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type SubscriptionsSubscription struct {
	ID                  string
	MerchantID          string
	Livemode            bool
	Amount              int64
	Currency            string
	Interval            string
	StartDate           pgtype.Date
	EndDate             pgtype.Date
	Description         string
	CustomerName        string
	CustomerTaxID       string
	Retries             bool
	AuthorizationMethod string
	PayerIspb           string
	PayerBranch         string
	PayerAccount        string
	Status              string
	SetUp               bool
	SetupAttemptedAt    pgtype.Timestamptz
	RecurrenceID        string
	QrCode              string
	CanceledBy          string
	EndCode             string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}
