// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeRules = `-- name: ActiveRules :many
SELECT id, merchant_id, livemode, action, expression, description, created_at, deleted_at FROM risk.rules WHERE merchant_id = $1 AND livemode = $2 AND deleted_at IS NULL ORDER BY id
`

type ActiveRulesParams struct {
	MerchantID string
	Livemode   bool
}

func (q *Queries) ActiveRules(ctx context.Context, arg ActiveRulesParams) ([]RiskRule, error) {
	rows, err := q.db.Query(ctx, activeRules, arg.MerchantID, arg.Livemode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RiskRule{}
	for rows.Next() {
		var i RiskRule
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Livemode,
			&i.Action,
			&i.Expression,
			&i.Description,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const activeThrottle = `-- name: ActiveThrottle :one
SELECT merchant_id, livemode, started_at, until, ratio, attempts FROM risk.throttles
WHERE merchant_id = $1 AND livemode = $2 AND until > $3
ORDER BY started_at DESC
LIMIT 1
`

type ActiveThrottleParams struct {
	MerchantID string
	Livemode   bool
	Now        pgtype.Timestamptz
}

func (q *Queries) ActiveThrottle(ctx context.Context, arg ActiveThrottleParams) (RiskThrottle, error) {
	row := q.db.QueryRow(ctx, activeThrottle, arg.MerchantID, arg.Livemode, arg.Now)
	var i RiskThrottle
	err := row.Scan(
		&i.MerchantID,
		&i.Livemode,
		&i.StartedAt,
		&i.Until,
		&i.Ratio,
		&i.Attempts,
	)
	return i, err
}

const decisionForAttempt = `-- name: DecisionForAttempt :one
SELECT id, attempt_id, intent_id, merchant_id, livemode, action, rules, features, created_at FROM risk.decisions WHERE attempt_id = $1
`

func (q *Queries) DecisionForAttempt(ctx context.Context, attemptID string) (RiskDecision, error) {
	row := q.db.QueryRow(ctx, decisionForAttempt, attemptID)
	var i RiskDecision
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.IntentID,
		&i.MerchantID,
		&i.Livemode,
		&i.Action,
		&i.Rules,
		&i.Features,
		&i.CreatedAt,
	)
	return i, err
}

const deleteListItem = `-- name: DeleteListItem :execrows
DELETE FROM risk.list_items WHERE id = $1 AND merchant_id = $2 AND livemode = $3
`

type DeleteListItemParams struct {
	ID         string
	MerchantID string
	Livemode   bool
}

func (q *Queries) DeleteListItem(ctx context.Context, arg DeleteListItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteListItem, arg.ID, arg.MerchantID, arg.Livemode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRule = `-- name: DeleteRule :one
UPDATE risk.rules SET deleted_at = $1
WHERE id = $2 AND merchant_id = $3 AND livemode = $4 AND deleted_at IS NULL
RETURNING id, merchant_id, livemode, action, expression, description, created_at, deleted_at
`

type DeleteRuleParams struct {
	Now        pgtype.Timestamptz
	ID         string
	MerchantID string
	Livemode   bool
}

func (q *Queries) DeleteRule(ctx context.Context, arg DeleteRuleParams) (RiskRule, error) {
	row := q.db.QueryRow(ctx, deleteRule,
		arg.Now,
		arg.ID,
		arg.MerchantID,
		arg.Livemode,
	)
	var i RiskRule
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Action,
		&i.Expression,
		&i.Description,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDecision = `-- name: GetDecision :one
SELECT id, attempt_id, intent_id, merchant_id, livemode, action, rules, features, created_at FROM risk.decisions WHERE id = $1 AND merchant_id = $2 AND livemode = $3
`

type GetDecisionParams struct {
	ID         string
	MerchantID string
	Livemode   bool
}

func (q *Queries) GetDecision(ctx context.Context, arg GetDecisionParams) (RiskDecision, error) {
	row := q.db.QueryRow(ctx, getDecision, arg.ID, arg.MerchantID, arg.Livemode)
	var i RiskDecision
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.IntentID,
		&i.MerchantID,
		&i.Livemode,
		&i.Action,
		&i.Rules,
		&i.Features,
		&i.CreatedAt,
	)
	return i, err
}

const iPVelocity = `-- name: IPVelocity :one
SELECT
    count(*) FILTER (WHERE created_at > $1)::integer AS ip_attempts_1h,
    count(DISTINCT card_fingerprint)::integer AS ip_cards_24h
FROM risk.attempts
WHERE ip = $2 AND merchant_id = $3 AND livemode = $4 AND created_at > $5
`

type IPVelocityParams struct {
	HourAgo    pgtype.Timestamptz
	Ip         string
	MerchantID string
	Livemode   bool
	DayAgo     pgtype.Timestamptz
}

type IPVelocityRow struct {
	IpAttempts1h int32
	IpCards24h   int32
}

func (q *Queries) IPVelocity(ctx context.Context, arg IPVelocityParams) (IPVelocityRow, error) {
	row := q.db.QueryRow(ctx, iPVelocity,
		arg.HourAgo,
		arg.Ip,
		arg.MerchantID,
		arg.Livemode,
		arg.DayAgo,
	)
	var i IPVelocityRow
	err := row.Scan(&i.IpAttempts1h, &i.IpCards24h)
	return i, err
}

const insertAttempt = `-- name: InsertAttempt :exec
INSERT INTO risk.attempts (attempt_id, merchant_id, livemode, card_fingerprint, ip, created_at, outcome)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (attempt_id) DO NOTHING
`

type InsertAttemptParams struct {
	AttemptID       string
	MerchantID      string
	Livemode        bool
	CardFingerprint string
	Ip              string
	CreatedAt       pgtype.Timestamptz
	Outcome         string
}

func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) error {
	_, err := q.db.Exec(ctx, insertAttempt,
		arg.AttemptID,
		arg.MerchantID,
		arg.Livemode,
		arg.CardFingerprint,
		arg.Ip,
		arg.CreatedAt,
		arg.Outcome,
	)
	return err
}

const insertDecision = `-- name: InsertDecision :exec
INSERT INTO risk.decisions (id, attempt_id, intent_id, merchant_id, livemode, action, rules, features, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (attempt_id) DO NOTHING
`

type InsertDecisionParams struct {
	ID         string
	AttemptID  string
	IntentID   string
	MerchantID string
	Livemode   bool
	Action     string
	Rules      []byte
	Features   []byte
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertDecision(ctx context.Context, arg InsertDecisionParams) error {
	_, err := q.db.Exec(ctx, insertDecision,
		arg.ID,
		arg.AttemptID,
		arg.IntentID,
		arg.MerchantID,
		arg.Livemode,
		arg.Action,
		arg.Rules,
		arg.Features,
		arg.CreatedAt,
	)
	return err
}

const insertListItem = `-- name: InsertListItem :one
INSERT INTO risk.list_items (id, merchant_id, livemode, list, kind, value, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (merchant_id, livemode, list, kind, value) DO UPDATE SET value = excluded.value
RETURNING id, merchant_id, livemode, list, kind, value, created_at
`

type InsertListItemParams struct {
	ID         string
	MerchantID string
	Livemode   bool
	List       string
	Kind       string
	Value      string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertListItem(ctx context.Context, arg InsertListItemParams) (RiskListItem, error) {
	row := q.db.QueryRow(ctx, insertListItem,
		arg.ID,
		arg.MerchantID,
		arg.Livemode,
		arg.List,
		arg.Kind,
		arg.Value,
		arg.CreatedAt,
	)
	var i RiskListItem
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.List,
		&i.Kind,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const insertRule = `-- name: InsertRule :one
INSERT INTO risk.rules (id, merchant_id, livemode, action, expression, description, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, merchant_id, livemode, action, expression, description, created_at, deleted_at
`

type InsertRuleParams struct {
	ID          string
	MerchantID  string
	Livemode    bool
	Action      string
	Expression  string
	Description string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertRule(ctx context.Context, arg InsertRuleParams) (RiskRule, error) {
	row := q.db.QueryRow(ctx, insertRule,
		arg.ID,
		arg.MerchantID,
		arg.Livemode,
		arg.Action,
		arg.Expression,
		arg.Description,
		arg.CreatedAt,
	)
	var i RiskRule
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Livemode,
		&i.Action,
		&i.Expression,
		&i.Description,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertThrottle = `-- name: InsertThrottle :exec
INSERT INTO risk.throttles (merchant_id, livemode, started_at, until, ratio, attempts)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT DO NOTHING
`

type InsertThrottleParams struct {
	MerchantID string
	Livemode   bool
	StartedAt  pgtype.Timestamptz
	Until      pgtype.Timestamptz
	Ratio      float64
	Attempts   int32
}

func (q *Queries) InsertThrottle(ctx context.Context, arg InsertThrottleParams) error {
	_, err := q.db.Exec(ctx, insertThrottle,
		arg.MerchantID,
		arg.Livemode,
		arg.StartedAt,
		arg.Until,
		arg.Ratio,
		arg.Attempts,
	)
	return err
}

const listDecisions = `-- name: ListDecisions :many
SELECT id, attempt_id, intent_id, merchant_id, livemode, action, rules, features, created_at FROM risk.decisions
WHERE merchant_id = $1 AND livemode = $2
  AND ($3::text = '' OR action = $3)
  AND ($4::text = '' OR intent_id = $4)
  AND ($5::text = '' OR id < $5)
  AND ($6::text = '' OR id > $6)
ORDER BY CASE WHEN $6 <> '' THEN id END ASC, id DESC
LIMIT $7::integer
`

type ListDecisionsParams struct {
	MerchantID    string
	Livemode      bool
	Action        string
	IntentID      string
	StartingAfter string
	EndingBefore  string
	MaxCount      int32
}

func (q *Queries) ListDecisions(ctx context.Context, arg ListDecisionsParams) ([]RiskDecision, error) {
	rows, err := q.db.Query(ctx, listDecisions,
		arg.MerchantID,
		arg.Livemode,
		arg.Action,
		arg.IntentID,
		arg.StartingAfter,
		arg.EndingBefore,
		arg.MaxCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RiskDecision{}
	for rows.Next() {
		var i RiskDecision
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.IntentID,
			&i.MerchantID,
			&i.Livemode,
			&i.Action,
			&i.Rules,
			&i.Features,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT id, merchant_id, livemode, list, kind, value, created_at FROM risk.list_items WHERE merchant_id = $1 AND livemode = $2 ORDER BY id
`

type ListItemsParams struct {
	MerchantID string
	Livemode   bool
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]RiskListItem, error) {
	rows, err := q.db.Query(ctx, listItems, arg.MerchantID, arg.Livemode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RiskListItem{}
	for rows.Next() {
		var i RiskListItem
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Livemode,
			&i.List,
			&i.Kind,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMerchant = `-- name: LockMerchant :exec
SELECT pg_advisory_xact_lock(hashtextextended('risk/' || $1::text, 0))
`

// A decision's lock: on a card, an address at a merchant, or a merchant.
func (q *Queries) LockMerchant(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, lockMerchant, key)
	return err
}

const matchingListItems = `-- name: MatchingListItems :many
SELECT id, merchant_id, livemode, list, kind, value, created_at FROM risk.list_items
WHERE merchant_id = $1 AND livemode = $2
  AND ((kind = 'card_fingerprint' AND value = $3) OR (kind = 'ip' AND value = $4) OR (kind = 'bin' AND value = $5))
ORDER BY list = 'allow' DESC, id
`

type MatchingListItemsParams struct {
	MerchantID string
	Livemode   bool
	Card       string
	Ip         string
	Bin        string
}

func (q *Queries) MatchingListItems(ctx context.Context, arg MatchingListItemsParams) ([]RiskListItem, error) {
	rows, err := q.db.Query(ctx, matchingListItems,
		arg.MerchantID,
		arg.Livemode,
		arg.Card,
		arg.Ip,
		arg.Bin,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RiskListItem{}
	for rows.Next() {
		var i RiskListItem
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Livemode,
			&i.List,
			&i.Kind,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const merchantVelocity = `-- name: MerchantVelocity :one
SELECT
    count(*) FILTER (WHERE created_at > $1)::integer AS attempts_1m,
    count(*)::integer AS attempts_10m,
    count(*) FILTER (WHERE outcome = 'declined')::integer AS declines_10m,
    count(*) FILTER (WHERE outcome IN ('approved', 'declined'))::integer AS decided_10m
FROM risk.attempts
WHERE merchant_id = $2 AND livemode = $3 AND created_at > $4
`

type MerchantVelocityParams struct {
	MinuteAgo     pgtype.Timestamptz
	MerchantID    string
	Livemode      bool
	TenMinutesAgo pgtype.Timestamptz
}

type MerchantVelocityRow struct {
	Attempts1m  int32
	Attempts10m int32
	Declines10m int32
	Decided10m  int32
}

func (q *Queries) MerchantVelocity(ctx context.Context, arg MerchantVelocityParams) (MerchantVelocityRow, error) {
	row := q.db.QueryRow(ctx, merchantVelocity,
		arg.MinuteAgo,
		arg.MerchantID,
		arg.Livemode,
		arg.TenMinutesAgo,
	)
	var i MerchantVelocityRow
	err := row.Scan(
		&i.Attempts1m,
		&i.Attempts10m,
		&i.Declines10m,
		&i.Decided10m,
	)
	return i, err
}

const setOutcome = `-- name: SetOutcome :exec
UPDATE risk.attempts SET outcome = $1 WHERE attempt_id = $2 AND outcome = 'pending'
`

type SetOutcomeParams struct {
	Outcome   string
	AttemptID string
}

func (q *Queries) SetOutcome(ctx context.Context, arg SetOutcomeParams) error {
	_, err := q.db.Exec(ctx, setOutcome, arg.Outcome, arg.AttemptID)
	return err
}

const velocity = `-- name: Velocity :one
SELECT
    count(*) FILTER (WHERE card_fingerprint = $1 AND created_at > $2)::integer AS card_attempts_1h,
    count(*) FILTER (WHERE card_fingerprint = $1)::integer AS card_attempts_24h,
    count(*) FILTER (WHERE card_fingerprint = $1 AND outcome = 'declined')::integer AS card_declines_24h
FROM risk.attempts
WHERE card_fingerprint = $1 AND livemode = $3 AND created_at > $4
`

type VelocityParams struct {
	Card     string
	HourAgo  pgtype.Timestamptz
	Livemode bool
	DayAgo   pgtype.Timestamptz
}

type VelocityRow struct {
	CardAttempts1h  int32
	CardAttempts24h int32
	CardDeclines24h int32
}

func (q *Queries) Velocity(ctx context.Context, arg VelocityParams) (VelocityRow, error) {
	row := q.db.QueryRow(ctx, velocity,
		arg.Card,
		arg.HourAgo,
		arg.Livemode,
		arg.DayAgo,
	)
	var i VelocityRow
	err := row.Scan(&i.CardAttempts1h, &i.CardAttempts24h, &i.CardDeclines24h)
	return i, err
}
